### ISSUE TITLE
update  nested section throw error `index out of range.`

### ISSUE THREAD

**Issue by zhixzhan** [microsoft/botframework-cli#1004]
## Versions
What CLI version are you using.
What Nodejs version are you using
What command-line interpreters are you using
What OS are you using

## Describe the bug

```
 > !# @enableSections = true

# CheckTodo
## CheckUnreadTodo
- check my unread todo
- show my unread todos

@ simple todoTitle

## CheckDeletedTodo
- check my deleted todo
- show my deleted todos

@ simple todoSubject
```

update `CheckTodo` with content:
```
# CheckTodo
## CheckUnreadTodo
  - please check my unread todo
  - show my unread todos

@ simple todoTitle
```

see error.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
<img width="1704" alt="image" src="https://user-images.githubusercontent.com/49866537/94982244-9d157200-056b-11eb-82a8-4465a89f8527.png">
<img width="2037" alt="image" src="https://user-images.githubusercontent.com/49866537/94982251-a7d00700-056b-11eb-9244-0409f1ea33c3.png">

## Additional context

[bug]

**Comment by feich-ms** [comment]
closed since it was caused by another PR https://github.com/microsoft/botframework-cli/pull/1002 and the issue is resolved there.
