### ISSUE TITLE
orchestratorAdaptiveRecognizer exits with status 3221225477

### ISSUE THREAD

**Issue by ecuellar2** [microsoft/botframework-cli#1033]
I am using pretrained.20200924.microsoft.dte.00.12.roberta.en.onnx because the other versions were raising errors:
pretrained.20200924.microsoft.dte.00.12.en.onnx - 'Could not load encoder - bad json' when trying bf orchestrator:create
pretrained.20200924.microsoft.dte.00.03.en.onnx - 'Could not load encoder - bad json' when trying bf orchestrator:create

I then generated orchestrator.blu file using bf orchestrator:create. My app has 1 QnA KB and 1 LUIS app. My LUIS app uses luis_schema_version 7.0.0 and I am testing with emulator 4.10.0.

I am seeing botbuilder-ai-orchestrator raising error:
Error message:
code ELIFECYCLE
errno 3221225477
nlp-with-dispatch@1.0.0 start: node ./index.js
Exit status 3221225477

The error is in orchestratorAdaptiveRecognizer. The recognize() method fails on the step:
this.resolver.score(text);

If I print out console.log(this.resolver) I get 'LabelResolver {}' in the output, which makes me believe  Initialize() is getting properly called in orchestratorAdaptiveRecognizer.
My package.json file references dependencies:
"botbuilder": "4.10.0",
"botbuilder-ai": "4.10.0",
"botbuilder-ai-orchestrator": "4.11.0-dev.20200813.01cd644",

Can you confirm if these versions of orchestrator pretrained model and botbuilder-ai-orchestrator are compatible?

**Comment by mdrichardson** [comment]
@ecuellar2 Generally, you want to:

1. Ensure all bot* packages are on the exact same version,
2. Avoid the `dev` versions unless there's a particular reason that you want to use it

Can you please include all of your `.json`/`.qna`/`.lu`/`.blu` files so that I can attempt to repro?

`3221225477` error is an Access Violation error. It may help to run `npm cache clean --force` as a troubleshooting step, as well.

**Comment by taicchoumsft** [comment]
@ecuellar2 , thanks for reporting this issue. Can you help us to collect more specific info to help us troubleshoot this issue?  

We'd like to collect the `orchestrator-core` version that got installed on your machine, from BF-CLI (which you used to author the blu files), and for your project (which read back the blu file that was generated):
1) If you're on windows, could you navigate to `%AppData%\..\Local\@microsoft\botframework-cli\node_modules\orchestrator-core\package.json` and provide the `version` in this file?
2) Similarly for your bot project, can you navigate to `\node_modules\orchestrator-core\package.json` and provide the `version` in this file?

**Comment by ecuellar2** [comment]
Below are the details you requested.
AppData\Local\@microsoft\botframework-cli\node_modules\orchestrator-core\package.json
version": "4.10.0-dev.20200916.980ea2d"

code_path\node_modules\orchestrator-core\package.json
"version": "4.11.0-dev.20201008.cb67719"

**Comment by hcyang** [comment]
Hi @ecuellar2,

As we have been actively developing Orchestrator and updating the models. Please uninstall, then reinstall your bf-orchestrator-cli plugin. Also you would have to the same for your botbuilder-ai-orchestrator package.

**Comment by ecuellar2** [comment]
Steps taken:
bf plugins:uninstall @microsoft/bf-orchestrator-cli
bf orchestrator -h    Error: command orchestrator not found (this is expected)
npm install -g @microsoft/botframework-cli
bf orchestrator -h    (Confirmed command now works)

Went to folder below and confirmed version went from 4.10.0-dev.20200916.980ea2d to 4.11.0-dev.20201024.0c5247b.
AppData\Local\@microsoft\botframework-cli\node_modules\orchestrator-core\package.json


bf plugins:install @microsoft/bf-orchestrator-cli@beta
node_modules\orchestrator-core\package.json version did not change and stayed at 4.11.0-dev.20201008.cb67719

Ran command below (looks like nlr:get is no longer used)
bf orchestrator:basemodel:get 

Ran bf orchestrator:create 

Then ran emulator. Error still appears in orchestratorAdaptiveRecognizer. Please let me know if I missed any step.

**Comment by hcyang** [comment]
Hi @ecuellar2,

Yes, for authoring, you have successfully reinstalled bf-orchestrator-cli using the correct orchestrator-core version. 

For the second orchestrator-core, can you tell us which runtime were you using? Botbuilder-js and  botbuilder-ai-orchestrator? Please reinstall them as well.

**Comment by hcyang** [comment]
Hi @ecuellar2,

Can you share with us the header line of the .blu snapshot file you created using bf-orchestrator-cli "create" command? We would like to see the version numbers.

Thanks,

**Comment by ecuellar2** [comment]
base_model_version,runtime_version	pretrained.20200924.microsoft.dte.00.06.en.onnx,1.0.0
This is from orchestrator.blu, which was created today using "bf orchestrator:basemodel:get"

I will work on re-install other steps you mentioned and report back.

**Comment by taicchoumsft** [comment]
Hi @ecuellar2, if you can't get `orchestrator-core` version in your project to be at least 4.11.0-dev.20201028`, can you try this steps? 

- In your project folder,  `npm remove botbuilder-ai-orchestrator`
- clear your npm cache: `npm cache clean --force` to remove the cached orchestrator-core 
- install the `next` version of `botbuilder-ai-orchestrator`: `npm install botbuilder-ai-orchestrator@next`

This should force `orchestrator-core` to be updated for the project.

**Comment by ecuellar2** [comment]
I updated orchestrator-core. Version is now 4.11.0-dev.20201029.862a357.
I performed another test and confirmed 3221225477 error is now gone. Thank you.
