### ISSUE TITLE
[bf luis:generate:cs] Disparity with bf luis:generate:ts to try/catch errors

### ISSUE THREAD

**Issue by fran893** [microsoft/botframework-cli#1050]
## Versions
What CLI version are you using.
4.10.1 or [master](https://github.com/microsoft/botframework-cli) branch

What Nodejs version are you using
12.14.1

What command-line interpreters are you using
bf luis:generate:cs

What OS are you using
Windows 10

## Describe the bug
There is a disparity between the [bf luis:generate:cs](https://github.com/microsoft/botframework-cli/blob/main/packages/luis/src/commands/luis/generate/cs.ts) and the [bf luis:generate:ts](https://github.com/microsoft/botframework-cli/blob/main/packages/luis/src/commands/luis/generate/ts.ts) commands. This cause that the `:cs` is throwing a generic error because it's not catching correctly the error as they are not wrapped in a `try/catch` sentence like in the `:ts.`

## To Reproduce
1. See [async run()](https://github.com/microsoft/botframework-cli/blob/main/packages/luis/src/commands/luis/generate/cs.ts#L44) of [bf luis:generate:cs](https://github.com/microsoft/botframework-cli/blob/main/packages/luis/src/commands/luis/generate/cs.ts).
2. See [async run()](https://github.com/microsoft/botframework-cli/blob/main/packages/luis/src/commands/luis/generate/ts.ts#L42) of bf [luis:generate:ts](https://github.com/microsoft/botframework-cli/blob/main/packages/luis/src/commands/luis/generate/ts.ts).
3. Check the differences of wrapping in a try/catch sentence.

## Expected behavior
The command should throw the same error like [bf luis:generate:ts](https://github.com/microsoft/botframework-cli/blob/main/packages/luis/src/commands/luis/generate/ts.ts), and not a generic one wrapping the process in a try/catch sentence.

## Screenshots
_Executing bf luis:generate:cs in the Virtual Assistant root folder_

![image](https://user-images.githubusercontent.com/51216149/98403070-21658400-2047-11eb-96e6-ba890f3e07b5.png)

_Executing bf luis:generate:ts in the Virtual Assistant root folder_

![image](https://user-images.githubusercontent.com/51216149/98403101-304c3680-2047-11eb-8515-6bf049fc3ce6.png)

_cs.ts vs ts.ts code_

![image](https://user-images.githubusercontent.com/51216149/98403131-3cd08f00-2047-11eb-818f-25f75905f3f8.png)

## Additional context
See microsoft/botframework-solutions#3693

[bug]

**Comment by cwhitten** [comment]
@munozemilio please take a look

**Comment by munozemilio** [comment]
@axelsrz could you please take a look on this?

**Comment by axelsrz** [comment]
@fran893 THanks for submitting this issue. We will include the appropiate fix in our next release cycle, thanks.
