### ISSUE TITLE
LU Export doesn't work for intents and features with the same name

### ISSUE THREAD

**Issue by abhishekpsen** [microsoft/botframework-cli#1051]
## Versions
LU 4.9.1

## Describe the bug
LU export doesn't allow intent and features to have the same name

## To Reproduce
1. Create an app
2. Add an intent, named say 'abc'
3. Add a feature to the above intent with the same name ('abc')
4. Export as LU

## Expected behavior
LU Export should work fine, JSON export doesn't hit this error.

Source IcM: https://portal.microsofticm.com/imp/v3/incidents/details/212216724/home

[bug]

**Comment by munozemilio** [comment]
Hello @abhishekpsen this is quite an old version, Ill try to reproduce on 4.11 and get back to you

**Comment by munozemilio** [comment]
Closing this since after a code review this is by design on the LU side
