### ISSUE TITLE
LU Export doesn't work for intents with special characters in the name

### ISSUE THREAD

**Issue by abhishekpsen** [microsoft/botframework-cli#1052]
## Versions
LU 4.9.1

## Describe the bug
LU export doesn't work if app has intents with special characters in the name

## To Reproduce
Create an app
Add an intent, named with special characters like "'" and "á".
Export as LU

## Expected behavior
LU Export should work fine, JSON export doesn't hit this error.

Source IcM: https://portal.microsofticm.com/imp/v3/incidents/details/212216724/home

[bug]

**Comment by munozemilio** [comment]
Hello @abhishekpsen this is quite an old version, Ill try to reproduce on 4.11 and get back to you

**Comment by munozemilio** [comment]
Hi @feich-ms could you please help me with this one?

**Comment by feich-ms** [comment]
@munozemilio sure, will take a look.

**Comment by feich-ms** [comment]
Fixed in this PR https://github.com/microsoft/botframework-cli/pull/1058
