### ISSUE TITLE
While executing the "dispatch create" command getting error

### ISSUE THREAD

**Issue by rbdemo** [microsoft/botframework-cli#1053]
Hi All,
While executing the "dispatch create" command getting below error:
Getting Error:
{
  "error": {
    "code": "401",
    "message": "The apps - Import application Operation under LUIS Programmatic APIs v3.0-preview is not supported with the current subscription key and pricing tier LUIS.S0."
  }
}

_Originally posted by @sarlasankar in https://github.com/microsoft/botframework-cli/issues/599#issuecomment-652964730_

**Comment by tsuwandy** [comment]
@rbdemo, this looks to be LUIS subscription issue.  Is the authoring key specified when creating dispatch an LUIS cognitive service authoring (or authoring + runtime)?

**Comment by tsuwandy** [comment]
Closing as @rbdemo fixed this issue by using the right key.
