### ISSUE TITLE
[Orchestrator-BugBash] warnings when installing plugin

### ISSUE THREAD

**Issue by v-kydela** [microsoft/botframework-cli#1054]
## Versions
What CLI version are you using.
@microsoft/botframework-cli/4.11.0 win32-x64 node-v12.18.3
What Nodejs version are you using
v12.18.3
What command-line interpreters are you using
cmd
What OS are you using
Windows 8.1

## Describe the bug

The following warnings are encountered when installing the Orchestrator plugin:

```
warning @microsoft/bf-orchestrator-cli > @microsoft/bf-orchestrator > orchestrator-core > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @microsoft/bf-orchestrator-cli > @microsoft/bf-orchestrator > orchestrator-core > node-gyp > request > har-validator@5.1.5: this library is no longer supported
```

## To Reproduce
1. Install the Orchestrator plugin as described [here](https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/orchestrator#prepare).
1. See warnings

## Expected behavior
The plugin should install without warnings

## Screenshots
![image](https://user-images.githubusercontent.com/41968495/98732513-1ca91480-2354-11eb-976e-4d03f676a800.png)

[bug]

**Comment by daveta** [comment]
Hi @v-kydela : This warning comes from one of our dependencies.  We'll update our package once the source package warning is addressed.  For tracking, here's the PR from the source.

https://github.com/nodejs/node-gyp/pull/2220

**Comment by tonyanziano** [comment]
Hi @daveta , was the `node-gyp` dependency ever bumped to get rid of this warning in bf-cli? If so, please close this issue. Thanks

**Comment by daveta** [comment]
Yep, this was fixed - the orchestrator is now not a plugin, but in the main bf-cli package.
