### ISSUE TITLE
[QnA maker] When exporting letters with accents, output is not correct.

### ISSUE THREAD

**Issue by ancorrg** [microsoft/botframework-cli#1057]
## Versions
@microsoft/botframework-cli/4.11.0 win32-x64 node-v12.19.0
Powhershell

## Describe the bug
I'm trying to export an existing kb from a qnamaker service and replace another one in other service with its contents. The original KB is in spanish and has accents and ñ characters. When I export the KB, the content is encoded in a way that can't be used in the destination KB.

## To Reproduce

1 bf qnamkaer:kb:export --kbId {id} --subscriptionKey {key} --qnaFormat > qnaEs.qna
2 bf qnamaker:kb:replace --in qnaEs.qna --kbId {destinationKB} --subscriptionKey {destinationKey}

## Expected behavior
The commands should export and import special characters for languages that are not english.

## Additional context

[bug]

**Comment by munozemilio** [comment]
Hello @ancorrg. Thanks a lot for reporting this issue. I just created a kb with special characters in it and the command is working fine which suggests the issue might be on the powershell [configuration](https://stackoverflow.com/questions/49476326/displaying-unicode-in-powershell). You can double check this by running the command on a different terminal like bash.
This is what my test looked like:
![Screen Shot 2020-11-23 at 4 52 52 PM](https://user-images.githubusercontent.com/43281931/100032811-abcf1700-2dad-11eb-86a0-5d442a53af8f.png)
Let me know if changing the configuration for PS worked for you.

**Comment by feich-ms** [comment]
@munozemilio there is another issue here https://github.com/microsoft/botframework-solutions/issues/3723 to track the similar issue, I made a PR #1065 to add --out support for kb export. Hope this works. Could you help to review?
