### ISSUE TITLE
BF qnamaker init node error (node:12300) Warning: Accessing  non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency

### ISSUE THREAD

**Issue by dinobrago** [microsoft/botframework-cli#1059]
## Versions
What CLI version are you using.    @microsoft/botframework-cli/4.11.0 win32-x64 
What Nodejs version are you using node-v14.15.1
What command-line interpreters are you using: Powershell or cmd, same problem
What OS are you using: Windows 10

## Describe the bug
When running the bf qnamaker:init command, get the error below
```
node.exe : What is your QnAMaker access/subscription key? (found on the Cognitive Services Azure portal page under "access keys") : (node:9484) Warning: Accessing 
non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
At C:\Users\xxxxxxxxx\AppData\Roaming\npm\bf.ps1:15 char:3
+   & "node$exe"  "$basedir/node_modules/@microsoft/botframework-cli/bi ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (What is your Qn...ular dependency:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9484) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
```

## To Reproduce
1) Installed bf cli per documentation: npm i -g @microsoft/botframework-cli
2) Ran command: bf qnamaker:init

## Expected behavior
Apparently this should be prompting me for my qna access/subscription key

[bug]

**Comment by dinobrago** [comment]
Repeated this on a clean machine, windows server 2012 r2

**Comment by axelsrz** [comment]
Hello @dinobrago, thanks for submitting this. The engineer who will drive this to closure will come back from vaction on Monday, thanks for the patience.

**Comment by munozemilio** [comment]
Hello @dinobrago, thanks for reporting this. Im able to reproduce on node 14. I will include this as a fix in the next release cycle. At the moment the Node Version supported is 12 for BF CLI. Sorry for the inconvenience.

**Comment by munozemilio** [comment]
Hello @dinobrago, after evaluation we have decided to wait another cycle on supporting node 14 given node 12 is still LTS and a lot of our customers are running on that version. Sadly the fix on the anltr side is not backward compatible with node 12.
