### ISSUE TITLE
ANTLR 4 depends on node >= 14 which breaks bf-generate

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botframework-cli#1060]
## Versions
@microsoft/botframework-cli/4.11.0 win32-x64 node-v12.16.1
Windows

## Describe the bug
@microsoft/bf-lu was changed to use Antlr4 rather than Antlr4ts which is what the SDK uses.  This introduces a dependency on node >= 14 which conflicts with composer's node >= 12.  This happens because bf-generate uses the cli LU parser in the CLI to do merges.  

## To Reproduce
1. npm config set @microsoft:registry https://botbuilder.myget.org/F/botframework-cli/npm/ 
 npm config set registry https://botbuilder.myget.org/F/botbuilder-v4-js-daily/npm/ 
2. bf plugins:install @microsoft/bf-generate

## Expected behavior
Plugin should install.  In actuality you get this error: 
error antlr4@4.9.0: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.16.1"
error Found incompatible module.

[bug]

**Comment by dawwa** [comment]
@chrimc62  @munozemilio , this repros with http://registry.npmjs.org as well

**Comment by munozemilio** [comment]
Closed by #1063
