### ISSUE TITLE
Adding an appazureaccount to a LUIS app should support taking an ARM token via file.

### ISSUE THREAD

**Issue by stevengum** [microsoft/botframework-cli#107]
Per this issue: https://github.com/microsoft/botbuilder-tools/issues/1227

We should add the ability to pass in an ARM token via file to get around the problem with Windows taking in command lines with a length of less than 8192 characters.

> After testing the command in VS Code, it's not a problem in the code base. The dummy token wasn't rejected because of its length, just because it was an invalid token.
> 
> This requirement on length is actually due to Windows: https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation
> 
> After searching for workarounds, it seems that using a relatively unladen service principal _might_ be a valid workaround. Alternatively there could be an enhancement to the CLI tool in the future that makes it possible to pass in a file that contains the ARM token instead of passing it in directly via the cmd.
> 
> @emiliomunoz FYI

[Comment from the relevant issue](https://github.com/microsoft/botbuilder-tools/issues/1227#issuecomment-524417665).

**Comment by scheyal** [comment]
AZ CLI tool requirement
(marked as 4.6. if disagree, push out)

**Comment by stevengum** [comment]
@munozemilio I think @jspruance resolved this issue in the 4.7 milestone?
