### ISSUE TITLE
QnaMaker command is returning empty responses

### ISSUE THREAD

**Issue by scheyal** [microsoft/botframework-cli#1075]
## Versions
What CLI version are you using.
What Nodejs version are you using
@microsoft/botframework-cli/4.11.1 win32-x64 node-v12.18.4
What command-line interpreters are you using
Windows cmd.exe
What OS are you using
Windows

## Describe the bug
QnAMaker command returns an empty string.

## To Reproduce

```
>bf qnamaker:query --kbId %QNAKBID% --endpointKey %QNAKEY% --hostname %QNAHOST% --question "What is vacation time?"
""

>bf qnamaker:query --kbId %QNAKBID% --endpointKey %QNAKEY% --hostname %QNAHOST% --question "What is vacation?"
""

>bf qnamaker:kb:get --kbId %QNAKBID% --endpoint %QNAHOST% --subscriptionKey %QNAKEY%
""

```

**Comment by munozemilio** [comment]
just talked to @scheyal over teams and the command is working fine. The command should log a better error response

**Comment by daveta** [comment]
Closing per @scheyal
