### ISSUE TITLE
Adjust qnamaker builder to accept qna v5.0 APIs

### ISSUE THREAD

**Issue by feich-ms** [microsoft/botframework-cli#1077]
**Is your feature request related to a problem? Please describe.**
Composer plans to enable QnA v5-preview APIs to support multi regions and other capabilities. To support this, BF-CLI should support:
1. Generate new kind of recognizer like Microsoft.QnAMakerRecognizerV2 for v5 API
2. Generate new runtime settings config for v5-preview runtime API

**Describe the solution you'd like**
1. Generate different qnamaker runtime settings config based on v4 or v5 API
2. Generate different qnamaker recognizer files based on v4 or v5 API
2. Adjust cli to output different config messages to console when calling different version api

**Describe alternatives you've considered**

**Additional context**

[enhancement]
.

**Comment by FrancoCorleone** [comment]
Is it happening? It took me 2 hrs to find what's wrong.. I had to override the endpoint manually but it's a pain ** *** ***. Also, I have no clue if the rest of the API works...

**Comment by feich-ms** [comment]
Hi @FrancoCorleone, sorry for the confusion. The support for qna v5 api is still in our backlog list and we have no ETA now. We will let you now once it's ready. Thanks for your patience.
