### ISSUE TITLE
In the lu file, @ phraselist works @ phraseList DOES NOT

### ISSUE THREAD

**Issue by jbinko** [microsoft/botframework-cli#1084]
## Versions
@microsoft/botframework-cli/4.11.1 linux-x64 node-v10.19.0

## Describe the bug
In the lu file - behavior of @ phraselist is case sensitive.
 If you create and specify @ phraseList My_PhraseList  (with upper L) as I saw in the documentation it is ignored and not defining phrase list.
this wil fail
@ ml MyEntity usesFeature My_PhraseList

if you change declaration to 
@ phraselist My_PhraseList  (with lower l)
this wil be OK
@ ml MyEntity usesFeature My_PhraseList

## To Reproduce
Just do as I mentioned above

## Expected behavior
I'd expected either error or case insensitivity but not curent behavior which is kind of silently ignoring the declaration.
Also check the documentation as it is using multiple variants: 
https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lu-file-format?view=azure-bot-service-4.0
[bug]

**Comment by joshgummersall** [comment]
We've assigned this issue to @munozemilio who owns the CLI tools, he will take a look.

**Comment by munozemilio** [comment]
Thanks for reporting this @jbinko, I will submit a PR to the docs repo to fix this issue.

**Comment by feich-ms** [comment]
@munozemilio I also created a similar [issue ](https://github.com/microsoft/botframework-cli/issues/1068)before. And last Friday I made a fix to make the entity type case insensitive here https://github.com/microsoft/botframework-cli/pull/1091. Do you think we should let the entity type case insensitive? If so, above PR can fix this issue as well.

**Comment by feich-ms** [comment]
It should be addressed in PR #1091 already, `phraselist`  should be case insensitive now. so I think we can close this one.
