### ISSUE TITLE
luis:application:import returns id with quotes surrounded

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/botframework-cli#1085]
## Versions
CLI: Latest Daily build
Node: v14.15.3.
PowerShell on Win10

The returned ID from the command luis:application:import returns the ID with quotes

$result = bf luis:application:import --in $_.modelLocation --endpoint $autoringEndpoint --subscriptionKey $autoringKey --json | ConvertFrom-Json
echo $result.id
Output:
"xxxx-xxxxxx-xxxxx"

[bug]

**Comment by gabog** [comment]
Hi @munozemilio, can you take a closer look at this one? 

Thanks

**Comment by munozemilio** [comment]
Hello @cxbuilders, thanks for reaching out. The cli  is a wrapper of the LUIS endpoint and as a result the output is just the same as the return by the [service](https://westus.dev.cognitive.microsoft.com/docs/services/luis-programmatic-apis-v3-0-preview/operations/5890b47c39e2bb052c5b9c31).
