### ISSUE TITLE
luis:convert does not handle LUIS settings

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botframework-cli#1100]
## Versions
CLI Version: @microsoft/botframework-cli/4.12.0-dev.20210126.0184ff0 win32-x64 node-v12.16.1
Node Version: 12.16.1
Windows 10

## Describe the bug
LUIS settings are not being included in the generated JSON which means importing a LU file into LUIS drops the settings.  This is a problem because LU file users cannot affect LUIS settings and LUIS exports don't round trip.

## To Reproduce
1. Create a LU file foo.lu that includes this in the header:
```
> !# @app.settings.NormalizePunctuation = true
> !# @app.settings.NormalizeWordForm = true
> !# @app.settings.UseAllTrainingData = true
```
2. bf luis:convert -i foo.lu -o foo.json
3. Open foo.json and you will not see a settings: [] section which means the LUIS settings are dropped.

## Expected behavior
You should see this:
```
 "settings": [
    {
      "name": "NormalizePunctuation",
      "value": "true"
    },
    {
      "name": "NormalizeWordForm",
      "value": "true"
    },
    {
      "name": "UseAllTrainingData",
      "value": "true"
    }
  ]
```

Anything in the LU file with the > !# @app.PATH = VALUE prefix should be exported to the JSON.  The lack of this functionality means you cannot round-trip LUIS models that modify settings.  The current LUIS export will include the settings in the exported file.

## Additional context
I looked at the repo and it looks like the bf-lu library is part of the CLI which implies that it has the latest bf-lu parser.  The part which is missing is to put that into the JSON output when doing build or convert.  It looks like only some of the properties like name and culture are being passed through when it should pass through all properties.

[bug]

**Comment by munozemilio** [comment]
@feich-ms is this something you can take a look at?

**Comment by scheyal** [comment]
Desire to do in R12 if possible.

**Comment by feich-ms** [comment]
@munozemilio sure, will take a fix soon.
@scheyal It can target R12.

**Comment by feich-ms** [comment]
Hi @chrimc62, I just tried the case you described, but could not repro it with my machine. The bf-cli convert command can convert the headers you provided to settings in luis json. The version I used is same with you. So did I miss any other steps to reproduce it?

![image](https://user-images.githubusercontent.com/43032123/106712944-a8b99800-6634-11eb-8b56-9cb3ef9330a7.png)

**Comment by feich-ms** [comment]
Synced with @chrimc62, this can be reproduced with import definitions like below. I will take a fix soon.
![image](https://user-images.githubusercontent.com/43032123/106977937-3791f600-6796-11eb-9799-c09b293d4457.png)
