### ISSUE TITLE
[qnamaker:init] Flags for non-interactive automation scripts 

### ISSUE THREAD

**Issue by a7i** [microsoft/botframework-cli#1103]
**Is your feature request related to a problem? Please describe.**
I am having issues using `qnamaker:init` in GitHub Actions since it is prompting for input such as subscription, etc.

**Describe the solution you'd like**
It would be ideal to provide flags via CLI or set environment variables to skip prompts.

**Describe alternatives you've considered**
The alternative is to use the SDK instead of CLI.

**Additional context**
```
bf qnamaker:init

This util will walk you through the QnA Maker config settings

Press ^C at any time to quit.

What is your QnAMaker access/subscription key? (found on the Cognitive Services Azure portal page under "access keys"): <<some input>>
What would you like to use as your active knowledgebase ID? [none] : <<some input>>
```

[enhancement]

**Comment by srinaath** [comment]
@munozemilio  Could you take a look at this ticket?

**Comment by munozemilio** [comment]
@a7i thanks for bringing this up. I will try to accommodate in the current release if possible. Otherwise this will be part of the following.

**Comment by munozemilio** [comment]
Hello @a7i would this [command](https://github.com/microsoft/botframework-cli/tree/main/packages/config#bf-configsetqnamaker) cover your needs?

**Comment by a7i** [comment]
> Hello @a7i would this [command](https://github.com/microsoft/botframework-cli/tree/main/packages/config#bf-configsetqnamaker) cover your needs? If it doesn't work for you feel free to re open this issue.

@munozemilio It's perfect, thank you!
