### ISSUE TITLE
Different LUIS predictions using same .lu file for two different Azure subscriptions

### ISSUE THREAD

**Issue by ericchansen** [microsoft/botframework-cli#1105]
## Versions

What CLI version are you using: **4.11.1**
What Node.js version are you using: **14.15.4 x64**
What command-line interpreters are you using: **?**
What OS are you using: **This is in an Azure Pipelines run using the pool "windows-latest"**

## Describe the bug

We're using update_cognitive_models.ps1 from https://github.com/microsoft/botframework-solution. Here's a link to the script https://github.com/microsoft/botframework-solutions/blob/master/templates/csharp/VA/VA/Deployment/Scripts/update_cognitive_models.ps1.

We have the same branch of our code that we're deploying to two different Azure environments (dev and test). These environments are essentially identical besides their names. We're using all the same .lu files. It seems that when we run `bf luis:convert` via update_cognitive_models.ps1 (see https://github.com/microsoft/botframework-solutions/blob/211ce82b0afff5c5f4199f45eb1e1b8932071d25/templates/csharp/VA/VA/Deployment/Scripts/luis_functions.ps1#L71-L76) we get two .json output files (one for each stage of our Azure pipeline) and the files will be identical **except for the patterns section of the .json. The patterns sections contains the same data, but in a different order/sorted differently.** Otherwise, everything that we can see looks identical.

update_cognitive_models.ps1 goes on to import https://github.com/microsoft/botframework-solutions/blob/211ce82b0afff5c5f4199f45eb1e1b8932071d25/templates/csharp/VA/VA/Deployment/Scripts/luis_functions.ps1#L121-L127, train https://github.com/microsoft/botframework-solutions/blob/211ce82b0afff5c5f4199f45eb1e1b8932071d25/templates/csharp/VA/VA/Deployment/Scripts/luis_functions.ps1#L139-L144 and publish the model https://github.com/microsoft/botframework-solutions/blob/211ce82b0afff5c5f4199f45eb1e1b8932071d25/templates/csharp/VA/VA/Deployment/Scripts/luis_functions.ps1#L145-L149.

When I test the model in the LUIS portal, I will get different scores and even different intents.

## To Reproduce

1. Use https://github.com/microsoft/botframework-solutions.
2. Use update_cognitive_models.ps1 to update your LUIS models.

## Expected behavior

I expect to take the exact same .lu file and get nearly the exact same results, no matter what.

## Screenshots

Please let me know if you need screenshots of anything, and I'll add them.

Here's an example of what should be the exact same LUIS model. One environment is shown on the left and the other environment is shown on the right. Notice how the scores are different.

![image](https://user-images.githubusercontent.com/5395779/106840151-8f810d80-666d-11eb-8bb1-143e3360b547.png)

## Additional context

Please let me know if you need any additional context, and I'll add it.

[bug]

**Comment by stevkan** [comment]
@ericchansen, it's important to note that scoring in LUIS is non-deterministic meaning that scores can vary for the same query/input between different instances. I am not as sure about that with intents so I am waiting to hear back from a colleague I have reached out to regarding that matter. I will update this thread when I know more.

**Comment by ericchansen** [comment]
@stevkan Certainly, scoring is non-deterministic. It should be possible to determine if confidence variations as large as 0.1 can stem only from non-determinism. That seemed unlikely to me, but I'm not sure.

**Comment by stevkan** [comment]
Another option is to [turn off](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-how-to-train#train-with-all-data) non-deterministic training. In doing so, you are utilizing all of your data to train your model rather than only a sample. This should produce more stable results when testing.

**Comment by stevkan** [comment]
Closing as resolved. If additional help is needed on this issue, please feel free to re-open.
