### ISSUE TITLE
bf luis:test command fails for some files

### ISSUE THREAD

**Issue by scheyal** [microsoft/botframework-cli#1121]
The following line works for some data, and fails for other:

* Command: bf luis:test --subscriptionKey %LUISKEY% --endpoint %LUISHOST% --appId %LUISAPP% --in %TESTFILE% --out report/luisresult.txt
* Results (files are available via email):
 - Success: common.test.lu
 - Failure: schoolnavigatorbot.test.lu
 - Neither is in a format that can be used in the portal. 
* CLI Error:
```
Unknown error during execution. Please file an issue on https://github.com/microsoft/botframework-cli/issues
entities[name] is not iterable
```

Error is possibly coming from:

ParseEntityResult() method defined in $botframework-cli\packages\lu\src\parser\test\testhelper.ts. 
```
...
    } else {
      for (const subEntity of entities[name]) {
        if (typeof subEntity === 'object') {
          ParseEntitiyResult(subEntity, result)
        }
...
```

**Comment by munozemilio** [comment]
Hi @feich-ms, is this something you are familiar with?

**Comment by feich-ms** [comment]
@munozemilio this is work of Huanran Xu, but he will leave Microsoft at the end of this week. I can be backup and take a look. Could you or anyone else provide the pieces of schoolnavigatorbot.test.lu that raised this exception?

**Comment by feich-ms** [comment]
@scheyal could you provide the failure lu case of `schoolnavigatorbot.test.lu` so that I can debug and verify? Thanks.
