### ISSUE TITLE
bf qnamaker:bf:convert do not respect multiple languages

### ISSUE THREAD

**Issue by FrancoCorleone** [microsoft/botframework-cli#1147]
Hey all,
I am using the newest version of CLI. 
I've read here: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-bf-cli-deploy-qna?view=azure-bot-service-4.0 that I can have file with locales in filename and it will create sort of multiple KBs. But when I run convert it creates single json file with all entries merged into single knowledge base.
Am I doing something wrong or is it a bug?

**Comment by anusharavindrar** [comment]
@FrancoCorleone, just to get more clarity before attempting a  repro, did you follow this particular [part](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-bf-cli-deploy-qna?view=azure-bot-service-4.0#qna-maker-knowledge-bases-created) in the above linked documentation? Also, how many qna files are you trying to convert into separate KBs?

**Comment by FrancoCorleone** [comment]
Yes, I have it kinda sorted out with "build" command, but I got an impression that it should also work with convert and then publish. It's pretty inconsistent. Also I tried to set suffix to an empty string in build command, I don't need my name there, nor environment, doesn't make much sense for me... Unfortunately, it is ignored then and my name is used

**Comment by anusharavindrar** [comment]
@FrancoCorleone, after using the **--suffix** option, you are still getting the username as a part of the KB name?

**Comment by FrancoCorleone** [comment]
Well, I wanted to do --suffix "" to override the behaviour, but it detected the suffix empty and fell back to username

**Comment by anusharavindrar** [comment]
@FrancoCorleone, 

- If the suffix is omitted, it will make use of the username(if no username is found, it will return ‘development’).
- If the suffix parameter is supplied, but it is an empty string, it will still fall back to making use of the username. 
- If you do not want to use the username, you must supply a non-empty string. 

Hope this helps.
