### ISSUE TITLE
Fix chatdown according to new specs

### ISSUE THREAD

**Issue by scheyal** [microsoft/botframework-cli#116]
Review command line guidelines and ensure chatdown conforms to new guidelines.

**Comment by jspruance** [comment]
This work is complete & ticket can be closed.

**Comment by scheyal** [comment]
Thanks!

**Comment by scheyal** [comment]
It looks like latest build doesn't conform to spec.

https://github.com/microsoft/botframework-cli/blob/master/specs/ChatdownDevSpec.md

**Comment by jspruance** [comment]
It was my understanding that this ticket referred to the specs here:
https://github.com/microsoft/botframework-cli/blob/master/CONTRIBUTING.md

After evaluating the new specs, 'static' flag needs to be changed to 'stamp'. PR for this is here:
https://github.com/microsoft/botframework-cli/pull/275

After discussion w Emilio, 'recursive' flag not needed for chatdown. we can remove from specs or discuss further if we think we need it.

**Comment by scheyal** [comment]
ok
