### ISSUE TITLE
Error: Cannot find module 'antlr4/index'

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/botframework-cli#1175]
BF Version: latest
Node: 12.22
OS: Win 64
Tool: PS
![image](https://user-images.githubusercontent.com/49873947/113471350-0d8a4680-945c-11eb-8e4f-1e8082d99c96.png)

When executing the bf luis:build command it fails with the following error:
![image](https://user-images.githubusercontent.com/49873947/113471318-dfa50200-945b-11eb-923b-4624930c1b06.png)

During install it already gave this warning:
![image](https://user-images.githubusercontent.com/49873947/113471334-f77c8600-945b-11eb-836e-58d1f77094d1.png)

**Comment by peterinnesmsft** [comment]
@cxbuilders per the error output pasted above, it looks like your issues is that you need to upgrade your installed version of node to 14.x.x. I believe that's the latest LTS. Can you try that and let us know if you continue to see any issues here?

**Comment by munozemilio** [comment]
Hello @cxbuilders by the attached images I can tell you are running on a daily version: 4.10.0-dev.... The issue you are seeing comes from antlr. A few months ago they published a node non backward compatible version, thats when we started to see the issue. We had to pin the exact antlr version to keep supporting customer running on node versions lower than 14. My guess is the CLI version you are running on does not have the anltr version pinned yet. At the moment the CLI only supports node versions < 14. Can you please try running the latest bf cli version and check if you get the same issue?

**Comment by cxbuilders** [comment]
hey @munozemilio , yeah I downloaded the latest stable release and that was all ok.  Was a bit confused by the catch 22 situation, luckily that was just the dev.
