### ISSUE TITLE
lu/test/parser/lufile/luis.boundary.test.js failed in Mac environment

### ISSUE THREAD

**Issue by hcyang** [microsoft/botframework-cli#1176]
## Versions
What CLI version are you using.
What Nodejs version are you using
What command-line interpreters are you using
What OS are you using

## Describe the bug
Give a clear and concise description of what the bug is.

## To Reproduce
Run 'rush test' in an Azure Mac VM.

## Expected behavior
Unit tests should not fail a build pipeline.

## Screenshots
![image](https://user-images.githubusercontent.com/370110/113498237-0ac13d00-94c0-11eb-82f8-b3dbb2ce1b8d.png)

## Additional context
https://fuselabs.visualstudio.com/573d2162-939e-4be5-9daa-90ad050ec28e/_apis/build/builds/230840/logs/302

[bug]

FAILURE (1)
================================
@microsoft/bf-lu (1 minute 53.3 seconds)
(node:1354) UnhandledPromiseRejectionWarning: AssertionError: expected 521 to equal 512
    at LuisBuilder.fromLUAsync.then.catch.err (/Users/runner/work/1/s/botframework-cli/packages/lu/test/parser/lufile/luis.boundary.test.js:220:24)
(node:1354) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 34)
(node:1354) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
================================

**Comment by daveta** [comment]
@hcyang : Can we close this now?

**Comment by hcyang** [comment]
@munozemilio, we found some bf-cli tests failing in one of our ADO pipeline for Orchestrator. I think you would be interested getting an ADO Mac pipeline to test all bf-cli unit tests.

**Comment by munozemilio** [comment]
Closing since it has not happened again
