### ISSUE TITLE
CLI Microsoft Documentation Update (BF ...)

### ISSUE THREAD

**Issue by scheyal** [microsoft/botframework-cli#118]
Tracking.

Although most CLI will be within GitHub repos, I think we need some basic documentation, maybe full sample scenarios or pointers to basic tool usage, downloads?

Consider/discuss?

**Comment by scheyal** [comment]
A few link starting points:
* [Tools Overview](https://github.com/Microsoft/botbuilder-tools/blob/master/tools-overview.md)
* Port [CLI GitHub home](https://github.com/microsoft/botbuilder-tools/blob/master/README.md)
* Update [PortingMap.md](https://github.com/microsoft/botframework-cli/blob/master/PortingMap.md)

**Comment by scheyal** [comment]
(a) Waiting for team to reach "code complete" next week. 
(b) Engaged with Kamran regarding updating MS Docs (waiting for (a))
(c) Will do a final pass on GitHub docs once the team is done.
ETA:  The week  of 10/21-25 is reserved for final polish (at which time this bug will be done)

**Comment by cleemullins** [comment]
This isn't an actionable issue. I'm going to close this. Please re-open if necessary as actionable.
