### ISSUE TITLE
Update CLI documentation with latest commands (Orchestrator etc)

### ISSUE THREAD

**Issue by scheyal** [microsoft/botframework-cli#1187]
## Versions
What CLI version are you using.
What Nodejs version are you using
What command-line interpreters are you using
What OS are you using

## Describe the bug
Give a clear and concise description of what the bug is.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by daveta** [comment]
@scheyal : Can we close this?
