### ISSUE TITLE
Compliance: Clients Must Support the Ability to Securely Upgrade its User Base

### ISSUE THREAD

**Issue by scheyal** [microsoft/botframework-cli#120]
Need Information for compliance item:
Compliance 151124: [CA-1] Clients Must Support the Ability to Securely Upgrade its User Base
(details in Email)

**Comment by munozemilio** [comment]
BF CLI will check once a day for updates and prom the user to run the installation command to update the tool.
File: [hook](https://github.com/microsoft/botframework-cli/blob/master/packages/cli/src/hooks/init/inithook.ts) line 12 to 22
