### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botframework-cli#1222]
The existing readme for this repo is out-of-date. The CLI tools are no longer new, and all older tools are ported and/or deprecated. The readme needs a simple refresh. 

> The new BF Command Line Interface (CLI) tool replaces the collection of standalone tools used to manage Bot Framework bots and related services. We have ported most tools and are in process of porting the rest. The new BF CLI aggregates the collection of cross-platform tools into one cohesive and consistent interface.
> 
> The old tools will be deprecated in subsequent releases. All new investments, bug fixes, and new features will be implemented in the new consolidated BF CLI alone.

**Comment by scheyal** [comment]
Update: waiting for PR merge.
