### ISSUE TITLE
ludown translate to zh-Hans using ，、 instead of , in phraselist

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-cli#123]
## Tool
Name: Ludown
Version: 1.3.3
OS: Windows 10

## Describe the bug

 When traslating to zh-Hans, ',' in phraselist is translated to chinese '，', '、'.

## To Reproduce
1. add phraselist to lu file
2. ludown translate --to_lang zh-Hans

## Expected behavior

Still ','.

[bug]

**Comment by vishwacsena** [comment]
Resolving as won't fix. This is hard to detect and handle correctly in the tool. A better solution where user is in complete control would be to update the source LU file to have phrase list as an actual list instead of a comma separated list of values. 

```markdown
$ one : phraselist
    - one
    - two
```

Instead of this - 
```markdown
$ one : phraselist
    - one, two
```

**Comment by xieofxie** [comment]
Got it, thanks~
