### ISSUE TITLE
LU parser can generate erroneous entity output in  LUIS JSON output

### ISSUE THREAD

**Issue by hcyang** [microsoft/botframework-cli#1244]
## Versions
What CLI version are you using.
the 'main' branch

What Nodejs version are you using
v12.14.1

What command-line interpreters are you using
API

What OS are you using
Windows 10

## Describe the bug
Below is the code snippet using bf-cli's LU parser and generate a LUIS JSON object. It can generate an erroneous entity label which is not specified in the input LU file.
Will share the LU input and JSON through email as the files are under NDA.

const luisBuildNoValidate: any = require('@microsoft/bf-lu/lib/parser/luis/luisCollate').build;

    const luObject: any = {
      content: luContent,
      id: luFile,
    };
    const luisObject: any = await luisBuildNoValidate([luObject], false, '', OrchestratorHelper.findLuFiles);

## Expected behavior
Give a clear and concise description of what you expected to happen.
LU Parser should not generate an entity label in JSON if not specified in the LU input.

## Additional context

[bug]

**Comment by munozemilio** [comment]
Closed by #1296
