### ISSUE TITLE
Programmatic ludown translate fails

### ISSUE THREAD

**Issue by ctstone** [microsoft/botframework-cli#125]
## Tool

- Name: Ludown
- Version: 1.3.3
- OS: macOS 10.14.6

## Describe the bug

Ludown cannot translate text when used as a library, most likely due to the use of `this` and `export`

## To Reproduce

```js
const ludown = require('ludown');

// valid values not need to reproduce
const key = 'abc';
const text = '# Intent';
const lang = 'xx';
ludown.translate.parseAndTranslate(text, key, lang).then(console.log, console.error)
```

## Expected behavior

The text is translated

## Screenshots

```
TypeError: this.addSegment is not a function
    at Object.parseAndTranslate (/<snip>/node_modules/ludown/lib/translate-helpers.js:76:26)
```

## Additional context

The functions `parseAndTranslate` and `addSegment` are both methods of the `translateHelpers` [object](https://github.com/microsoft/botbuilder-tools/blob/1964e39f77dc85579ac227332842dc172de8258a/packages/Ludown/lib/translate-helpers.js#L18), however `parseAndTranslate` is being [exported](https://github.com/microsoft/botbuilder-tools/blob/1964e39f77dc85579ac227332842dc172de8258a/packages/Ludown/lib/exports.js#L16) alone, which is probably why `this.anything` cannot be resolved. Exports.js should export the full object, not just a method, or else the functions should be converted to not use `this`

A workaround is to import the helper directly:

```js
const translateHelpers = require('ludown/lib/translate-helpers')
translateHelpers.parseAndTranslate(text, key, 'xx').then(console.log, console.error)
```

[bug]

**Comment by vishwacsena** [comment]
Fixed via #145
