### ISSUE TITLE
Undefined error when parsing QnA file using LU parser

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botframework-cli#1276]
## Versions
@microsoft/botframework-cli/4.15.0-dev.20210723.bf1f054 win32-x64 node-v14.16.0

## Describe the bug
This was reported by a customer. If you have a QnA file with a link across multiple lines then you will get an 'undefined' error rather than any useful diagnostics.  

## To Reproduce
1. Create a QnA File foo.qna like: 
~~~
**Prompts:**
- [Files that Cannot Sync
](#1)

<a id = "1"/>

## ? Files that Cannot Sync
```
Files that cannot sync.
```
~~~
2. bf orchestrator:create -i foo.qna -m basemodel
3. You will get an undefined error in `BuildDialognostic` because context is a string and not a structure. 
```
    else if (context !== undefined) {
        const startPosition = new Position(context.start.line, context.start.column);
```

## Expected behavior
An error message indicating the line.

[bug]

**Comment by jongon** [comment]
I have the same problem here. I'm working with tsv files meanwhile

**Comment by tsuwandy** [comment]
@jongon, could you share the problematic .qna file?

**Comment by tsuwandy** [comment]
Looks like the content in the example above is invalid, see this page for valid .qna content.  https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-qna-file-format?view=azure-bot-service-4.0

Prompts should be part of a question.  The following will work fine:
# ?store hours
```
Most our stores are open M-F 9AM-10PM.
```
**Prompts:**
- [Files that Cannot Sync](#1)

<a id = "1"></a>

# ? Files that Cannot Sync
```
Files that cannot sync.
```

**Comment by tsuwandy** [comment]
Related issue https://github.com/microsoft/botframework-cli/issues/1294

**Comment by tsuwandy** [comment]
Fix should be available with the next bf cli daily deployment.

**Comment by fedsp** [comment]
Hi @tsuwandy, what do you mean by the daily deployment?
I'm facing the exact same issue using the latest release.

**Comment by tsuwandy** [comment]
@fedsp, yes, it should be in the stable version before end of the month.
