### ISSUE TITLE
Need to parse error from bf luis command

### ISSUE THREAD

**Issue by scheyal** [microsoft/botframework-cli#1277]
Getting error from LUIS command but the error structure isn't parsed so I can't tell what's wrong.

## version
@microsoft/botframework-cli/4.14.1 win32-x64 node-v14.17.3

## command

[BF]c:\workspace\botroot\sdk\Orchestrator\Samples\dotnet\nlp-with-entities>bf luis:build --in CognitiveModels --authoringKey 9b4....  --botName OrchEntitySample --log
Loading files...

c:\workspace\botroot\sdk\Orchestrator\Samples\dotnet\nlp-with-entities\CognitiveModels\HomeAutomation.lu loaded

[WARN] line 61:0 - line 61:7: no utterances found for intent definition: "# None"
c:\workspace\botroot\sdk\Orchestrator\Samples\dotnet\nlp-with-entities\CognitiveModels\Weather.lu loaded

[WARN] line 50:0 - line 50:7: no utterances found for intent definition: "# None"
Handling applications...
**Luis build failed: Cannot read property 'error' of undefined**

**Comment by munozemilio** [comment]
@cosmicshuai is this something you could take a look?

**Comment by mrivera-ms** [comment]
@munozemilio, @cosmicshuai, can you please update with the latest status?

**Comment by cosmicshuai** [comment]
I test this in my local env, copying the lu files as described in this issue from Botbuilder-Samples repo. 
There is no build error in my case: 
```
C:\Users\shuwan\Github\botframework-cli\packages\luis\bin>run luis:build -i CognitiveModels --authoringKey 8807ef......validKey --botName OrchEntitySample --log
Loading files...

C:\Users\shuwan\Github\botframework-cli\packages\luis\bin\CognitiveModels\a.lu loaded

[WARN] line 61:0 - line 61:7: no utterances found for intent definition: "# None"
C:\Users\shuwan\Github\botframework-cli\packages\luis\bin\CognitiveModels\b.lu loaded

[WARN] line 50:0 - line 50:7: no utterances found for intent definition: "# None"
Handling applications...
[WARN]: empty intent(s) # None are filtered when handling luis application
[WARN]: empty intent(s) # None are filtered when handling luis application
C:\Users\shuwan\Github\botframework-cli\packages\luis\bin\CognitiveModels\b.lu no changes

C:\Users\shuwan\Github\botframework-cli\packages\luis\bin\CognitiveModels\a.lu no changes

The published application setting:
{
    "b_en_us_lu": {
        "appId": "05b6971d-0764-4afe-aaee-a094180d3d00",
        "version": "0.1",
        "recognizes": [
            "Get Weather Condition",
            "Get Weather Forecast",
            "Location"
        ]
    },
    "a_en_us_lu": {
        "appId": "12e35410-03ad-43bf-a807-d9d7c193b1b5",
        "version": "0.1",
        "recognizes": [
            "ControlDevice",
            "Device",
            "deviceProperty",
            "Room"
        ]
    }
}
```
I've already added some extra check for the luis build error in this PR
https://github.com/microsoft/botframework-cli/pull/1214

The next step I did was I closed my Internet connection and run the command. I got the undefined error:
```
C:\Users\shuwan\Github\botframework-cli\packages\luis\bin>run luis:build -i CognitiveModels --authoringKey 8807efe4....validKey --botName OrchEntitySample --log    
Loading files...

C:\Users\shuwan\Github\botframework-cli\packages\luis\bin\CognitiveModels\a.lu loaded

[WARN] line 61:0 - line 61:7: no utterances found for intent definition: "# None"
C:\Users\shuwan\Github\botframework-cli\packages\luis\bin\CognitiveModels\b.lu loaded

[WARN] line 50:0 - line 50:7: no utterances found for intent definition: "# None"
Handling applications...
Luis build failed: Cannot read property 'error' of undefined
```
