### ISSUE TITLE
Cant use own set of knowledge base files in the Bot with orchestrator Sample

### ISSUE THREAD

**Issue by danieldangler** [microsoft/botframework-cli#1283]
## Versions
What CLI version are you using: 2.27.1
What Nodejs version are you using: 14.17.5
What command-line interpreters are you using: Powershell 7
What OS are you using: WIndows 10 Professional

## Describe the bug
I was trying to follow the Bot-Builder Sample "14.nlp-with-orchestrator" with my own set of QnA Maker Knowledge Bases but that isnt working for me. Everything works fine until i try to add my qna files to the Orchestrator. These files are .tsv files and not .qna fiiles which might cause the error, but i am not sure. I also was trying to test it out but i cant find a solution how i can convert the .tsv files to .qna files.

![image](https://user-images.githubusercontent.com/39704877/129805038-c52c759e-614c-47d7-b772-add8f9a1bfd5.png)

## To Reproduce
1. Follow the 14.nlp-with-orchestrator Sample in the Bot-Builder Samples (https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-orchestrator?view=azure-bot-service-4.0&tabs=cs)

2. Use your own Knowledge Bases in a .tsv file format

## Expected behavior
The Orchestrator should get updated with the informations from my knowledge bases

## Screenshots
![Inkedba9851c8-ea32-4bee-b425-836926048fa1_LI](https://user-images.githubusercontent.com/39704877/129804611-060b5231-f649-4c48-8daf-b97f7cf3e78b.jpg)

[bug]

**Comment by tsuwandy** [comment]
@danieldangler, you could skip the 
bf qnamaker:build step if you already  have your QnA Maker kb.   bf orchestrator:create  command can handle qna file in tsv format.

**Comment by LeeParrishMSFT** [comment]
Closed due to inactivity.
