### ISSUE TITLE
Entities and Patterns are not working with orchestrator

### ISSUE THREAD

**Issue by SRGajjala** [microsoft/botframework-cli#1286]

**Comment by tracyboehrer** [comment]
@SRGajjala Can you provide some more detail about this issue?

**Comment by SRGajjala** [comment]
I have added entity of Regex Entity type and used it in patterns feature of Luis.
I need to extract the information such as ticket number from user utterance by matching to the regex entity.
If the user submits any query matching the pattern, we are not able to get high score for the intent having this pattern defined.

**Comment by tracyboehrer** [comment]
@SRGajjala Is this in a Composer bot?  Can you provide the specific regex and sample utterance we can use to investigate?

**Comment by LeeParrishMSFT** [comment]
Closed due to lack of response.
