### ISSUE TITLE
Package Manager Error

### ISSUE THREAD

**Issue by corepk** [microsoft/botframework-cli#1289]
I am getting a Package Manager error when I tried to add a new package/component from the package manager

Could not load component list:Error Cannot create property '$bundled' on string '<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0"/><style>body{margin:0px;padding:0px;}iframe{width:100%;height:100%}</style><iframe src="http://www.airtel.in/dot/" width="100%" height="100%" frameborder=0></iframe>' *** Could not merge components ***

## Version

v2.1.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] Windows

**Comment by chrimc62** [comment]
@benbrown I have no idea why this is happening.  The merge process will go out to json schema as part of validation, but except for temporary internet issues it should work fine.  Do the people that are seeing this have poor internet access?  Wonder if there is a timeout.  The package uses axios to resolve URLs--we switched to that to better deal with people that have proxies.  Is it possible they have a proxy server setup?

**Comment by chrimc62** [comment]
@ParagHurkat is it possible this is caused by an issue with your proxy server?  
The XML looks like it is proxy related.  When we try to resolve a URL we are getting back that XML string as a result and the code is expecting an object which is why you get the error stack when we try to set a property on it.

**Comment by prajwal-ainapur** [comment]
Am getting the same error now. Using Composer 2.1.1. Please guide me on how to resolve this.

**Comment by benbrown** [comment]
@prajwal-ainapur this is due to your local network having a restriction on content. Make sure you can access json-schema.org.

**Comment by prajwal-ainapur** [comment]
> @prajwal-ainapur this is due to your local network having a restriction on content. Make sure you can access json-schema.org.

I tried and am not able to access the json-schema.org line on my WiFI as well as Mobile Data. Any recommendation on how to overcome this?
