### ISSUE TITLE
Prebuilt V2 entities need update

### ISSUE THREAD

**Issue by MatteoMeil** [microsoft/botframework-cli#1293]
## Versions
What CLI version are you using: **4.14.1**
What Nodejs version are you using: **14.17.1**
What command-line interpreters are you using: **CMD (Windows' command prompt)**
What OS are you using: **Win10 x64**

## Describe the bug
Prebuilt entities defined in [this file](https://github.com/microsoft/botframework-cli/blob/4.14.0/packages/lu/src/parser/utils/enums/luisbuiltintypes.js) needs to be updated.

This causes errors described in #1292 because prebuilt entities aren't recognized in [this line of code](https://github.com/microsoft/botframework-cli/blob/4.14.0/packages/lu/src/parser/lufile/parseFileContents.js#L1803)

As an example, prebuilt entity `datetimeV2` is available for culture `it-it` but as per [this file](https://github.com/microsoft/botframework-cli/blob/4.14.0/packages/lu/src/parser/utils/enums/luisbuiltintypes.js), it cannot be used in a `.lu` model.
The use of the entity causes the error described in #1292

**Notice that this bug affects [BotFramework Composer](https://github.com/microsoft/botframework-composer) that outputs a wrong error in cases like this one**

### Composer way
1. Create a new bot using BotFramework Composer
2. Change locale to `it-it`
3. Add `@ prebuilt datetimeV2` and `@ ml SomeEntity usesFeature datetimeV2` when defining a new trigger
4. Try to start the bot

### BF CLI way
1. Create a new `.lu` file using `datetimeV2` prebuilt entity
2. Run `bf luis:build` passing that file

## Expected behavior
It should allow the use of available features as in [LUIS Portal](https://www.luis.ai/)

## Screenshots
Not applicable

## Additional context
Not applicable

[bug]

**Comment by srinaath** [comment]
@MatteoMeil This looks to be tracked in the ticket you have enclosed and we would look to triage it in our upcoming releases. Closing this as a dupe.
