### ISSUE TITLE
Issue with command [bf orchestrator:create]

### ISSUE THREAD

**Issue by vinothkumar1097** [microsoft/botframework-cli#1311]
Hi Team,

I'm recently facing issue with bf command. I'm generating .blu file based on model and .qna/.lu files.

command : 
```
bf orchestrator:create --in ./dataSources --model ./model --out ./generated
```

Below is the error message
```
Processing C:\Local\dataSources\luis_nlp.lu...
Processing C:\Local\dataSources\test.qna...
Processing C:\Local\model\config.json...
Failed to parse C:\Local\model\config.json
```

model.config file
```
{	
	"TokenizerDirectory": "tokenizer", 
	"ModelPath": "model.onnx",
	"OutputDim": 768,
	"Runtime": "onnx",
	"GraphOptimizationLevel": "ORT_ENABLE_BASIC",
	"IntraOpNumThreads": 1,
	"OMP_WAIT_POLICY": "PASSIVE",
	"MaxConcurrency": 2,
	"Version": 3,
	"Tokenizer": "bert",
	"AddPrefixSpaceForBPETokenizer": true,
	"MaxSequenceLength": 128
}
```

**OS : Windows**
**BF CLI Version : 4.14.1**
**Node version : 14.17.5**

Need your help to resolve this.

Thanks.

**Comment by daveta** [comment]
@vinothkumar1097 : I noticed the error message said it couldn't access `\Local\model\config.json` but you typed the `model.config` file by mistake.  

Can you show the contents of `\Local\model\config.json`?  I should look something like this (depending on what model you chose to download).
{
  "VocabFile": "vocab.txt",
  "ModelFile": "model.onnx",
  "Name": "pretrained.20200924.microsoft.dte.00.06.en.onnx",
  "Framework": "onnx",
  "Publisher": "Microsoft",

**Comment by vinothkumar1097** [comment]
@daveta: Thanks for replying. Below is my ```model\config.json```
```
{
  "VocabFile": "vocab.txt",
  "ModelFile": "model.onnx",
  "Name": "pretrained.20200924.microsoft.dte.00.06.en.onnx",
  "Framework": "onnx",
  "Publisher": "Microsoft",
  "ModelType": "dte_bert",
  "Layers": 6,
  "EmbedderVersion": 1,
  "MinRequiredCoreVersion": "1.0.0"
}
```
And below are the commands i'm executing to generate .blu file.
```
bf orchestrator:basemodel:get --out ./model
bf orchestrator:add -t qna --id *** --key *** --routingName test_qna
bf orchestrator:add -t luis --id *** --key *** --endpoint *** --routingName test_luis
bf orchestrator:create --hierarchical --in ./dataSources --model ./model --out ./generated
```

**Comment by tsuwandy** [comment]
@vinothkumar1097, could you update orchestratorsettings.json, should be in c:\local, update path inside inputs to c:\local:\datasources?  Then try the command bf orchestrator:create again?

**Comment by mrivera-ms** [comment]
@vinothkumar1097, is your issue resolved? Please re-open if you need more help.
