### ISSUE TITLE
npm install of botframework cli not supported on MacOS M1 (arm64 architecture)

### ISSUE THREAD

**Issue by SamVanhoutte** [microsoft/botframework-cli#1315]
## Versions
What CLI version are you using: latest to install
What Nodejs version are you using: 16.13
What command-line interpreters are you using: bash
What OS are you using : MacOS, M1 version

## Describe the bug

- MacOS, running on MacbookPro with M1 chipset
- Trying to install CLI through npm with this command: `npm i -g @microsoft/botframework-cli`
- The terminal shows the following errors
> npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @microsoft/bf-orchestrator-cli@4.14.1: wanted {"os":"darwin,linux,win32","arch":"x64,ia32"} (current: {"os":"darwin","arch":"arm64"})
npm ERR! notsup Valid OS:    darwin,linux,win32
npm ERR! notsup Valid Arch:  x64,ia32
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: arm64

## To Reproduce

See above

## Expected behavior
I would expect this to work on the arm64 architecture as well

## Screenshots
![image](https://user-images.githubusercontent.com/3539605/140662463-3c13cdce-4b39-40a1-8144-bf56bd39d428.png)

## Additional context

[bug]

**Comment by anishprasad01** [comment]
Hi @SamVanhoutte,

Composer does not support multiple aspects of this system configuration. Firstly, the Node version is too high. Composer's requirements specify 14.x LTS. Furthermore, Composer does not support Apple's M1 chips or the ARM64 architecture as a whole. The only supported MacOS architecture is x64. The documentation of these points is linked below for reference.

- https://github.com/microsoft/BotFramework-Composer/blob/main/docs/supported-os.md#macos
- https://github.com/microsoft/BotFramework-composer#prerequisites

**Comment by anishprasad01** [comment]
@DanielHjelm,

You could install another Terminal app on your Mac (like iTerm2), and in the settings configure the new terminal to launch with the x86 emulation layer, Rosetta 2. Once you've done this, try installing bf-cli into this new environment and proceeding with the tasks you wish to perform.

**Comment by agvglobant** [comment]
I'm running the command "npm i -g @microsoft/botframework-cli" in iTerm2 running under Rosetta2 emulation, but i get the same error:

npm error code EBADPLATFORM
npm error notsup Unsupported platform for @microsoft/bf-orchestrator-cli@4.15.0: wanted {"os":"darwin,linux,win32","cpu":"x64,ia32"} (current: {"os":"darwin","cpu":"arm64"})
npm error notsup Valid os:   darwin,linux,win32
npm error notsup Actual os:  darwin
npm error notsup Valid cpu:  x64,ia32
npm error notsup Actual cpu: arm64

npm error A complete log of this run can be found in: /Users/andres.vettori/.npm/_logs/2024-06-26T21_03_02_810Z-debug-0.log

I have confirmed the process has "Intel" as type looking in Activity Monitor.
