### ISSUE TITLE
Can not install BF CLI 

### ISSUE THREAD

**Issue by JorinZhu** [microsoft/botframework-cli#1323]
Hello, when i install BF CLI by command 'npm install -g @microsoft/botframework-cli' and stopped when "node-pre-gyp install" :

so i tried to rebuild the cli by command 'node-gyp rebuild',the error message is below:
![image](https://user-images.githubusercontent.com/20517079/143162342-45ffc696-d4f4-47df-9835-ebb14f82382c.png)

then i tried install again by command  'npm install -g @microsoft/botframework-cli' and it returns success;

but i tried the bf command 'bf orchestrator:basemodel:list',the error message returns:
![image](https://user-images.githubusercontent.com/20517079/143161774-95aade8f-6113-4175-97d9-efa37764bcb5.png)

So could you give me some advice to solve this problem? Thanks a lot.

Command: 
npm install -g @microsoft/botframework-cli
node-gyp rebuild
bf orchestrator:basemodel:list

OS: 
Win10 PowerShell

**Comment by mrivera-ms** [comment]
@munozemilio, can you please take a look at this issue?

**Comment by munozemilio** [comment]
Hello @tsuwandy - could you assist with that Orchestrator error please?

**Comment by tsuwandy** [comment]
@JorinZhu, what's OS are you doing the install in?   I just tried and the install was finished successfully and I was able to use the bf orchestrator:basemodel:get command

**Comment by tsuwandy** [comment]
I see that you tried running the 'node-gyp rebuild' command?  You don't need to do it.   

Could you try these?

Command:
npm uninstall -g @microsoft/botframework-cli
npm install -g @microsoft/botframework-cli
bf orchestrator:basemodel:list

**Comment by JorinZhu** [comment]
@tsuwandy  hello, I have tried your solution but it was failed again,see the below info:
![image](https://user-images.githubusercontent.com/20517079/144815388-e73d2f1b-8914-45ce-9d73-1b457d57c3ac.png)

it was stopped when  excute the command "node-pre-gyp install " and i also use yarn to install it,but the result was failed too.

My OS is windows 10 and i installed the cli by PowerShell;
I guess maybe the "windows-build-tools" was not installed correctly.
Below is my node.js version and other configuration, please help me check it ,thanks a lot.

![image](https://user-images.githubusercontent.com/20517079/144816505-a11cc95b-53e3-4249-89df-88ff5b66f82b.png)

**Comment by JorinZhu** [comment]
@tsuwandy    Because i can not install the  @microsoft/botframework-cli successfully, i tried use the dispatch cli but the region is not invalid.
![image](https://user-images.githubusercontent.com/20517079/144817920-40c0aea4-4b6f-4f66-9f6e-96efc4340624.png)

**Comment by JorinZhu** [comment]
@tsuwandy Because i can not install the @microsoft/botframework-cli successfully, i tried use the dispatch cli but the region is not invalid. 
![image](https://user-images.githubusercontent.com/20517079/144818047-4922b108-beac-4e47-a8a3-d4e87818e94d.png)

**Comment by tsuwandy** [comment]
@daveta any ideas on why node-pre-gyp install would fail on Windows 10?

**Comment by daveta** [comment]
@JorinZhu : Is this 32-bit?  Can you on a regular command prompt send results for the following commands :
 `npm config list` 
 `npm install -g node-gyp@8.0.0 && npm install -g @mapbox/node-pre-gyp@1.0.3`

**Comment by JorinZhu** [comment]
@daveta  Hello, here is my npm configuration:
![image](https://user-images.githubusercontent.com/20517079/144949860-ca075d90-c325-4ab7-b7a8-aa126c0a7194.png)

and i did as you said, but it did not work:
![image](https://user-images.githubusercontent.com/20517079/144980992-90931c8f-cbe6-4ca9-9736-81caa6b422fe.png)

**Comment by fdundjer** [comment]
Similiar issue on my side except it's a MacOs
```
npm install -g @microsoft/botframework-cli

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@microsoft/bf-orchestrator-cli@4.15.0',
npm WARN EBADENGINE   required: { node: '^10.0.0 || ^12.0.0 || ^13.0.0 || ^14.0.0' },
npm WARN EBADENGINE   current: { node: 'v17.0.1', npm: '8.1.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@microsoft/bf-orchestrator@4.15.0',
npm WARN EBADENGINE   required: { node: '^10.0.0 || ^12.0.0 || ^13.0.0 || ^14.0.0' },
npm WARN EBADENGINE   current: { node: 'v17.0.1', npm: '8.1.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@microsoft/orchestrator-core@4.14.1',
npm WARN EBADENGINE   required: { node: '^10.0.0 || ^12.0.0 || ^13.0.0 || ^14.0.0 || ^16.0.0' },
npm WARN EBADENGINE   current: { node: 'v17.0.1', npm: '8.1.0' }
npm WARN EBADENGINE }
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/orchestrator-core
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install
npm ERR! response status 404 Not Found on https://bcmodelsprod.azureedge.net/native/orchestrator-core-v4.14.1-node-v102-darwin-x64.tar.gz
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.7
npm ERR! node-pre-gyp info using node@17.0.1 | darwin | x64
npm ERR! node-pre-gyp info check checked for "/usr/local/lib/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/orchestrator-core/orchestrator-core.node" (not found)
npm ERR! node-pre-gyp http GET https://bcmodelsprod.azureedge.net/native/orchestrator-core-v4.14.1-node-v102-darwin-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://bcmodelsprod.azureedge.net/native/orchestrator-core-v4.14.1-node-v102-darwin-x64.tar.gz 
npm ERR! node-pre-gyp ERR! install error 
npm ERR! node-pre-gyp ERR! stack Error: response status 404 Not Found on https://bcmodelsprod.azureedge.net/native/orchestrator-core-v4.14.1-node-v102-darwin-x64.tar.gz
npm ERR! node-pre-gyp ERR! stack     at /usr/local/lib/node_modules/@microsoft/botframework-cli/node_modules/@mapbox/node-pre-gyp/lib/install.js:67:15
npm ERR! node-pre-gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm ERR! node-pre-gyp ERR! System Darwin 21.1.0
npm ERR! node-pre-gyp ERR! command "/usr/local/Cellar/node/17.0.1/bin/node" "/usr/local/lib/node_modules/@microsoft/botframework-cli/node_modules/.bin/node-pre-gyp" "install"
npm ERR! node-pre-gyp ERR! cwd /usr/local/lib/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/orchestrator-core
npm ERR! node-pre-gyp ERR! node -v v17.0.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.7
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/filip/.npm/_logs/2021-12-09T12_39_17_236Z-debug.log
```

**Comment by JorinZhu** [comment]
Finally i create an virtual machine in Germany and install this cli successfully, i guess maybe the network cause the install issues in China.
