### ISSUE TITLE
Not able to run bf orchestrator:basemodel

### ISSUE THREAD

**Issue by aishwaryaumachandran** [microsoft/botframework-cli#1324]
I've been trying to set up the Orchestrator using the [sample](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/14.nlp-with-orchestrator) 

I have the correct node version and I also have the microsoft/botframework-cli installed. I get an error at the _**"bf orchestrator:basemodel:get --out ./model"** 

Error: Cannot find module '/usr/local/lib/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/orchestrator-core/orchestrator-core.node'. Please verify that the package.json has a valid "main" entry
    at Module.patchedRequire [as require] (/usr/local/lib/node_modules/@microsoft/botframework-cli/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at Object.<anonymous> (/usr/local/lib/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/bf-orchestrator/lib/labelresolver.js:14:12)

I'm running this on a Mac. Would appreciate any leads

**Comment by tsuwandy** [comment]
@aishwaryaumachandran, what is the version of @microsoft/botframework-cli installed?

>bf -v

Could you try this:
>npm uninstall -g @microsoft/botframework-cli
>npm install -g @microsoft/botframework-cli

Make sure this works:
>bf orchestrator

Should show:
Display Orchestrator CLI available commands

USAGE
  $ bf orchestrator

OPTIONS
  -h, --help  Orchestrator commands help

COMMANDS
  orchestrator:add          Add examples from .lu/.qna/.json/.blu files, LUIS app(s) and QnaMaker kb(s) to Orchestrator
                            snapshot file.
  orchestrator:basemodel    Gets Orchestrator base model
  orchestrator:build        Creates Orchestrator snapshot file and Orchestrator dialog definition file (optional) for
                            each lu file in input folder.
  orchestrator:create       Create orchestrator snapshot (.blu) file from .lu/.qna/.json/.tsv/.dispatch files, which
                            represent bot modules
  orchestrator:interactive  Real-time interaction with Orchestrator model and analysis. Can return score of given
                            utterance using previously created orchestrator examples
  orchestrator:query        Query Orchestrator base model and a snapshot/train file
  orchestrator:remove       Remove examples from LUIS app(s), QnaMaker kb(s) or .lu/.qna/.json files from Orchestrator
                            snapshot file.
  orchestrator:test         The "test" command can operate in three modes: test, evaluation, assessment.

**Comment by aishwaryaumachandran** [comment]
I have the 4.15 version of BF CLI. 

The steps you provided helped and I was successfully able to train all the models. Thank you!

**Comment by hanhsia** [comment]
I have the same issue in ubuntu 20.
I have followed you instruction to uninstall and install bf but still encounter the issue.
Here is the result:
bf -v
@microsoft/botframework-cli/4.15.0 linux-x64 node-v14.18.2
bf orchestrator
Display Orchestrator CLI available commands

bf orchestrator:basemodel:list
Error: Cannot find module '/usr/lib/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/orchestrator-core/orchestrator-core.node'. Please verify that the package.json has a valid "main" entry
    at Module.patchedRequire [as require] (/usr/lib/node_modules/@microsoft/botframework-cli/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at Object.<anonymous> (/usr/lib/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/bf-orchestrator/lib/labelresolver.js:14:12)

**Comment by aishwaryaumachandran** [comment]
The only difference is the node version in my case. Maybe try downgrading to node 4.17 and give it a shot

@microsoft/botframework-cli/4.15.0 darwin-x64 node-v14.17.1

**Comment by tsuwandy** [comment]
@hanhsia, @aishwaryaumachandran is correct.  Node v14.18 is not yet supported.  Please downgrade to node 4.17 and try uninstall and installing @microsoft/botframework-cli/ again.  Thanks.

**Comment by hanhsia** [comment]
eh, that's strange, because our document doesn't say v14.18 is not supported. and i also installed node v14.18 in windows and bf works well.
>bf -v
@microsoft/botframework-cli/4.15.0 win32-x64 node-v14.18.1
anyway, i will try your suggestion in Linux.

**Comment by hanhsia** [comment]
I also tested it using V14.17.4 in windows server 2016. but it still failed with following error:
node -v
v14.17.4
>bf orchestrator:basemodel:list
Error: The specified module could not be found.
//?/C:/Users/itsp/AppData/Roaming/npm/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/orchestrator-core/orchestrator-core.node
    at Module.patchedRequire [as require] (C:/Users/itsp/AppData/Roaming/npm/node_modules/@microsoft/botframework-cli/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at Object.<anonymous> (C:/Users/itsp/AppData/Roaming/npm/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/bf-orchestrator/lib/labelresolver.js:14:12)

**Comment by tsuwandy** [comment]
@hanhsia, did you install v14.17 node on the same machine as the v14.18?  or this is a new VM?  if in the same machine, did you uninstall and then re-install?
