### ISSUE TITLE
not able to run bf orchestrator:basemodel in ubuntu 20.04

### ISSUE THREAD

**Issue by hanhsia** [microsoft/botframework-cli#1326]
I have followed the instruction in #1324 to uninstall and install bf but still encounter the issue.
Here is the result:
bf -v
@microsoft/botframework-cli/4.15.0 linux-x64 node-v14.18.2
bf orchestrator
Display Orchestrator CLI available commands

bf orchestrator:basemodel:list
Error: Cannot find module '/usr/lib/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/orchestrator-core/orchestrator-core.node'. Please verify that the package.json has a valid "main" entry
    at Module.patchedRequire [as require] (/usr/lib/node_modules/@microsoft/botframework-cli/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at Object.<anonymous> (/usr/lib/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/bf-orchestrator/lib/labelresolver.js:14:12)

_Originally posted by @hanhsia in https://github.com/microsoft/botframework-cli/issues/1324#issuecomment-1002859298_

**Comment by hanhsia** [comment]
I also tested it using V14.17.4 in windows server 2016. but it still failed with following error:
node -v
v14.17.4
>bf orchestrator:basemodel:list
Error: The specified module could not be found.
//?/C:/Users/itsp/AppData/Roaming/npm/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/orchestrator-core/orchestrator-core.node
    at Module.patchedRequire [as require] (C:/Users/itsp/AppData/Roaming/npm/node_modules/@microsoft/botframework-cli/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at Object.<anonymous> (C:/Users/itsp/AppData/Roaming/npm/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/bf-orchestrator/lib/labelresolver.js:14:12)

**Comment by tsuwandy** [comment]
@hanhsia, is the Ubuntu run in VM or Azure?

**Comment by Lrony** [comment]
@tsuwandy Hi, I also found this problem on Ubuntu 20.04.2 LTS
`
username@username:~$ bf -v
@microsoft/botframework-cli/4.15.0 linux-x64 node-v14.17.0
pengyang@pengyang:~$ bf orchestrator
Display Orchestrator CLI available commands

USAGE
  $ bf orchestrator

OPTIONS
  -h, --help  Orchestrator commands help

COMMANDS
  orchestrator:add          Add examples from .lu/.qna/.json/.blu files, LUIS app(s) and QnaMaker kb(s) to Orchestrator snapshot file.
  orchestrator:basemodel    Gets Orchestrator base model
  orchestrator:build        Creates Orchestrator snapshot file and Orchestrator dialog definition file (optional) for each lu file in input folder.
  orchestrator:create       Create orchestrator snapshot (.blu) file from .lu/.qna/.json/.tsv/.dispatch files, which represent bot modules
  orchestrator:interactive  Real-time interaction with Orchestrator model and analysis. Can return score of given utterance using previously created orchestrator examples
  orchestrator:query        Query Orchestrator base model and a snapshot/train file
  orchestrator:remove       Remove examples from LUIS app(s), QnaMaker kb(s) or .lu/.qna/.json files from Orchestrator snapshot file.
  orchestrator:test         The "test" command can operate in three modes: test, evaluation, assessment.

username@username:~$ bf orchestrator:create
Error: Cannot find module '/usr/local/lib/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/orchestrator-core/orchestrator-core.node'. Please verify that the package.json has a valid "main" entry
    at Module.patchedRequire [as require] (/usr/local/lib/node_modules/@microsoft/botframework-cli/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at Object.<anonymous> (/usr/local/lib/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/bf-orchestrator/lib/labelresolver.js:14:12)
`

**Comment by hanhsia** [comment]
> @hanhsia, is the Ubuntu run in VM or Azure?

runs in Azure. 
In windows, it's due to lack of  VC++ runtime 14.0. Is there similar thing in Linux?

**Comment by ChiragM-Hexaware** [comment]
Showing same error on Redhat Linux. Can anyone tell how to resolve???

**Comment by jrpavoncello** [comment]
Also experiencing this, but using a node 14.0 alpine image. Runs fine on windows.
