### ISSUE TITLE
Orchestrator - QnA Maker Alterations support

### ISSUE THREAD

**Issue by AndreaLeonangeli** [microsoft/botframework-cli#1336]
### **Is your feature request related to a problem? Please describe.**

I'm currently exploring **QnA Maker Alterations** and the ability of the Bot Framework Orchestrator to handle them. 
With a .qna QnA Maker knowledge Base file definition and a separate .json/.qna (downloaded and converted with the appropriate bf-cli commands) file of QnA Maker Alterations, the command to create an orchestrator .blu file does not seem to take into account the QnA maker Alterations. 

The consequence is that a given query that uses an alteration may result with a high confidence score when QnA Maker receives it but  QnA Maker will never receive the query if the Orchestrator does know nothing about Alterations, giving a low score in the "orchestration layer".

### **Describe the solution you'd like**

The command **bf orchestrator:create** takes into account QnA Maker Alterations feature in a given .qna or .json file and the Orchestrator is able to address a user query that contains an alteration to QnA Maker.

**Comment by jrpavoncello** [comment]
+1 This was a feature of the old **dispatch-cli** tool that we relied on heavily. Is there a workaround for the time being?

**Comment by ChandraChinta** [comment]
After installing botframework cli on latest node,  Orchestrator commands not working.  Is Orchestrator production ready?  Is there any updated documentation step by step guide to configure bf orchestrator ?  Is it recommended to use it on production or not?

**Comment by tracyboehrer** [comment]
As QnA is on a deprecation path, no new QnA features will be added.
