### ISSUE TITLE
Run OSS Compliance build pass

### ISSUE THREAD

**Issue by scheyal** [microsoft/botframework-cli#134]
See Task [36858](https://fuselabs.visualstudio.com/Bot%20Builder%20Tools/_workitems/edit/36858)
In particular follow this [video](https://microsoft.sharepoint.com/teams/DD_VSCS/Enterprise%20Social/Documents/Forms/AllItems.aspx?sortField=Modified&isAscending=false&id=%2Fteams%2FDD_VSCS%2FEnterprise%20Social%2FDocuments%2FCode%20Sharing%2FSpecs%2FComponent%20Governance%2FSprint%20mails%2FCG%20onboarding%20demo%2Emp4&parent=%2Fteams%2FDD_VSCS%2FEnterprise%20Social%2FDocuments%2FCode%20Sharing%2FSpecs%2FComponent%20Governance%2FSprint%20mails
)

**Comment by munozemilio** [comment]
Added to the build and task succeeded: https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=80436
