### ISSUE TITLE
Add support for Question Answering like with QnA Maker

### ISSUE THREAD

**Issue by jrpavoncello** [microsoft/botframework-cli#1340]
These CLI tools don't seem to have support for Azure's new Question Answering service [like it does for QnA Maker](https://github.com/microsoft/botframework-cli/blob/main/packages/qnamaker/README.md) - i.e. things that build automation might do like adding/updating/removing/training/publishing/exporting knowledge bases, and replacing the alterations list.

**Describe the solution you'd like**
Add an equivalent CLI like what is done for [QnA Maker](https://github.com/microsoft/botframework-cli/blob/main/packages/qnamaker/README.md)

**Describe alternatives you've considered**
We could migrate our CI/CD pipelines over to use the REST API for Question Answering, though this would increase the scope a bit of our migration. According to the QnA Maker documentation they will stop allowing new services as of October of **this year** which puts our production environment at risk if we ever need to spin up new resources, so we are trying to get migrated as quickly as possible.

Related to  [#6413](https://github.com/microsoft/botframework-sdk/issues/6413) and #1339 

[enhancement]

**Comment by birla** [comment]
MSFT has completely deprecated QnA maker and customers want to migrate to the new service. Seems like we need to stop using this toolkit as Luis is also on the way to depreciation.

**Comment by jrpavoncello** [comment]
We converted to using the REST api fully due to this. One of many things that was support was silently dropped for when they switched to orchestrator and language services

**Comment by tracyboehrer** [comment]
As QnA is on a deprecation path, no new QnA feature will be added.
