### ISSUE TITLE
BF-CLI : QNA-KB Export Issue

### ISSUE THREAD

**Issue by rcs-phamax** [microsoft/botframework-cli#1341]
## Versions
CLI version : 4.15.0 win32-x64
Nodejs version : 14.15.0
command-line interpreters : Windows Power Shell
OS : Windows 10

## Describe the bug
Trying to run the BF-CLI command to export the QnA-Maker KB which throws an Unknown isuue.

Command : 
bf qnamaker:kb:export --endpoint <endPoint> --kbId <ID> --subscriptionKey <sub-key> --environment prod --qnaFormat > qna_export.qna 
OR
bf qnamaker:kb:export --endpoint <endPoint> --kbId <ID> --subscriptionKey <sub-key> --environment prod > qna_export.json
 
## To Reproduce
1. Install BF -CLi; Get QnA-Maker endpoint and ID's
2. Run the command after adding all config values

## Expected behavior
The Command is supposed to connect to the atrget QnA-Maker Knowledge Base and export the KB in either JSON or QNA format to STDOUT.
Instead command is throwing an "Unknown Issue" instantly

## Screenshots
![BF-CLi-qnaExport_issue](https://user-images.githubusercontent.com/96542950/168010362-42a7f367-9aed-4442-96a1-f671c16ad0ee.png)

## Additional context
Here's the issue response on running the command :
    Unknown error during execution. Please file an issue on https://github.com/microsoft/botframework-cli/issues
    Converting circular structure to JSON
        --> starting at object with constructor 'Socket'
        |     property '_httpMessage' -> object with constructor 'ClientRequest'
        --- property 'socket' closes the circle

Here's the Documentation I followed : https://www.npmjs.com/package/@microsoft/botframework-cli#bf-qnamakerkbexport
[bug]

**Comment by ramfattah** [comment]
Hi @rcs-phamax 

Update: I was able to reproduce this issue. 
![image](https://user-images.githubusercontent.com/38049078/168316132-965e2727-de56-4d69-a29f-f976d2147745.png)

I get the same error message in the issue:
```ps
Unknown error during execution. Please file an issue on https://github.com/microsoft/botframework-cli/issues
Converting circular structure to JSON
    --> starting at object with constructor 'Socket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
```

**Comment by ryanlengel** [comment]
@munozemilio can you investigate this one?

**Comment by munozemilio** [comment]
Hello @rcs-phamax could you please try with NO endpoint flag:
```
bf qnamaker:kb:export --kbId --subscriptionKey --environment prod --qnaFormat > qna_export.qna
OR
bf qnamaker:kb:export --kbId --subscriptionKey --environment prod > qna_export.json
```

**Comment by ramfattah** [comment]
@rcs-phamax, any updates?

Thanks to @munozemilio's suggestion, I was able to run `bf qnamaker:kb:export` without issues.

**Comment by rcs-phamax** [comment]
Hi @ramfattah , thank you for the help, but @munozemilio 's approach was actually my initial approach which kept throwing me a 401 error, only after which I started explicitly providing the endpoint, below is the screengrab of the error I get:

![qnaMakerExportIssue401](https://user-images.githubusercontent.com/96542950/169945063-fd167d40-7afa-49dd-96e3-8075ab6d0f03.png)

Please note that the same KB-ID and sub-key works fine and is currently in use with multiple bots so there's no doubt regarding the key as the error points.

**Comment by ramfattah** [comment]
Hi @rcs-phamax, thanks for the update; what endpoint are you providing?

**Comment by rcs-phamax** [comment]
Hi @ramfattah I've tried with following as endpoints, yeilding same result of 401 error,
1. name-of-my-qna-svc.azurewebsites.net
2. https://name-of-my-qna-svc.azurewebsites.net
3.  https://name-of-my-qna-svc.azurewebsites.net/qnamaker
Please correct me in case I'm giving the wrong endpoint. Thank you.

**Comment by munozemilio** [comment]
Hello @rcs-phamax, thanks so much for the quick reply. Let me provide a bit of context. The qna maker commands are a wrapper of the qna maker v4.0 api...[Here](https://westus.dev.cognitive.microsoft.com/docs/services/5a93fcf85b4ccd136866eb37/operations/knowledgebases_getknowledgebasedetails/console) you can find a testing console where you can try the parameters directly. Its weird that your resource is not found by the default endpoint. The endpoint you commented above is only for the generate answer operation. The one you have to use for the export operation should look something like this:
```
https://resource-name.cognitiveservices.azure.com/qnamaker/v4.0/
```
Where _resource name_ can be found in the Azure Portal.

Let me know if that helps

**Comment by rcs-phamax** [comment]
Thank you so much @munozemilio , this was of great help. Even though the original issue remains, I've got the info required to get .qna file. So this is wrap from my side here.
Also to those who might face a similar issue, quickest option is to have a simple py-script to convert CSV export of QnA-KB to .qna or JSON format.
