### ISSUE TITLE
BF luis build: datetimeV2 is not available for the requested locale: it-it

### ISSUE THREAD

**Issue by Erry91** [microsoft/botframework-cli#1347]
## Versions
What CLI version are you using: 4.15.0
What Nodejs version are you using: 14.x
What OS are you using: Ubuntu

## Describe the bug
I have a .lu file definition which defines the datetimeV2 prebuilt entity. When I want to use that pre-built entity in an intent (with the notation "@ intent usesFeatures feature1,feature2,datetimeV2") the bf luis build command fails saying that:

- the datetimeV2 entity is not supported for locale it-it, which is not true according to the docs [https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-reference-prebuilt-entities#italian-entity-support](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-reference-prebuilt-entities#italian-entity-support)
- it tries to switch to datetime instead and complains that it's not defined (rightfully). I cannot define it though even if I try to change datetimeV2 to datetime in my .lu file

## To Reproduce
1. have .lu file as it-it as locale
2. define prebuild entity datetimeV2
3. use the entity as a feature in an intent
4. compile with bf luis build

## Expected behavior
I expected the bf luis build command to work smoothly with no errors. More importantly, I would expect the datetimeV2 feature to be supported as it appears from the documentation.

## Screenshots
![image](https://user-images.githubusercontent.com/6703817/174625313-2553cfdc-ef92-4795-a924-3f2b37cebaaf.png)

**Comment by anishprasad01** [comment]
Hi @Erry91,

I'd be happy to take a look at this issue. Could you please provide me with a minimal copy of an `.lu` file that you are using to attempt the `bf luis build` process so that I may test it with a file that reflects your implementation?

**Comment by Erry91** [comment]
Hi @anishprasad01 and thank you for your reply.
This should be a minimal copy of a .lu file that presents that behaviour. Let me know if this occurs for you too or if you need some more info. 
The locale for this is it-it.
The file .txt (as you can imagine for github attachment restrictions) has to be renamed .lu, but apart from that it should contain a minimal example.

[luExmple.it-it.txt](https://github.com/microsoft/botframework-cli/files/8965329/luExmple.it-it.txt)

**Comment by anishprasad01** [comment]
So, I was able to get this to run and return back the completed operation JSON, but I had to define a `phraseList` for `Application_feature` as well as supply the prebuilt entity definitions:

```
> # PREBUILT Entity definitions

@ prebuilt datetimeV2
@ prebuilt email
```
I also needed to supply metadata in the file like this:
```
> !# @app.name = APIT-ITTest
> !# @app.culture = it-it
> !# @app.versionId = 0.1
```
Does your full implementation do this? If not, perhaps adding these items will fix it. Otherwise, something else in your full `.lu` file may be at fault.

**Comment by Erry91** [comment]
Sorry for the missing information, I accidentally cut them out as I was trying to re-create a minimal example. I apologize for this.
However, my .lu files **DO** have the prebuilt entities, but I still get that warning about the use of datetimeV2 not supported. And the locale is actually being referred to correctly (as it complains that is not supported for it-it). 
The actual .lu files do not have the metadata included, as I am using Bot Framework Composer that generates them as I design the bot Luis model (from inside Composer). But the locale as I understand it is being inferred by both the name/folder of where the language generation file is placed. 

The complete command that generates this warning is the following:
`bf luis:build --in $PWD --authoringKey $(eval $LUIS_AUTHORING_KEY) --botName $(eval $BOT_NAME_HANDLE) --out ./generated --region "westeurope" --suffix composer --force --log --defaultCulture=it-it`

@anishprasad01 are you saying that your bf luis:build didn't throw any error in console about datetimeV2?

**Comment by Erry91** [comment]
I just did another quick test with the minimal example and the command I am trying to run above, and it fails with the problem I mentioned at the top. 

![luisErrorDatetimev2](https://user-images.githubusercontent.com/6703817/175354189-6825b3f5-4884-4173-b759-5e86574cd4c1.png)

@anishprasad01 doesn't this happen for you too? I don't understand where the error might be.

**Comment by anishprasad01** [comment]
No, I don't encounter this error. However, my file is not named `<filename>.it-it.lu`, but rather just `<filename>.lu`, in keeping with all samples of this format that I have seen. In my testing thus far, varying the extensions can cause issues. I'm thinking this might be it.

**Comment by Erry91** [comment]
Even without the extension there is no difference for me, still the same error. Can it be the region? Any of the arguments can cause trouble in the bf luis:build function? For example I need to use --force and --out
Can it be that you have a different node.js version and that is causing problems for me?

**Comment by anishprasad01** [comment]
I was able to reproduce using the `--defaultCulture` flag. Now that I have the repro, I can investigate further.

**Comment by Erry91** [comment]
Any sort of update on this topic?

**Comment by anishprasad01** [comment]
Not yet, however it is still on our radar. I will attempt to get some traction on this issue.

**Comment by munozemilio** [comment]
Hello @Erry91, I found the issue is when the content is converted to LU object in the LU parser process. I will try to get you a build in the following days. Sorry for the inconvenience and thank you for your patience.

**Comment by munozemilio** [comment]
Hello @Erry91 could you please try using:
```
npm i -g @microsoft/botframework-cli@next
```

That build has datetimeV2 enabled for Italian.

Let me know if that works for you
