### ISSUE TITLE
bf orchestrator:create getting failed while processing CLU (Conversational language understanding) Json file

### ISSUE THREAD

**Issue by Vijayalakshmi-R1** [microsoft/botframework-cli#1355]
Hi Team,

While trying to create snapshot file using .tsv (Question Answering) & .json file (CLU), it gets failed while processing Json file. 
I have **migrated the project from LUIS to CLU** and exported the project (.json file) from CLU to create a snapshot but it gets failed while processing this json file whereas I am able to create a snapshot file using json file exported from LUIS App.

Command executed- bf orchestrator:create --hierarchical --in ./CognitiveModels --out ./generated --model ./model

Please find the error details below.

**While using the project exported from LUIS**
Processing C:\Users\Vijayalakshmi.R\Desktop\Orchestrator\NPE\CognitiveModels\FINANCEKB.tsv...
Processing C:\Users\Vijayalakshmi.R\Desktop\Orchestrator\NPE\CognitiveModels\GeneralKB.tsv...
Processing C:\Users\Vijayalakshmi.R\Desktop\Orchestrator\NPE\CognitiveModels\HRKB.tsv...
Processing C:\Users\Vijayalakshmi.R\Desktop\Orchestrator\NPE\CognitiveModels\Master.json...
Processing C:\Users\Vijayalakshmi.R\Desktop\Orchestrator\NPE\CognitiveModels\STPKB.tsv...
Snapshot written to C:\Users\Vijayalakshmi.R\Desktop\Orchestrator\NPE\generated\orchestrator.blu

**While using the same project exported from CLU**
Processing C:\Users\Vijayalakshmi.R\Desktop\Orchestrator\NPE\CognitiveModels\FINANCEKB.tsv...
Processing C:\Users\Vijayalakshmi.R\Desktop\Orchestrator\NPE\CognitiveModels\GeneralKB.tsv...
Processing C:\Users\Vijayalakshmi.R\Desktop\Orchestrator\NPE\CognitiveModels\HRKB.tsv...
Processing C:\Users\Vijayalakshmi.R\Desktop\Orchestrator\NPE\CognitiveModels\Master.json...
Failed to parse LUIS or JSON file on intent/entity labels
Failed to parse C:\Users\Vijayalakshmi.R\Desktop\Orchestrator\NPE\CognitiveModels\Master.json, error=
{}

Please find the Json files below.
CLU- 
[Master.txt](https://github.com/microsoft/botframework-cli/files/10257458/Master.txt)

LUIS- 
[Master.txt](https://github.com/microsoft/botframework-cli/files/10257454/Master.txt)

I see differences in schema between both json files. 
Is there any update in the orchestrator model to generate snapshot for CLU projects?

Thanks in advance.

**Comment by johnataylor** [comment]
@munozemilio any update on this?

**Comment by munozemilio** [comment]
Hello @Vijayalakshmi-R1 ... at the moment there is no support for CLU projects.
