### ISSUE TITLE
Unable to install botframework-cli with Node 18x

### ISSUE THREAD

**Issue by kasivn** [microsoft/botframework-cli#1357]
# Versions
What CLI version are you using. >> 4.15.0
What Nodejs version are you using >> 18.14.0
What command-line interpreters are you using >> Powershell
What OS are you using >> Windows

# Describe the bug
I am not able to execute npm i -g @microsoft/botframework-cli

Getting below error.
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@microsoft/bf-orchestrator-cli@4.15.0',
npm WARN EBADENGINE   required: { node: '^10.0.0 || ^12.0.0 || ^13.0.0 || ^14.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.14.0', npm: '9.4.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@microsoft/bf-orchestrator@4.15.0',
npm WARN EBADENGINE   required: { node: '^10.0.0 || ^12.0.0 || ^13.0.0 || ^14.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.14.0', npm: '9.4.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@microsoft/orchestrator-core@4.14.4',
npm WARN EBADENGINE   required: { node: '^10.0.0 || ^12.0.0 || ^13.0.0 || ^14.0.0 || ^16.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.14.0', npm: '9.4.1' }
npm WARN EBADENGINE }
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated cli-ux@4.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated cli-ux@5.3.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated cli-ux@5.6.7: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\<USER>\\AppData\\Roaming\\npm\\node_modules\\@microsoft\\botframework-cli\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\<USER>\AppData\Roaming\npm\node_modules\@microsoft\botframework-cli\node_modules\botbuilder-lg'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\<USER>\\AppData\\Roaming\\npm\\node_modules\\@microsoft\\botframework-cli\\node_modules\\botbuilder-lg'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\<USER>\\AppData\\Roaming\\npm\\node_modules\\@microsoft\\botframework-cli',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\<USER>\AppData\Roaming\npm\node_modules\@microsoft\botframework-cli\node_modules\botbuilder-lg'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\<USER>\\AppData\\Roaming\\npm\\node_modules\\@microsoft\\botframework-cli\\node_modules\\botbuilder-lg'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\<USER>\\AppData\\Roaming\\npm\\node_modules\\@microsoft\\botframework-cli\\node_modules\\@azure',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\<USER>\AppData\Roaming\npm\node_modules\@microsoft\botframework-cli\node_modules\@azure\ms-rest-js\es'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\<USER>\\AppData\\Roaming\\npm\\node_modules\\@microsoft\\botframework-cli\\node_modules\\@azure\\ms-rest-js\\es'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\<USER>\\AppData\\Roaming\\npm\\node_modules\\@microsoft\\botframework-cli\\node_modules\\@microsoft\\bf-dispatcher',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\<USER>\AppData\Roaming\npm\node_modules\@microsoft\botframework-cli\node_modules\@microsoft\bf-dispatcher\lib'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\<USER>\\AppData\\Roaming\\npm\\node_modules\\@microsoft\\botframework-cli\\node_modules\\@microsoft\\bf-dispatcher\\lib'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\<USER>\AppData\Roaming\npm\node_modules\@microsoft\botframework-cli\node_modules\@microsoft\orchestrator-core
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install
npm ERR! response status 404 Not Found on https://bcmodelsprod.azureedge.net/native/orchestrator-core-v4.14.4-node-v108-win32-x64.tar.gz
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@18.14.0 | win32 | x64
npm ERR! node-pre-gyp info check checked for "C:\Users\<USER>\AppData\Roaming\npm\node_modules\@microsoft\botframework-cli\node_modules\@microsoft\orchestrator-core\orchestrator-core.node" (not found)
npm ERR! node-pre-gyp http GET https://bcmodelsprod.azureedge.net/native/orchestrator-core-v4.14.4-node-v108-win32-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://bcmodelsprod.azureedge.net/native/orchestrator-core-v4.14.4-node-v108-win32-x64.tar.gz
npm ERR! node-pre-gyp ERR! install error
npm ERR! node-pre-gyp ERR! stack Error: response status 404 Not Found on https://bcmodelsprod.azureedge.net/native/orchestrator-core-v4.14.4-node-v108-win32-x64.tar.gz
npm ERR! node-pre-gyp ERR! stack     at C:\Users\<USER>\AppData\Roaming\npm\node_modules\@microsoft\botframework-cli\node_modules\@mapbox\node-pre-gyp\lib\install.js:67:15
npm ERR! node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19045
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\<USER>\\AppData\\Roaming\\npm\\node_modules\\@microsoft\\botframework-cli\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install"
npm ERR! node-pre-gyp ERR! cwd C:\Users\<USER>\AppData\Roaming\npm\node_modules\@microsoft\botframework-cli\node_modules\@microsoft\orchestrator-core
npm ERR! node-pre-gyp ERR! node -v v18.14.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<USER>\AppData\Local\npm-cache\_logs\2023-02-05T06_58_27_757Z-debug-0.log

# To Reproduce

Go to PowerShell 
execute npm install -g @microsoft/botframework-cli
See error

# Expected behavior
All BotFramework CLI dependencies should have install successfully.

**Comment by stevkan** [comment]
@kasivn, please note that in the installation instructions in the readme file states that only Node v14 is supported.

![image](https://user-images.githubusercontent.com/18403946/217061380-f33dca81-08df-413c-b7c1-9077ee51a87e.png)
