### ISSUE TITLE
Ludown should build valid subcommand to ensure the model output by parse toluis can be loaded by LUIS portal

### ISSUE THREAD

**Issue by daden-ms** [microsoft/botframework-cli#150]
## Tool
Name:  Ludown

## Describe the problem
I have experience a model that's converted from lu file to json format which cannot be loaded by LUIS portal

## Describe the solution you'd like
a validity sub-command that can tell if the lu file/json file can be loaded as a valid LUIS app or not.  

## Describe alternatives you've considered
NA

## Additional context
NA

[enhancement]

**Comment by vishwacsena** [comment]
@daden-ms - we constantly add validations to ensure the output of the tool is valid .json file however not all validations done by the LUIS service are available in the tool. That said, are you able to share a specific .lu file or mock .lu content that could not be loaded by this LUIS portal? That will help me add additional validations that might be missing.

**Comment by daden-ms** [comment]
This happens in the past due to prebuilt domains as some prebuilt domains are no longer supported in LUIS.

**Comment by vishwacsena** [comment]
@daden-ms: We have invested in this area by adding support for prebuilt domains in LU file format via microsoft/botbuilder-tools#1257. 

The latest version of the BF CLI is available via the nightly feed here - https://botbuilder.myget.org/feed/botframework-cli/package/npm/@microsoft/bf-luis

This will be published to npm next month. 

Please reactivate should you continue to see issues with the latest BF CLI either by installing from the nightly feed or via npm (once available).
