### ISSUE TITLE
Seeing Γö¼├í in .lu file while exporting QnA from Remote

### ISSUE THREAD

**Issue by SreekanthOAuth** [microsoft/botframework-cli#162]
## qnamaker
Name: QnAMaker
Version: *1.3.1*
OS: *Windows 10*

## Describe the bug

Not sure why these are coming. Are these are replacing any char or symbols? 
When we try to export the QnA from remote to local seeing Γö¼├í in .lu file.
qnamaker export kb `
                --environment Prod `
                --kbId $kb.kbId `
                --subscriptionKey $kb.subscriptionKey | ludown refresh `
                --stdin `
                -n "$($kb.name).lu" `
                -o $(Join-Path $qnaFolder $langCode)

## To Reproduce
1. Create KB Model
2. Add some QnAs to it.
3. Export it by using qnamaker export command.
4. Now check the .lu file.

## Expected behavior
Expecting file shouldn't be having these characters. Because we are updating the same file and importing to the KB model.

## Screenshots
![qna lufile](https://user-images.githubusercontent.com/24246902/65572733-9cc0bf00-df86-11e9-8d5b-f0d75783dbce.jpg)

[bug]

**Comment by vishwacsena** [comment]
Related to #157 - for both these it would be great if we verify the issue and have the customer confirm if they continue to repro with the latest bf cli off the nightly feed.

**Comment by munozemilio** [comment]
We will investigate and find the issue soon. This fix should be part of the new bf cli tool

**Comment by munozemilio** [comment]
hello @SreekanthOAuth, I'm unable to reproduce your issue either in latest ludown or new bf cli.
Could you please share more details on the character that should be displayed? Also, is it displayed in the QnA Maker [portal](https://www.qnamaker.ai)?

**Comment by stevengum** [comment]
@sreekanthOAuth, are you still running into this issue?

**Comment by stevengum** [comment]
@sreekanthOAuth, I'm going to close this issue due to inactivity. If you're still running into this issue please ping us or open a new issue.

**Comment by SreekanthOAuth** [comment]
@stevengum - Sorry for the inactivity. Reopening this issue since seeing special characters even after updating Ludown. 

Now seeing different character and it's **┬á**.

Could you please help us on this.

Thanks,
Sreekanth
