### ISSUE TITLE
Export parseAllFiles function as a pure function

### ISSUE THREAD

**Issue by Danieladu** [microsoft/botframework-cli#180]
As I want to parse a .lu file to get the whole lu info like `LUISContent`, `QnAContent` and `QnAAlterations`. 

But `parseFileContents.js` just return the parsed structure `parsedContent` which includes `additionalFilesToParse` property. 

Then I found `parse.js` contains what I want , because in this file, `parseAllFiles` provides all the final items. 
But this function is not exported.

**Comment by vishwacsena** [comment]
What you are looking for is this - 

parseLuList: require('./converters/lutoluisconverter').parseLuToLuis

We should vet this in the composer branch and include it in public APIs once we have it vetted.
