### ISSUE TITLE
Foundation: Compliance Requirements.

### ISSUE THREAD

**Issue by scheyal** [microsoft/botframework-cli#19]
[+PM]

Details tracked in VSO issues due to compliance needs.

**Comment by scheyal** [comment]
Just a status note: In discussions with security/privacy we agreed that as long as we're careful to not collect any PII we should wait until the tool has a bit more beef in it as it doesn't make sense to review a tool that's only 10-20% done.,

Once we settle on 4.6 CLI deliverables (soon), we'll re-assess when we get a full compliance pass.

**Comment by scheyal** [comment]
In progress. Working on it, and tragetting completion and/or approval by 10/25

**Comment by scheyal** [comment]
Blocked on response regarding globalization/localization acceptance.

**Comment by scheyal** [comment]
Talked to Scott & Yochay. We will be English only for this release.

**Comment by scheyal** [comment]
Waiting for a few final items. We're pretty much good to go.

**Comment by sgellock** [comment]
@scheyal what's the status of closing this? we're done, no?

**Comment by scheyal** [comment]
Done.
