### ISSUE TITLE
Ensure all commands return completion status - No silent return from execution.

### ISSUE THREAD

**Issue by scheyal** [microsoft/botframework-cli#191]
I filed an earlier bug around telemetry silent return. QnAMaker found another instance. We need to scrub all CLI commands and ensure all commands return a value to console:
1. Error message: In case of execution error
2. Usage+Failure: In case of wrong command line invocation. Identify missing / wrong param and print out relevant usage. 
3. Success: Return execution results. If retrun is true (20*, OK), return success message.

There should be no silent returns as they lead to user confusion. 

#### QnAMaker review comments:
1.	Can we add an error to the commands when the required parameter is absent? Right now it just silently exits.
2.	I know we show any response from the API calls, but it would be good to explicitly add a “Success” response when there is a 2xx HTTP response from the API. Sometimes it is hard to make out what happened when a command completes.

**Comment by munozemilio** [comment]
Fixed
