### ISSUE TITLE
Review new tool announcement in all legacy tool references

### ISSUE THREAD

**Issue by scheyal** [microsoft/botframework-cli#201]
Please review and suggest changes. If agree, please note so. Once approved we will propagate to all areas referencing the old tools.

## The new BF CLI replaces legacy standalone tools

The Bot Framework SDK team is happy to announce the release for General Availability of the consolidated bot management Command Line Interface: [BF](https://aka.ms/bfcli). The new BF CLI tool will replace legacy standalone tools to manage Bot Framework bots and related services. The old tools will be ported over in phases and all new features, bug fixes, and further investments will focus on the new BF CLI.  Old tools will still work for the time being, but they are going to be deprecated in future releases.

Upon the release of Bot Framework SDK version 4.6 the following legacy tools have been ported: Chatdown, QnAMaker, and LuDown.

To learn more about the BF CLI please visit the following github repository: https://aka.ms/bfcli

**Comment by scheyal** [comment]
Please review, suggest changes or agree here. Thanks.

**Comment by cleemullins** [comment]
> "The Bot Framework SDK team is happy to announce the release for General Availability of the consolidated bot management Command Line Interface"

How about:
The Bot Framework SDK team is happy to announce the General Availability of the consolidated bot framework CLI tool [bf-cli](https://github.com/Microsoft/BotFramework-cli). 


> "The old tools will be ported over" 

We're done with that, so far as I know. We have parity for everything except dispatch. 

> "Old tools will still work for the time being, but they are going to be deprecated in future releases"

Is there a crisper / clearer message we can send?

**Comment by scheyal** [comment]
New Version (with Chris's comments). Also:
* Old tools such as Luis API, LuisGen aren't there yet afaik
* We will update precise deprecation timeline (and what it means) after 4.6 adoption insights

---
The Bot Framework SDK team is happy to announce the General Availability of the consolidated bot framework CLI tool [bf-cli](https://aka.ms/bfcli). The new BF CLI tool will replace legacy standalone tools to manage Bot Framework bots and related services. The old tools will be ported over in phases and all new features, bug fixes, and further investments will focus on the new BF CLI.  Old tools will still work for the time being, but they are going to be deprecated in future releases.

Upon the release of Bot Framework SDK version 4.6 the following legacy tools have been ported: Chatdown, QnAMaker, and LuDown.

To learn more about the BF CLI please visit the following github repository: https://aka.ms/bfcli

**Comment by scheyal** [comment]
Forgot to add LuisGen....

---
## The new BF CLI replaces legacy standalone tools
The Bot Framework SDK team is happy to announce the General Availability of the consolidated bot framework CLI tool [bf-cli](https://aka.ms/bfcli). The new BF CLI tool will replace legacy standalone tools to manage Bot Framework bots and related services. The old tools will be ported over in phases and all new features, bug fixes, and further investments will focus on the new BF CLI. Old tools will still work for the time being, but they are going to be deprecated in future releases.
Upon the release of Bot Framework SDK version 4.6 the following legacy tools have been ported: Chatdown, QnAMaker, LuisGen, and LuDown.
To learn more about the BF CLI please visit the following github repository: https://aka.ms/bfcli

**Comment by christopheranderson** [comment]
Added a suggestion in the Sample repo change. Adding it here as well:

---
## The new BF CLI replaces legacy standalone tools
The Bot Framework SDK team is happy to announce the General Availability of the consolidated bot framework CLI tool [bf-cli](https://aka.ms/bfcli). The new BF CLI tool will replace legacy standalone tools to manage Bot Framework bots and related services. The old tools will be ported over in phases and all new features, bug fixes, and further investments will focus on the new BF CLI. Old tools will still work for the time being, but they are going to be deprecated in future releases.
Upon the release of Bot Framework SDK version 4.6 the following legacy tools have been ported: Chatdown, QnAMaker, LuisGen, and LuDown.
To learn more about the BF CLI please visit the [BF CLI github repository](https://aka.ms/bfcli).

**Comment by scheyal** [comment]
Done.
