### ISSUE TITLE
[hackathon] [DCR] add option to import/export config via file

### ISSUE THREAD

**Issue by dmvtech** [microsoft/botframework-cli#229]
After setting up configuration, it would be nice to have switches/commands to export and import (more importantly) configurations. My assumption is that there is a .json file that does contain the config, but this would be more user friendly.

Something like:
`bf config:set --configuration myconfig.json`

Export is somewhat easy in most shells:
`PowerShell:> bf config:show | out-file -myconfig.json`

But we might want to add an explicit export for ease:
`bf config:show --exportconfig=C:\myconfig.json`

or 

`bf config:export`

**Comment by scheyal** [comment]
Will add file location on usage instead.
