### ISSUE TITLE
[qnamaker] Errors with .lu file should provide a line number

### ISSUE THREAD

**Issue by christopheranderson** [microsoft/botframework-cli#235]
## Problem:

When trying to convert a .lu file which has an error in it, the error message doesn't have a line number which means I have to try to guess where the error is  which can be arduous in a very large file.

For example: copy the content from [here](https://raw.githubusercontent.com/microsoft/botbuilder-tools/master/packages/Ludown/examples/all.lu) to a local file (all.lu) and then try to convert it. You'll get an error message like so:

```
[ERROR] Sorry unable to open [C:\w\scratch\cli-hackathon\none.lu]
```

In this case, the error is pretty clear, but I need to grep through my file to find where the none dependency is coming from.

## Desired solution:

A line number should be provided alongside any errors.

**Comment by vishwacsena** [comment]
This would require some house-keeping - additionalFilesToParse can be expanded to include parser context (current ID being parsed as well as line number, full text on that line etc) which then can be optionally exposed up to the delegate which can include that context when throwing an error in case the requested ID cannot be resolved.
