### ISSUE TITLE
Add synopsis when bf is invoked

### ISSUE THREAD

**Issue by scheyal** [microsoft/botframework-cli#238]
Text: 
Manages Bot Framework bots and related services: Use to process bot configuration files, and manage language understanding resources and services related to Bot Framework bot development.

For this:
$ bf

<<< ADD HERE >>>

VERSION
  @microsoft/botframework-cli/4.5.0-preview.84297 win32-x64 node-v10.15.3

USAGE
  $ bf [COMMAND]

COMMANDS
  chatdown  Converts chat dialog files in <filename>.chat format into transcript file. Writes corresponding
            <filename>.transcript for each .chat file
  config    The config plugin allows users to configure various settings within the cli.
  help      display help for bf
  luis      Convert, translate luis/lu files or generate source code
  plugins   list installed plugins
  qnamaker  Convert .lu file(s) to a QnA application JSON model or vice versa

manage Bot Framework bots and related services

**Comment by v-kydela** [comment]
I was considering making a new bug for this, but notice that [this README](https://github.com/microsoft/botframework-cli/blob/master/packages/cli/README.md#bf-) uses the `bf config` description for the root `bf` command. It should use its own description, but that doesn't seem to exist yet as reported by this bug.
