### ISSUE TITLE
README should provide a link to an overview of Bot Framework and how CLI fits in

### ISSUE THREAD

**Issue by BruceHaley** [microsoft/botframework-cli#240]
The readme: https://github.com/microsoft/botframework-cli/blob/master/README.md

The document the readme points to should 1) give a 20,000 foot overview of Bot Framework. 2) Link to a "Getting started" document for new users. 3) Review how the CLI tools fit in to the overall bot development process.

Something like this Tools Overview document would be a good start: https://github.com/Microsoft/botbuilder-tools/blob/master/tools-overview.md

**Comment by scheyal** [comment]
Done.
