### ISSUE TITLE
Need doc describing the environmental prerequisites that make each tool relevant

### ISSUE THREAD

**Issue by BruceHaley** [microsoft/botframework-cli#242]
For example, qnamaker: The readme now provides a link to the command line syntax. https://github.com/microsoft/botframework-cli/tree/master/packages/cli#bf-qnamaker 

Addressing what the tool does it says: "Convert .lu file(s) to a QnA application JSON model or vice versa". But there is no link to or explanation of what a .lu file is or what a QnA application JSON model is. 

In addition to explaining the above, it should link to or explain what bot development steps or setup steps must be completed before the qnamaker tool is useful.

This kind of documentation should be provided for each tool.

(I would assume that there is a document that tells a user how to create a bot. At various points that document would suggest using a CLI tool to solve a particular problem. The links I am suggesting here might "back-link" to that document. That would give the user the crucial context I am advocating here.)

**Comment by scheyal** [comment]
The Overview in PR #265 explains the broader context and contains additional links to specifics such as file formats, even broader context, and usage details.

**Comment by sgellock** [comment]
Fixed with PR #265
