### ISSUE TITLE
[qnamaker] qnamaker structure inconsistent

### ISSUE THREAD

**Issue by christopheranderson** [microsoft/botframework-cli#245]
## Problem:

The pattern the CLI follows is usually `bf <plugin subject>:[subject:]*[verb]`

qnamaker has the pattern of `bf qnamaker:[verb:][subject]` which inverses the pattern.

## Desired behavior

To be consistent, the pattern should be `bf: qnamaker:[subject:][verb]`.

This applies to the following:

```
  qnamaker:create
  qnamaker:delete
  qnamaker:export
  qnamaker:get
  qnamaker:list
  qnamaker:publish
  qnamaker:query
  qnamaker:refresh
  qnamaker:replace
  qnamaker:train
  qnamaker:update
```

The relevant subjects appear to be:
- kb
- endpointkeys
- alterations
-endpointsettings

**Comment by munozemilio** [comment]
I think the spec is outdated. @scheyal assigning this to you, to update specs accordingly
