### ISSUE TITLE
[chatdown][luis][qnamaker] missing force flag

### ISSUE THREAD

**Issue by christopheranderson** [microsoft/botframework-cli#247]
## Problem:

Any command with `--out` must support `--force` to be compliant to spec. The following commands that have `--out` commands do not support `--force:

- `bf chatdown`
- `bf luis:convert`
- `bf luis:translate`
- `bf qnamaker:convert`
- `bf qnamaker:translate`

## Desired solution

Ensure that these commands do take a `--force` flag and that it doesn't overwrite files unless that flag is passed.

**Comment by scheyal** [comment]
Add for consistency, yes.
