### ISSUE TITLE
[chatdown] chatdown doesn't follow CLI format

### ISSUE THREAD

**Issue by christopheranderson** [microsoft/botframework-cli#248]
## Problem

`bf chatdown` just converts the input to `.chat`, but the pattern the other commands are using is: `bf <subject>:convert`.

## Desired solution

`bf chatdown`'s functionality should be moved under `bf chatdown:convert`

**Comment by sgellock** [comment]
@scheyal @munozemilio this seems like it needs to be address before 4.6 goes out, if not, then we'd have a breaking change when we fixed it.  making this P0, unless you want to educate me that it's not.

**Comment by scheyal** [comment]
I think we should add it for parity right now.

**Comment by munozemilio** [comment]
Closed by #262
