### ISSUE TITLE
Add default LUIS application information for API call to LU library

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botframework-cli#255]
API call to LU library to parse lu to luis does not include any default values for application information (name, description, locale). Consider adding default values for API route so callers do not always have to set these before calling LUIS. 

The current work around is for users to set these via application description properties.

**Comment by scheyal** [comment]
@vishwacsena - do you imagine this as default values in config file? So we'll have bf config:set -key LUAppName - value "My Luis App" 
Or maybe an "init" command parallel to QnAMaker

**Comment by vishwacsena** [comment]
@scheyal  - this is one of those where the library .vs. CLI route both need to be handled. 

For CLI route, we already do support defaults as well as override via CLI arguments. We could totally do config file as well for consistency. 
This issue was more for consumption of the LU parser as library where the config or CLI arguments route does not work. 

Hope that helps clarify.

**Comment by munozemilio** [comment]
FIxed by #298
