### ISSUE TITLE
[docs] clarify library support level

### ISSUE THREAD

**Issue by christopheranderson** [microsoft/botframework-cli#257]
in 4.6, we intend for the CLI itself to be stable, but the underlying library code itself is not.

We should message that folks can use the CLI itself, but not to take production dependencies on the library without breaking changes between minor versions until we stabilize that surface area.

**Comment by scheyal** [comment]
For each publicly exposed library in CLI follow the guideline:
* Pass it though API review and documentation OR
* Document that it should not be used publically.

**Comment by scheyal** [comment]
We have a meeting to discuss approach.

**Comment by cleemullins** [comment]
Fixed in PR #597, currently in PR review and anticipated to resolve today.
