### ISSUE TITLE
[engineering] Standardize PR titles

### ISSUE THREAD

**Issue by christopheranderson** [microsoft/botframework-cli#281]
## Problems

1. We generate release notes from commit titles. Those commit titles have no current expected format. This means our releases notes are very messy and we have to stress about readability at release time. 
    - Additionally, it can be hard to know which things that made it in are features vs bug fixes, which makes writing the summary error prone. 

2. Knowing which PRs apply to which areas is difficult to discern without opening the PR. 
   - Inbox rules can't be optimized
   - PRs go unreviewed for longer

## Proposed solution

A standard expected PR title format & enforcement mechanisms

### Proposed format

[Angular commit guidelines format](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines) which is the default for [semantic-release](https://github.com/semantic-release/semantic-release).

That format is `<type>(<scope>): <subject>`

<details>
<summary>relevant guidelines (Click to expand)</summary>

### Commit Message Format
Each commit message consists of a **header**, a **body** and a **footer**.  The header has a special
format that includes a **type**, a **scope** and a **subject**:

```
<type>(<scope>): <subject>
<BLANK LINE>
<body>
<BLANK LINE>
<footer>
```

The **header** is mandatory and the **scope** of the header is optional.

Any line of the commit message cannot be longer 100 characters! This allows the message to be easier
to read on GitHub as well as in various git tools.

### Revert
If the commit reverts a previous commit, it should begin with `revert: `, followed by the header
of the reverted commit.
In the body it should say: `This reverts commit <hash>.`, where the hash is the SHA of the commit
being reverted.

### Type
Must be one of the following:

* **feat**: A new feature
* **fix**: A bug fix
* **docs**: Documentation only changes
* **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing
  semi-colons, etc)
* **refactor**: A code change that neither fixes a bug nor adds a feature
* **perf**: A code change that improves performance
* **test**: Adding missing or correcting existing tests
* **chore**: Changes to the build process or auxiliary tools and libraries such as documentation
  generation

### Scope
The scope could be anything specifying place of the commit change. For example `$location`,
`$browser`, `$compile`, `$rootScope`, `ngHref`, `ngClick`, `ngView`, etc...

You can use `*` when the change affects more than a single scope.

### Subject
The subject contains succinct description of the change:

* use the imperative, present tense: "change" not "changed" nor "changes"
* don't capitalize first letter
* no dot (.) at the end

### Body
Just as in the **subject**, use the imperative, present tense: "change" not "changed" nor "changes".
The body should include the motivation for the change and contrast this with previous behavior.

### Footer
The footer should contain any information about **Breaking Changes** and is also the place to
[reference GitHub issues that this commit closes][closing-issues].

**Breaking Changes** should start with the word `BREAKING CHANGE:` with a space or two newlines.
The rest of the commit message is then used for this.
</details>

For our scopes I propose the following guidelines:
- relevant scopes
    - anything in packages
    -  If you have more than 1 scope or you're not touching code under packages:
        1. Consider splitting up your PR.
        2. Omit the area if it is going to affect more than one package (and it doesn't make sense to split the PRs up) or it doesn't affect any package in particular (i.e. the root `package.json`)

#### Examples

- `feat(qnamaker): add new magic convert option`
- `fix(chatdown): handle empty files`
- `test: add e2e test for typescript compatibility`
- `docs(cli): update cli docs to include examples`
- `style(*): add prettier to all packages`
- `chore: update typescript to 3.8.0`

### Proposed enforcement mechanisms

- PR template update that documents this format in the description
- GitHub Action which will fail the PR if it doesn't match the format
    - We might be able to use this off the shelf: https://github.com/seferov/pr-lint-action

## Additional context

 - I asked how others are doing this [on Twitter](https://twitter.com/crandycodes/status/1187836973852971008), and got some good responses.
 - Node.js uses a format of `<area>: <title>` and don't specify type of change - https://github.com/nodejs/node/commits/master - These get used in their automated change notes (which also include a manually crafted summary section at the top)
 - Many other Microsoft properties don't bother with commit names for Changelogs. They instead craft them artisinally. Checked dotnet and vs code.
 - [semantic-release](https://github.com/semantic-release/semantic-release#readme) appears to have good traction and some strong endorsements

**Comment by christopheranderson** [comment]
Another option if we want to be issue driven instead of commit driven is to use labels to drive the formatting. This could be more flexible and allow us to do sections/etc. more easily. https://github-tools.github.io/github-release-notes/concept.html

**Comment by cleemullins** [comment]
I would love PR's to be *forced* to include an issue #. "Fixes #1234" or similar.

**Comment by christopheranderson** [comment]
Also goodness. Do you want that in that title or is in the body fine?

FYI - looks like this GitHub App will just enable this PR validation for us for the title format: https://github.com/probot/semantic-pull-requests

**Comment by cleemullins** [comment]
As a personal preference, and for driving higher quality release notes, having it in the title seems best.

If there is a "Best practice" or a well established enforcement mechanism, I'm good to snap to that rather than inventing something new.

**Comment by christopheranderson** [comment]
We can use the existing bot to enforce the semantic format. We'd need something else for the issue enforcement. If we do the issue enforcement, I'd suggest we try just doing action (and not including the bot) so we don't have more than 1 moving part for title enforcement.

**Comment by BruceHaley** [comment]
Intercom PRs require a Work Item # to be specified before they can be submitted. I expect github would have the same option.

**Comment by BruceHaley** [comment]
Looks like not. PULL_REQUEST_TEMPLATE does not look like it has that kind of enforcement capability, either.

**Comment by christopheranderson** [comment]
Yeah, it's more like PULL_REQUEST_SUGGESTIONS. 😜
