### ISSUE TITLE
Coveralls not showing the correct code coverge

### ISSUE THREAD

**Issue by munozemilio** [microsoft/botframework-cli#282]
The report does not match the real code coverage. You can run it locally and you can tell the mismatch

**Comment by BruceHaley** [comment]
I tried a number of different scripting scenarios without getting a meaningful coverage report published to coveralls.io. 
Build 90436 https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=90436&view=results
Pushed this: https://coveralls.io/builds/27024052
Build 90443 https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=90443&view=results
Pushed this: https://coveralls.io/builds/27024393
Looks like coveralls.io publishing support for JS does not work well for multiple packages.

We might try inspecting Botbuilder-tools-js-CI-PR coveralls output to see if it is accurate.

**Comment by BruceHaley** [comment]
This will be resolved by PR [Publish cobertura code coverage to codecov.io #850](https://github.com/microsoft/botframework-cli/pull/850)
