### ISSUE TITLE
[LuisGen] Add strong typed class support for new luis feature like sentiment

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botframework-cli#322]
## Tool
Name: LuisGen
Version: 2.2.0.0
OS: *os version*

## Describe the bug
Add strong typed class support for new luis feature like sentiment. This information also contains luis result, format like this:
"sentimentAnalysis": {
    "label": "positive",
    "score": 0.9863797
  }
https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-quickstart-intent-and-sentiment-analysis

**Comment by cleemullins** [comment]
@vishwacsena - is this a feature we need to support in LuisGen? Given that it's a new feature of LUIS, it seems we should offer support. 

@axelsrz impemented the BF-CLI LuisGen tooling, and could (probably) add this in R7.

**Comment by vishwacsena** [comment]
We should check in with @chrimc62. It would be good to support this and agree with P2.

**Comment by vishwacsena** [comment]
@chrimc62 - thoughts?

**Comment by chrimc62** [comment]
It should already end up in <yourClass>.Properties dictionary so people have access to it, the only question is if we want to assign a strong type to it.  I'm personally fine with just leaving it in properties, but @munozemilio would be better to do this if we do decide to do it.

**Comment by chrimc62** [comment]
@vishwacsena assigned to you.  I don't think we need to do this--if you do, please assign to @munozemilio

**Comment by vishwacsena** [comment]
No plans to support this per guidance above.
