### ISSUE TITLE
[Ludown] Support prebuilt domain intents and entities in Ludown

### ISSUE THREAD

**Issue by rozele** [microsoft/botframework-cli#326]
## Tool
Name: Ludown

## Describe the problem
I have a model that includes some user trained intents as well as prebuilt intents. Is there a way to represent prebuilt intents in .lu files? 

## Describe the solution you'd like
E.g., `## $PREBUILT:Utilities.Confirm`

## Describe alternatives you've considered
I attempted to roundtrip from LUIS JSON -> Ludown -> LUIS JSON to see if Ludown does have some kind of support for prebuilt intents. If I have a LUIS JSON that includes the following:
```json
  "intents": [
    {
      "name": "Calendar.ShowNext",
      "inherits": {
        "domain_name": "Calendar",
        "model_name": "ShowNext"
      }
    }
  ]
```
When I run:
```bash
ludown refresh -i luis.json -n luis.lu
ludown parse toluis --in luis.lu --out roundtrip.json
```
Then the builtin intent in `roundtrip.json` becomes:
```
  "intents": [
    {
      "name": "Calendar.ShowNext"
    }
  ]
```

[enhancement]

**Comment by vishwacsena** [comment]
Fixed in the latest bf-cli. 

You can export a LUIS application that includes pre-built domains and pre-built entities via 
```bash
> bf luis:convert --in luisapp.json --out test.lu
```

And subsequently re-convert it into a valid LUIS application JSON via 
```bash
> bf luis:convert --in test.lu --out luisapp.json
```
This will detect and preserve any prebuilt-domains and prebuilt domain entity information.

**Comment by saroup** [comment]
@vishwacsena , what if I don't want to export the LUIS application. I just want to modify my ludown file to add a prebuilt domain intent, would I be able to do that?
Right now with Ludwon 1.4 when I have this
