### ISSUE TITLE
 enabledForAllModels missing in phraselist object

### ISSUE THREAD

**Issue by munozemilio** [microsoft/botframework-cli#327]
When a phraselist is not added as a feature the enabledForAllModels property is missing when going: luis.json -> lu -> luis.json.

The expecte behavior is to set as true if not added to any intent.

**Comment by vishwacsena** [comment]
- provide control for developers to set if a phrase list is enabled for all models or not
- provide control for developers to enable/ disable a phrase list (controls activated property)
