### ISSUE TITLE
[bf luis:translate] Incorrect translate result

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botframework-cli#331]
Original text:
$Items:phraseList interchangeable
- shampoo,conditioner,towel,hand towel,bath towel,pillow,pillows,pillow case,blanket,blankets,tissues,tissue box,lotion,moisturizer,body lotion,sheets,down pillow,feather pillow,bar of soap,dish soap,laundry detergent,soap,toothpaste,deodorant,towels,toothbrush,toilet paper,body wash,sunscreen,cushion,lip balm,perfume,toothbrushes,mouthwash,shaving cream,detergent,hand sanitizer,shower gel,hand soap,hand lotion,hand cream,liquid soap,bar soap,paper towels,baby wipes,purell,hair conditioner,laundry soap,fabric softener,facial tissue,kleenex,trash bags,hair dryer,detergent powder,cleaning supplies,garbage bags,toiletries,cutlery,cleaning products,bedding,duvet,comforter,comforters,bedspread,pillowcase,duvets,pillowcases,bedspreads,linens,bedsheets,bedlinen,bedclothes,bed sheets,bedsheet,bedcovers,washcloths,bathmats,bathmat,bed sheet,handtowel,washclothes,toiletpaper,facecloths,handtowels,soap/shampoo,papertowels,babywipes,loofas,kleenexes,washrag,dishsoap,waterbottles,papertowel,qtips,chap stick,q tips,q tip,ziplocs,qtip,band aids,zip loc,ziploc,cottonballs,swabs,cotton tipped,bandaids,ziplock,bandaid,band aid,bandages,zip lock,guaze,swab,neosporin,wipes,gauze,bandage,antiseptic,trashbag,ointment,tweezers,scissors,thermometer,nail clippers,safety pins,mirror,comb,nail file,brush,sewing kit,q-tips,razor,dental floss,hairspray,shower cap,slippers,hairbrush,hair brush,combs,bobby pins,brushes,razors,hairbrushes,deoderant,shampoo/conditioner,shaver,chapstick,antiperspirant,anti perspirant,deodarant,bodywash,facewash,face wash,face cream,eye cream,mug,fork,knife,spoon,bowl,spoons,plate,pot,glass,plates,bowls,pan,mugs,pots,dish,workout clothes,work out clothes,running shoes,umbrella

After translate to zh-cn:
$Items:phraseList interchangeable
- 洗发水、护发素、毛巾、手巾、浴巾、枕头、枕头、枕套、毛毯、毛毯、纸巾、纸巾、化妆水、保湿剂、身体化妆水、床单、羽绒枕、羽毛枕、肥皂、肥皂、洗涤剂、洗衣粉、肥皂、牙膏、除臭剂、毛巾、牙刷、卫生纸、沐浴、防晒霜、唇膏、香水、牙刷、漱口水、剃须膏、洗涤剂、洗手液、沐浴露、洗手液、手化妆水、手霜、液体肥皂、肥皂、纸巾、婴儿巾、纯色、护发素、洗衣皂、织物柔软剂、面部纸巾、清洁剂、洗衣粉、清洁用品、垃圾袋、洗漱用品、餐具、清洁用品、床上用品、羽绒被、舒适器、舒适器、床罩、pillowcase,duvets,pillowcases,bedspreads,linens,bedsheets,bedlinen,bedclothes,bed sheets,bedsheet,bedcovers,washcloths,bathmats,bathmat,bed sheet,handtowel,washclothes,toiletpaper,facecloths,handtowels,soap/shampoo,papertowels,婴儿巾， 洛法斯， 克列内塞斯， 洗涤， 香皂， 水瓶， 纸巾， qtips， 章棒， q 提示， q 提示， ziplocs， qtip， 带辅助， ziploc， ziploc， 棉球， 棉签， 棉签， 带子， 拉链， 带援助， 绷带， zip锁， 瓜兹，新孢子， 湿巾， 纱布， 绷带， 防腐剂， 垃圾袋， 药膏， 钳子， 剪刀， 温度计， 指甲钳， 安全针， 镜子， 梳子， 指甲文件， 刷子， 缝纫套件， q-提示， 剃须刀， 牙线， 发胶， 淋浴帽， 拖鞋， 毛刷，梳子，博比别针，刷子，剃须刀，发刷，洗发水/护发素，剃须刀，茶棍，止汗剂，止汗剂，脱汗剂，沐浴，洗脸，洗脸，面霜，眼霜，泥巴，叉子，刀，勺子，勺子，盘子，锅，玻璃，盘子，碗，锅，泥，锅，菜，锻炼的衣服，锻炼的衣服，跑鞋，雨伞

2 issues:
1) for separator, you can see some are "、", some are "，".
2) Some words are not translated.

**Comment by vishwacsena** [comment]
@DingmaomaoBJTU do you know if this used to work with ludown?

**Comment by vishwacsena** [comment]
Tagging P0 since this is a regression from ludown.

**Comment by vishwacsena** [comment]
@DingmaomaoBJTU The translation service actually returns mixed text (english and chinese) in this case and is not a defect as such with the library itself. For this to be more effective, you should consider breaking the phrase list into a list and have each item on its own line.

```markdown
$Items:phraseList interchangeable
- shampoo
- conditioner
- towel
- hand towel
- bath towel
- pillow
- pillows
- pillow case
- blanket
- blankets
- tissues
- tissue box
- lotion
- moisturizer
- body lotion
- sheets
- down pillow
- feather pillow
- bar of soap
- dish soap
- laundry detergent
- soap
- toothpaste
- deodorant
- towels
- toothbrush
- toilet paper
- body wash
- sunscreen
- cushion
- lip balm
- perfume
- toothbrushes
- mouthwash
- shaving cream
- detergent
- hand sanitizer
- shower gel
- hand soap
- hand lotion
- hand cream
- liquid soap
- bar soap
- paper towels
- baby wipes
- purell
- hair conditioner
- laundry soap
- fabric softener
- facial tissue
- kleenex
- trash bags
- hair dryer
- detergent powder
- cleaning supplies
- garbage bags
- toiletries
- cutlery
- cleaning products
- bedding
- duvet
- comforter
- comforters
- bedspread
- pillowcase
- duvets
- pillowcases
- bedspreads
- linens
- bedsheets
- bedlinen
- bedclothes
- bed sheets
- bedsheet
- bedcovers
- washcloths
- bathmats
- bathmat
- bed sheet
- handtowel
- washclothes
- toiletpaper
- facecloths
- handtowels
- soap/shampoo
- papertowels
- babywipes
- loofas
- kleenexes
- washrag
- dishsoap
- waterbottles
- papertowel
- qtips
- chap stick
- q tips
- q tip
- ziplocs
- qtip
- band aids
- zip loc
- ziploc
- cottonballs
- swabs
- cotton tipped
- bandaids
- ziplock
- bandaid
- band aid
- bandages
- zip lock
- guaze
- swab
- neosporin
- wipes
- gauze
- bandage
- antiseptic
- trashbag
- ointment
- tweezers
- scissors
- thermometer
- nail clippers
- safety pins
- mirror
- comb
- nail file
- brush
- sewing kit
- q-tips
- razor
- dental floss
- hairspray
- shower cap
- slippers
- hairbrush
- hair brush
- combs
- bobby pins
- brushes
- razors
- hairbrushes
- deoderant
- shampoo/conditioner
- shaver
- chapstick
- antiperspirant
- anti perspirant
- deodarant
- bodywash
- facewash
- face wash
- face cream
- eye cream
- mug
- fork
- knife
- spoon
- bowl
- spoons
- plate
- pot
- glass
- plates
- bowls
- pan
- mugs
- pots
- dish
- workout clothes
- work out clothes
- running shoes
- umbrella
```

results in the following translated content 

```markdown
$Items:phraseList interchangeable
- 洗发水
- 护 发 素
- 毛巾
- 手巾
- 浴巾
- 枕头
- 枕头
- 枕套
- 毯子
- 毯子
- 组织
- 组织盒
- 化妆水
- 保湿
- 身体化妆水
- 床单
- 下枕头
- 羽毛枕头
- 肥皂棒
- 菜皂
- 洗衣粉
- 肥皂
- 牙膏
- 除 臭 剂
- 毛巾
- 牙刷
- 卫生纸
- 沐浴
- 防 晒 霜
- 垫
- 唇膏
- 香水
- 牙刷
- 漱口 水
- 剃须膏
- 洗涤剂
- 洗手液
- 沐浴露
- 手肥皂
- 手化妆水
- 手霜
- 液体肥皂
- 酒吧肥皂
- 纸巾
- 婴儿湿巾
- 纯尔
- 护发素
- 洗衣皂
- 织物软化剂
- 面部组织
- 面巾 纸
- 垃圾袋
- 吹风 机
- 洗涤剂粉末
- 清洁用品
- 垃圾袋
- 化妆品
- 餐具
- 清洁产品
- 床上用品
- 羽绒被
- 安慰
- 舒适器
- 床罩
- 枕套
- 羽绒被
- 枕套
- 床单
- 床单
- 床单
- 床上用品
- 床上用品
- 床单
- 床单
- 床罩
- 毛巾
- 浴垫
- 浴垫
- 床单
- 手巾
- 洗衣服
- 卫生纸
- 面巾
- 手巾
- 肥皂/洗发水
- 纸巾
- 婴儿巾
- 洛法斯
- 克莱内斯
- 洗涤
- 沙迪索普
- 水瓶
- 纸巾
- qtips
- 章棒
- q 提示
- q 提示
- ziplocs
- qtip
- 带辅助装置
- 邮编
- ziploc
- 棉球
- 样本
- 棉尖
- 乐队
- 拉链锁
- 班达德
- 带援助
- 绷带
- 拉链锁
- 瓜泽
- 拭 子
- 新孢斯波林
- 湿 巾
- 纱布
- 绷带
- 防腐
- 垃圾袋
- 软膏
- 镊子
- 剪刀
- 温度计
- 指甲钳
- 安全销
- 镜子
- 梳
- 指甲文件
- 刷
- 缝纫套件
- q 提示
- 剃刀
- 牙
- 发胶
- 淋浴帽
- 拖鞋
- 梳子
- 毛刷
- 梳子
- 鲍比针脚
- 刷
- 剃刀
- 发刷
- 德德兰特
- 洗发水/护发素
- 剃须刀
- 筷子
- 止 汗
- 防汗剂
- 德奥达兰特
- 沐浴
- 洗面
- 洗脸
- 面霜
- 眼霜
- 杯
- 叉
- 刀
- 勺子
- 碗
- 勺子
- 板
- 可以
- 玻璃
- 板
- 碗
- 泛
- 杯子
- 盆
- 菜
- 锻炼服装
- 锻炼衣服
- 跑鞋
- 伞
```

**Comment by DingmaomaoBJTU** [comment]
I see. Thanks!
