### ISSUE TITLE
Return error exit code when `luis:convert` fails

### ISSUE THREAD

**Issue by rozele** [microsoft/botframework-cli#346]
If I supply an invalid input or output parameter to `bf luis:convert`, I get an error message on stderr, but I still get exit code `0`. If I integrate this tool into an Azure Pipelines script task, it won't fail the task by default. If we instead return a non-zero exit code when we run into a failure (unable to read the input, parse error,  unable to write the output, etc.), the CI task would fail by default.

**Comment by rozele** [comment]
I could also just set `failOnStderr`, but I'm not sure if the tool uses stderr for, e.g., informational logging.

**Comment by munozemilio** [comment]
Hello @rozele, thanks for your input, error messages use stderr while information logs are sent to stdout. I will take a look on the exit code as well

**Comment by rozele** [comment]
One challenge is that we can't easily fail a CI build on GitHub Actions as it does not have a `failOnStderr` feature.
