### ISSUE TITLE
Closed list LUDown entities should allow non-alphanumeric characters in canonical form

### ISSUE THREAD

**Issue by rozele** [microsoft/botframework-cli#347]
If I have a LUDown file as follows:
```
$entity:Foo & Sons=
-Foo and Sons
-F&S
$entity:Maelström=
-Maelstrom
$entity:Qux (US)=
-Qux
-Qux USA
-Qux US

# MyIntent
- Tell me about Foo and Sons
- Get me info for Maelstrom
- What's going on with Qux USA
```

The `bf luis:convert` command will report the following errors:
```
line 1:12 token recognition error at: '&'
line 4:15 token recognition error at: 'ö'
line 6:12 token recognition error at: '('
line 6:15 token recognition error at: ')'
```

And the resulting LUIS JSON file strips out the non-alphanumeric characters in the canonical forms of the list entity:
```
    {
      "name": "entity",
      "subLists": [
        {
          "canonicalForm": "Foo  Sons",
          ...
        },
        {
          "canonicalForm": "Maelstrm",
           ...
        },
        {
          "canonicalForm": "Qux US",
          ...
        }
      ],
      ...
    }
```

LUIS has no such constraint for canonical forms, and this worked as expected in the `ludown` CLI  tool.

**Comment by vishwacsena** [comment]
@rozele - thanks for reporting this issue.

@feich-ms - can you help take a look and prep a fix? @boydc2014 as FYI.

**Comment by feich-ms** [comment]
@vishwacsena here is the fix PR https://github.com/microsoft/botframework-cli/pull/358
