### ISSUE TITLE
Telemetry prompt prevents usage in CI/CD environment.

### ISSUE THREAD

**Issue by jhaldiman** [microsoft/botframework-cli#370]
I'm setting up an Azure Pipeline so that I can source control a QnA Maker knowledge base, and have it deploy the changes.

In my pipeline, I'm installing the botframework-cli and then attempting to run the qnamaker:convert command.  When it executes, the following prompt appears, and prevents my pipeline from completing.

```
Help us improve products by allowing MIcrosoft to collect anonymous command and flags usage: (Y/N)
```

Is there a way I can suppress this prompt?

**Comment by munozemilio** [comment]
Hello @jhaldiman, thanks for reporting this. A quick work around it to create a config file before installing the cli in your machine with the following contents:
```
{
  "telemetry": true,
}
```

The file should be placed in the following path:
```
Unix: ~/.config/@microsoft/botframework-cli/config.json 
Windows: %LOCALAPPDATA%\@microsoft\botframework-cli\config.json 
```

**Comment by jhaldiman** [comment]
@munozemilio Thanks for the work around!  I was able to get it setup in my pipeline.

**Comment by gabog** [comment]
It seems has been addressed, closing it.

**Comment by jhaldiman** [comment]
Does this mean you will not be implementing an easier way to work around this issue?  Like a command line argument or something?

It feels weird that I will have to have any CI/CD pipeline have extra steps to generate a file to get past this prompt.

**Comment by munozemilio** [comment]
Hi @jhaldiman, we will implement an easier way to set a CI/CD pipeline in the upcoming releases

**Comment by jbkcmouli** [comment]
Same issue, its very annoying.. tried the above options of copying the file. but with hosted agents its becoming difficult to have success..
