### ISSUE TITLE
[bf qnamaker:kb:create] Can't create Knowledge Bases

### ISSUE THREAD

**Issue by Nerconer** [microsoft/botframework-cli#373]
I get an error when I try to run the command:
`$ bf qnamaker:kb:create`

Error: Cannot find module './../../../../utils/payloads/createKb'
    at Module.patchedRequire [as require] (/usr/local/lib/node_modules/@microsoft/botframework-cli/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at Object.<anonymous> (/usr/local/lib/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/bf-qnamaker/lib/commands/qnamaker/kb/create.js:12:22)

**Comment by munozemilio** [comment]
Hello @Nerconer, thanks for bringing this up. Could you please provide the cli version and OS you are running on please?

**Comment by Nerconer** [comment]
Hi, the version of the CLI I am using is 
`$ bf -v`
`@microsoft/botframework-cli/4.6.0 linux-x64 node-v8.10.0`
Regarding the OS, I am on Windows 10 Enterprise and Ubuntu's terminal downloaded from Microsoft Store to use the CLI. The current version of Ubuntu is:
`$ lsb_release -a`
`No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic`

**Comment by munozemilio** [comment]
Thanks for the information @Nercorner, I will try to reproduce in the same environment and get back to you as soon as possible.

**Comment by munozemilio** [comment]
Hello @Nerconer, just to keep you updated, for some reason one of our transient dependencies is not performing in Ubuntu. In the meantime I can suggest you to use cmd. We will keep working on this to make it work in the environment you specified

**Comment by munozemilio** [comment]
There is an issue opened against App insights team [here](https://github.com/microsoft/ApplicationInsights-node.js/issues/573)

**Comment by jspruance** [comment]
I've submitted a fix for this issue - PR here:
https://github.com/microsoft/botframework-cli/pull/413/files

**Comment by munozemilio** [comment]
Hello @Nerconer, this is fixed in 4.7.0 which is already released.

**Comment by Nerconer** [comment]
Works great, thank you!
