### ISSUE TITLE
dialog:merge dotnet dependency

### ISSUE THREAD

**Issue by christopheranderson** [microsoft/botframework-cli#385]
## Problem

dialog:merge requires dotnet to run. It crashes out if it doesn't exist. Our CI system doesn't have dotnet installed by default. The tests have been disabled in CI.

## Proposed solution

1. Add graceful handling of dotnet not existing
2. Add dotnet to CI steps
3. Re-enable merge tests

**Comment by vishwacsena** [comment]
@chrimc62 We should re-write dialog:merge without any non-JS dependency. We will not ship this with dotnet dependencies.

**Comment by chrimc62** [comment]
There is no dotnet dependency unless you search for .csproj file--in which case depending on dotnet is reasonable.
