### ISSUE TITLE
Tests fail on Linux and Mac in CI Builds (and maybe desktop)

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botframework-cli#389]

**Comment by christopheranderson** [comment]
https://github.com/microsoft/botframework-cli/blob/master/azure-pipelines.yml#L20-L23

**Comment by munozemilio** [comment]
Build is not running on those yet. @BruceHaley could you help us setting the build to run on Linux and Mac as well please?

**Comment by munozemilio** [comment]
Fixed by #532
