### ISSUE TITLE
"Entity number has duplicate definitions."for luis:convert when reference in lu file

### ISSUE THREAD

**Issue by WTobor** [microsoft/botframework-cli#392]
Based on your tests:
https://github.com/microsoft/botframework-cli/blob/4c685ed3c8b01623a62458c7f0e78d7f69e96c29/packages/lu/test/fixtures/testcases/ref10.lu
and 
https://github.com/microsoft/botframework-cli/blob/4c685ed3c8b01623a62458c7f0e78d7f69e96c29/packages/lu/test/fixtures/testcases/8.lu

I have prepared:
- file `ref10.lu` with defined prebuilt entities and reference to `8.lu` intents
- file `8.lu` with intents and reference tu `ref10.lu`
- file `8fixed.lu` with the same structure that `8.lu`, but no references, just copy of prebuild entities from `ref10.lu`

## example 1 (not working):
`bf luis:convert --in "8.lu"`
![image](https://user-images.githubusercontent.com/22730914/69610881-ff891200-102c-11ea-9bf8-1b89b8c84803.png)

## example2 (working):
`bf luis:convert --in "8fixed.lu"`
![image](https://user-images.githubusercontent.com/22730914/69611025-3b23dc00-102d-11ea-91bf-a0a046d86b5c.png)

Why the `example1` is not working? Is it expected behaviour?

Files: [luis.zip](https://github.com/microsoft/botframework-cli/files/3890678/luis.zip)

**Comment by benbrown** [comment]
@munozemilio can you take a look at this, and escalate if necessary?

**Comment by vishwacsena** [comment]
@WTobor This bug has been fixed possibly via one of the other unrelated checkins. 

I just verified no repro and correct reference merging with your sample files (thank you for the clear repro) on both master branch as well as the latest nightly build. 

We will push the latest set of fixes to npmjs as part of our next release but in the interim, you could get unblocked by installing the latest nightly package from the [nightly feed](https://botbuilder.myget.org/gallery/botframework-cli)

**Comment by WTobor** [comment]
Thank you!
