### ISSUE TITLE
luis:generate:cs generates wrong namespace

### ISSUE THREAD

**Issue by SWolObj** [microsoft/botframework-cli#397]
Command luis:generate:cs generates wrong file names of models if parameter className is with namespace. In my  case I have className as _MyProject.Services.GeneralLuisModel_, command generates me class _MyProjectServicesGeneralLuisModel_ with namespace _Luis_

**Comment by WTobor** [comment]
I have the same problem!

**Comment by axelsrz** [comment]
Thanks for submitting this issue, we will schedule the fix in an upcoming release.

**Comment by jbgh2** [comment]
Which version is this fixed in? It's still present in the version pulled from npm using the installation guide.

**Comment by munozemilio** [comment]
Hi @jbgh2, this is present in our nightly build and will be released March 16th
