### ISSUE TITLE
[bf qnamaker:kb:export] Export command doesn't preserve emojis in output

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-cli#409]
Emojis are converted to character strings when I export a kb using this export command. I tried changing the encoding of the content before writing it out to a file, but it seems like the issue is happening before it gets there.

**Comment by munozemilio** [comment]
Hi @lauren-mills , I think this might be a config issue on your terminal. I ran the command in bash and PS and the emoji got rendered just fine. Let me  know if you want me to look into a specific scenario.
