### ISSUE TITLE
[bf qnamaker:kb:export] Export command does not support multi-turn knowledge bases

### ISSUE THREAD

**Issue by ryanlengel** [microsoft/botframework-cli#439]
When running `bf qnamaker:kb:export` on a multi-turn knowledge base, the results json file stores all of the question-answer pairs in the first object of the qnaDocuments array. This in turn creates a .lu file that cannot be shared with a Virtual Assistant sample as it only contains the top-level intent. I am able to provide access to a multi-turn KB environment when this needs to be developed/tested.

Attached both LU and JSON files as .log files.

[QnA_HRBenefits_JSON.log](https://github.com/microsoft/botframework-cli/files/3974996/QnA_HRBenefits_JSON.log)

[QnA_HRBenefits_LU.log](https://github.com/microsoft/botframework-cli/files/3974994/QnA_HRBenefits_LU.log)

*I couldn't find a tracking issue for this, please link if there is one*

**Comment by vishwacsena** [comment]
Tracked via #448
