### ISSUE TITLE
[bf luis:convert] Prebuilt pattern entities not supported by LUDown

### ISSUE THREAD

**Issue by rozele** [microsoft/botframework-cli#444]
If you try to roundtrip a LUIS model with LUDown using a prebuilt intent, such as `ToDo.AddToDo`, if that prebuilt model contains pattern any entities with reseritved names (e.g., `ToDo.TaskContent.Any`), you won't be able to re-train the model, as the LUIS JSON to LUDown conversion does not include any metadata for the builtin pattern any entity.

**Comment by vishwacsena** [comment]
This has been addressed in the latest BF-CLI release. Can you try the [latest BF-CLI](https://www.npmjs.com/package/@microsoft/botframework-cli) and confirm if you continue to see this issue? 

Command to try -`bf luis:convert`

**Comment by vishwacsena** [comment]
@rozele any update here? Can you please try with with the latest BF CLI tool and comment if you continue to repro the issue? If so, can you add .lu content or LUIS json?

**Comment by saroup** [comment]
Hey @vishwacsena , I am on 
> bf --version
@microsoft/botframework-cli/4.7.0 win32-x64 node-v8.11.3

I created a model in LUIS that only had prebuilt intent toDo.AddToDo, exported that model into testmodel.json
> bf luis:convert -i testmodel.json -o fromjsontolu.lu
> bf luis:convert -i fromjsontolu.json -o fromlutojson.json

When I try to import fromlutojson.json in luis I get :
 BadArgument: The prebuilt models { ToDo.TaskContent.Any } are reserved.
It contains the patterns and patternAnyEntitiesl in this way

 "patterns": [
    {
      "pattern": "^[(can you|could you|would you)] [please] (put|add|append) {ToDo.TaskContent} [and] [{ToDo.TaskContent}] (on|to)[my][(to do|todos|todo)]list",
      "intent": "ToDo.AddToDo"
    },
    {
      "pattern": "^(add|create|append) an item [(called|about|of)] \"{ToDo.TaskContent.Any}\" [as (next|first|last) task][(in|on|to) my (to do|to-do|todos) list]",
      "intent": "ToDo.AddToDo"
    }
  ],
  "patternAnyEntities": [
    {
      "name": "ToDo.TaskContent.Any",
      "explicitList": [],
      "roles": []
    }
  ],

**Comment by rozele** [comment]
We would need the output for the LUDown -> JSON conversion to return:
```
  "patternAnyEntities": [
    {
      "name": "ToDo.TaskContent.Any",
      "inherits": {
        "domain_name": "ToDo",
        "model_name": "TaskContent.Any"
      },
      "roles": [],
      "explicitList": []
    }
  ]
```
Which likely means we need the initial conversion from JSON -> LUDown to have something similar.

**Comment by vishwacsena** [comment]
@saroup 

I cannot repro this on. Tried on a Mac as well as windows.

```
bf --version
@microsoft/botframework-cli/4.7.0 win32-x64 node-v12.11.0
```

Here's the exported JSON file from my LUIS application that has the prebuilt domain `todo.addTodo` 
added.

See attached files.. Have not looked at source code to see if this matters but can you upgrade your node version and try again? BF CLI [recommends][1] 10.14.1 or higher

[Archive.zip](https://github.com/microsoft/botframework-cli/files/4093166/Archive.zip)

[1]:https://github.com/microsoft/botframework-cli#installation

**Comment by saroup** [comment]
@vishwacsena @munozemilio  I am on v12.14.1
bf --version 
@microsoft/botframework-cli/4.7.0 win32-x64 node-v12.14.1 and when I try in luis.ai and preview.luis.ai and I still get the same error :(

**Comment by saroup** [comment]
We practically have the same output from the conversion so this seems to be doing what's expected (regardless of the node version) . The problem seems to be in the LUIS version and how it is interpreting the JSON file. Can you tell which LUIS version are you using?

**Comment by saroup** [comment]
Also it would be helpful to share the converted json from lu down based on your exported JSON .

**Comment by rozele** [comment]
@vishwacsena - in your output, I see:
```
  "patternAnyEntities": [
    {
      "name": "ToDo.TaskContent.Any",
      "explicitList": [],
      "roles": []
    }
  ]
```

Still missing the expected:
```
      "inherits": {
        "domain_name": "ToDo",
        "model_name": "TaskContent.Any"
      }
```

which will prevent the import from throwing an error about using a reserved entity name.

**Comment by vishwacsena** [comment]
@rozele @saroup thanks for helping me get to the bottom of this issue with patience. I have a PR up to address this.
