### ISSUE TITLE
luis:convert "culture was unexpected at this time"

### ISSUE THREAD

**Issue by rvallireply** [microsoft/botframework-cli#450]
Hello
trying to convert the command in the samples'  **luis_function.ps1**

```
    ludown parse toluis `
        --in $lu_file `
        --luis_culture $language `
        --out_folder $outFolder `
        --out $outFile  
```

to the CLI command

`bf luis:convert --in="($lu_file)" --culture="($language)" --out="$(Join-Path $outFolder $outFile)"`

I am getting this

`--culture was unexpected at this time.`

Is it an error or warning? it seems the language is correctly recognized anyway and the correct LUIS app culture created.

BTW: Any idea if/when the deployment scripts in the samples will be updated with the CLI version commands?

**Comment by a-b-r-o-w-n** [comment]
Hi @rvallireply what `luis_function.ps1` script are you referring to? Can you please provide a link to it?

**Comment by rvallireply** [comment]
Hi, 

Here is the link to the sample script folder, it's in the ITSM skill sample

https://github.com/microsoft/botframework-solutions/tree/master/skills/csharp/experimental/itsmskill/Deployment/Scripts

**Comment by munozemilio** [comment]
Hello @rvallireply, does the CLI command fails if you run it directly in the terminal?
@lauren-mills Do we have a target for the scripts migration?

**Comment by lauren-mills** [comment]
@rvallireply - The 0.8 release in the botframework-solutions repo yesterday includes the migration to bf cli for the ludown, luisgen, and qnamaker. bf luis support will be added in a subsequent release. Please refer to the latest ITSM skill sample in master for the updates.

**Comment by munozemilio** [comment]
Hello @rvallireply, Im closing this since the scripts are released now. Feel free to open again if you face any other issue
