### ISSUE TITLE
LUISgen generates bad C# files from JSON app file

### ISSUE THREAD

**Issue by vhnatyk** [microsoft/botframework-cli#453]
From attached JSON file, that was generated by preview.luis.ai - generated C# file has only sections

```
            // Simple entities
            public string[] amount;
            public string[] [object_Object];
            public string[] [object_Object];
            public string[] directionWithAddress;
            public string[] [object_Object];
            public string[] [object_Object];
            public string[] [object_Object];
            public string[] valueCurrency;
            public string[] [object_Object];
            public string[] [object_Object];
```
while for example entity `directionWithAddress` is not simple from JSON section

```
{
      "name": "directionWithAddress",
      "children": [
        {
          "name": "direction2",
          "children": [],
          "features": [
            {
              "featureName": "direction"
            }
          ]
        },
        {
          "name": "id",
          "children": [],
          "features": []
        },
        {
          "name": "network",
          "children": [],
          "features": []
        }
      ],
      "roles": [],
      "features": []
    },
```
[TransferFunds.zip](https://github.com/microsoft/botframework-cli/files/3999164/TransferFunds.zip)

**Comment by vishwacsena** [comment]
@vhnatyk LUISGen CLI has been deprecated in favor of [BF-CLI](https://github.com/microsoft/botframework-cli/tree/master/packages/lu#bf-luisgeneratecs). Can you please clarify if you are using LUISGen or the new `bf luis:generate` command?

**Comment by vhnatyk** [comment]
Both new cli and old gen app give bad results from JSON generated by exporr
from preview.luis.ai portal. And both give same good code from
FlightBooking.json of old sample. Seems the issue is composite section is
empty in new json file. But I thought new cli tools should handle luis
schema version 6.0.0 well?

пн, 30 груд. 2019, 21:09 користувач vishwacsena <notifications@github.com>
пише:

**Comment by bravezlecoeur** [comment]
Am facing the same issue, the tool convert all the composite entities to object_Object
this start happening when I start using schema version 6.0.0 (preview.luis.ai).

Any solution is highly appreciated , even if it is rewriting the C# file manually.

**Comment by axelsrz** [comment]
Hello @vhnatyk and @bravezlecoeur thanks you for submitting this. As you mentioned, the new tool does not currently support version 6.0.0 of the schema, but we will consider triaging this for future cycles.

**Comment by vhnatyk** [comment]
Any ETA or clues on how to fix it? Maybe there are some sources with history of schema changes? Anything :)

**Comment by tonyanziano** [comment]
Hey @cahann can you please chime in on the topic of getting the 6.0.0 schema support into the cli tooling? Thanks.

**Comment by carlosscastro** [comment]
@axelsrz could you please provide a brief update of the progress on this? Thanks!

**Comment by rurounijones** [comment]
Hit this issue today. Quick support for v6 schema would be much appreciated.
