### ISSUE TITLE
DCR: As a bot developer, I would like to be able to get training evaluation analytics about my LUIS model programmatically

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-cli#46]
The LUIS portal provides some useful training evaluation analytics about my LUIS model:

![image](https://user-images.githubusercontent.com/12264946/61144728-b6805900-a4a3-11e9-83e7-08fc62d4b204.png)

As a developer, I would like to have an API that returns this data so I can invoke it from my integration tests and perform assertions on the status of the training model, for example:

```csharp
[Fact]
public async Task AnalyticThresholds()
{
    var analyzer = new LuisAnalyzer();
    var sut = await analyzer.AnalyzeAsync("flightbooking.lu");

    Assert.True(sut.IncorrectPredictions.Count == 0);
    Assert.True(sut.ImbalancedIntents.Count == 0);
    Assert.True(sut.UnclearPredictions.Count == 0);
}
```

Preferably, I would like the LuisAnalyzer to work locally on my machine, but it may also acceptable to pass an authoring key and have the analyzer create, train and tear down my model based on the lu file or a json file.

**Comment by scheyal** [comment]
LUIS API is part of R7 release

**Comment by cleemullins** [comment]
Closed due to inactivity.

**Comment by marawanshalaby** [comment]
hey @cleemullins could you consider re-opening this issue? I am also interested in this use case
