### ISSUE TITLE
CLI bin alias not exported

### ISSUE THREAD

**Issue by narfanar** [microsoft/botframework-cli#467]
Installed via:

```
npm i @microsoft/bf-lu
```

But no combination of `bf` invocation is working from PowerShell. It's just not seen. And I can't find any `bf.exe` either.

I'd tried installing globally at first but that doesn't work either.

**Comment by srinaath** [comment]
@narfanar Did you try `npm i -g @microsoft/botframework-cli`. The lu is just a library used by cli.

**Comment by narfanar** [comment]
So here's how this misunderstanding developed:

1. I found this (https://www.npmjs.com/package/@microsoft/bf-lu), which talks (IMO) like it's a CLI tool. But it isn't :T
2. Then I found this (https://docs.microsoft.com/en-us/azure/bot-service/bf-cli-reference?view=azure-bot-service-4.0#bf-luis) which says to do `npm i -g @microsoft/botframework-cli`. And it works. But:
3. It says this:
```
#####################################################################################################
# Active development of this SDK has been moved to @azure/cognitiveservices-luis-authoring package. #
#             This package is in maintenance mode and will be deprecated in July 2019.              #
#               Visit https://aka.ms/azure-sdk-for-js-migration for more information.               #
#####################################################################################################
```
4. So I try `npm i -g @azure/cognitiveservices-luis-authoring` but that doesn't work either (no bf executable visible from PATH). And I'm not sure what the current main CLI package is.

**Comment by munozemilio** [comment]
Hello @narfanar , thanks for binging this up, sorry for the confusion, we will improve the documentation at the plugin level. The BF CLI is based on [oclif ](https://oclif.io/). The plugins are installed through @microsoft/botframework-cli as @srinaath  mentioned. The message you are getting at step 3 is a deprecation message one of our dependencies added, but there is nothing you would have to do to make the cli work. Just by running npm i -g @microsoft/botframework-cli you should be able to invoke bf cli.
