### ISSUE TITLE
bf luis:version:import not mapping phraseLists to entities

### ISSUE THREAD

**Issue by ionut-matei** [microsoft/botframework-cli#468]
Hi,

 I am using @microsoft/botframework-cli/4.7.0

I have the following JSON model:
```json
{
  "luis_schema_version": "6.0.0",
  "intents": [
    {
      "name": "Demo",
      "features": []
    }
  ],
  "entities": [
    {
      "name": "phone number",
      "children": [],
      "roles": [],
      "features": [
        {
          "featureName": "phone PL"
        }
      ]
    }
  ],
  "hierarchicals": [],
  "composites": [],
  "closedLists": [],
  "prebuiltEntities": [
    {
      "name": "datetimeV2",
      "roles": []
    },
    {
      "name": "number",
      "roles": []
    },
    {
      "name": "ordinalV2",
      "roles": []
    },
    {
      "name": "personName",
      "roles": []
    }
  ],
  "utterances": [
    {
      "text": "demo",
      "intent": "Demo",
      "entities": []
    }
  ],
  "versionId": "0.2",
  "name": "Ionut_Dev_Hcm",
  "desc": "desc",
  "culture": "en-us",
  "tokenizerVersion": "1.0.0",
  "patternAnyEntities": [],
  "regex_entities": [],
  "phraselists": [
    {
      "name": "phone PL",
      "mode": true,
      "words": "phone,phone number,telephone,cellphone",
      "activated": true,
      "enabledForAllModels": false
    }
  ],
  "regex_features": [],
  "patterns": [],
  "settings": []
}
```

After i use **bf luis:version:import** command and I open LUIS portal (preview) I can't see any mapping between "**phone number**" entity and "**phone PL**" phrase list.
![bug](https://user-images.githubusercontent.com/17688773/72175941-0950b400-33e6-11ea-9eae-0cdd91628af0.PNG)

Thank you!

**Comment by srinaath** [comment]
Thank you for the report. We are further investigating it. @munozemilio Can you take a look at it when you get a chance

**Comment by munozemilio** [comment]
Hello @ionut-matei , thanks for your input. We will address this in the current development cycle.

**Comment by jspruance** [comment]
Problem is that the version of the 'azure-cognitiveservices-luis-authoring' client being used by the bf cli (2.1.1) does not support the 'features' property on the 'entity' object in the luis schema. It gets stripped out during serialization of the schema object before making the api request and so the connection between the phraselist and the entity is lost.

Options would be to have this fixed in 'azure-cognitiveservices-luis-authoring' v2.1.1 or upgrade bf cli to use a newer version of the authoring client.

**Comment by jspruance** [comment]
Update: we've updated the luis authoring client to v4.0.0-preview.1 and retested. Now I'm able to see the association between the 'phone number' entity and the 'phone PL' phraselist in the LUIS UI.

This change is now in the master branch.

**Comment by jspruance** [comment]
fix targeted for R8 on March 8th
