### ISSUE TITLE
DCR: as a bot developer, I would like to be able to have a way of programmatically push and pull LUIS models from the LUIS portal

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-cli#47]
The current luis CLI provides some primitives to create, publish, train, etc. LUIS models but these are too granular and require writing some additional powershell to wrap them into common operations. 

As a developer, I would like to simply say:

```
luis push -luFile FlightBooking.lu -luisAppId MyAppId-luisAuthoringKey myAuthoringKey -luisSubscriptionKey mySubscriptionKey -luisAppVersion myVersion
```
And have my model created, trained, published and ready to use. 
- luisSubscriptionKey: can be optional but it should get assigned to my app if provided
- luisAppVersion should be optional and If it is not provided, it should just overwrite the latest or create a 0.1 one.

To get a a model, I would like to just say:

```
luis pull-luFile FlightBooking.lu -luisAppId MyAppId-luisAuthoringKey myAuthoringKey -luisAppVersion myVersion
```
And get a lu file with the app from LUIS:
- luisAppVersion should be optional and If it is not provided, it should just get the currently active and published model.

## Additional info

- A sample LuisPull written in powershell can be found [here](https://github.com/microsoft/botbuilder-dotnet/blob/gabog/CoreBotTests/tests/Microsoft.Bot.Builder.TestBot/CognitiveModels/luisPull.ps1)
- A sample LuisPush written in powershell can be found [here](https://github.com/microsoft/botbuilder-dotnet/blob/gabog/CoreBotTests/tests/Microsoft.Bot.Builder.TestBot/CognitiveModels/luisPush.ps1)
- These two scripts rely on a helper powershell file that uses the LUIS primitives and can be found [here](https://github.com/microsoft/botbuilder-dotnet/blob/gabog/CoreBotTests/tests/Microsoft.Bot.Builder.TestBot/CognitiveModels/luis_functions.ps1)

**Comment by scheyal** [comment]
BF LUIS is R7

**Comment by munozemilio** [comment]
Luis API will be done in R7 any parsing to Lu can be added in R8
