### ISSUE TITLE
bf:luis:convert - error for entity names containing blank spaces

### ISSUE THREAD

**Issue by ionut-matei** [microsoft/botframework-cli#472]
Hi,

I've notice that in the LUIS portal I can have entities with names containing blank spaces.
However, if I try to convert an .lu file containing such entities I get an error.

Example .lu file:
```code

> LUIS application information
> !# @app.name = DemoApp
> !# @app.desc = desc
> !# @app.versionId = 0.3
> !# @app.culture = en-us
> !# @app.luis_schema_version = 6.0.0

> # Intent definitions

## Demo
- demo

> # Entity definitions

@ ml phone number entity usesFeature phonePL


> # PREBUILT Entity definitions

@ prebuilt datetimeV2

@ prebuilt number

@ prebuilt ordinalV2

@ prebuilt personName


> # Phrase list definitions

@ phraselist phonePL(interchangeable) = 
	- phone,phone number,telephone,cellphone

> # List entities

> # RegEx entities
```
When I run "**bf luis:convert -i demo.lu**", I get the following error: "**[ERROR] line 16:18 - line 16:24: syntax error: invalid input 'entity' detected. Expecting one of this - end of file, Whitespace, new line**".

I am using @microsoft/botframework-cli/4.7.0
I expect that the same LUIS portal restrictions (regarding naming stuff) to apply to the .lu file format.
Is there any way to support this? 

Thank you!

**Comment by munozemilio** [comment]
Hello @ionut-matei , thanks for your input. We will address this in the current development cycle.

**Comment by jspruance** [comment]
Entity names with spaces in them must be contained in quotes, ex: @ ml 'phone number entity'

When formatted like this the full entity name will appear correctly in the output.

More details on lu file format here:
https://github.com/microsoft/botframework-cli/blob/master/packages/lu/docs/lu-file-format.md

**Comment by munozemilio** [comment]
> phrase lists/ add tests to ensure any entity type can have spaces in name
> Uses features should support spaces
> Roles to support spaces?
> child ml for type definition supports multi-word with quotes.
