### ISSUE TITLE
bf luis:convert doesn't work when running on ubuntu vm in Azure pipeline

### ISSUE THREAD

**Issue by saroup** [microsoft/botframework-cli#473]
The yaml file corresponding the the Azure pipeline has:
vmImage: 'ubuntu-latest"

- script: npx bf luis:convert -i $(ludownModelFolder) -o $(luisModelPath) --name=$(Build.BuildNumber) --log
 
It ran for more than 35 minutes and still haven't returned. 

When I was using 'ludown parse ToLuis' on ubuntu it was working fine. 
note: Adding "--log" didn't produce more helpful logs

**Comment by munozemilio** [comment]
Hello @saroup could you please try adding a file at the following location please:
```
Unix: ~/.config/@microsoft/botframework-cli/config.json 
Windows: %LOCALAPPDATA%\@microsoft\botframework-cli\config.json
```

with this content:
```
{
  "telemetry": true,
}
```

**Comment by saroup** [comment]
That indeed fixed it. Thank you.
