### ISSUE TITLE
bf luis - Authoring Api V3 preview

### ISSUE THREAD

**Issue by ionut-matei** [microsoft/botframework-cli#482]
Hi,
I am using @microsoft/botframework-cli/4.7.0 and I've noticed that, for all the "bf luis" commands,  botframework-cli use package "azure-cognitiveservices-luis-authoring" which calls LUIS Authoring Api V2.
https://github.com/microsoft/botframework-cli/blob/master/packages/luis/package.json

Is there a way to use LUIS Authoring API V3 preview within botframework-cli? Is there a preview/daily build of the botframework-cli which uses LUIS Authoring API V3 preview?

Thanks!

**Comment by munozemilio** [comment]
Hello @ionut-matei, we are monkey patching the url to hit the v3 endpoint. You should be able to run the commands with the version you are currently using.

**Comment by munozemilio** [comment]
In the next release (March 16h) we will swap to the latest  Azure sdk package as well.
