### ISSUE TITLE
bf luis:convert Phraselists export not compatible with Composer

### ISSUE THREAD

**Issue by dinobrago** [microsoft/botframework-cli#488]
Not clear if compatibility with Composer is a requirement. However, when exporting an existing LUIS application as json and converting to .lu format, the format of the phraselists in the lu file are in the wrong format for use in Composer. 

To recreate the problem: 
1) Find a LUIS application with a phraselist.
2) Export from LUIS online via the website
3) convert using the command >bf luis:convert -i in.json -o out.lu

The resulting phrase list definitions in the out.lu file are in the format:
`@ phraselist FamilyMember(interchangeable) = `
`	- son,daughter`

The format should be:
`$FamilyMember:PhraseList interchangeable`
`- son`
`- daughter`

**Comment by Virtual-Josh** [comment]
@cwhitten Are you the right person to take a look at this?

**Comment by cwhitten** [comment]
Hi @dinobrago. This is a known issue. We're currently integrating this library into Composer to keep the formats in sync. Your issue is a point in time one, we're hoping to have this addressed in our next officially release (March, 2020)

**Comment by dinobrago** [comment]
Thanks for the quick response!

Dean

**Comment by daveta** [comment]
Hi @dinobrago, Closing this issue.  Please reopen if you have any further questions.
thanks, -Dave
