### ISSUE TITLE
[Feature request] Support TSV file format for QnA Maker

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-cli#503]
The QnA Maker team has created different chitchat knowledge bases for different personalities that customers would like to take advantage of, but they are only provided in TSV format. If the CLI could support parsing/importing/updating etc from the TSV files in addition to JSON, the process of using and maintaining these kbs would be a lot easier.

Here is a link to the datasets: https://github.com/microsoft/BotBuilder-PersonalityChat/tree/master/CSharp/Datasets

Related issue requesting JSON formatted datasets: https://github.com/microsoft/BotBuilder-PersonalityChat/issues/48

**Comment by vishwacsena** [comment]
I'm actively working with QnA team to natively support .qna format on the service. As part of that effort, we can track making the chitchat datasets available in .qna format. 

@simer99 FYI

No plans to support .tsv in favor of that but keeping this ticket for tracking purposes until we have support for .qna.

**Comment by vishwacsena** [comment]
QnA service now natively supports import/ export to .qna format. You can use `qnaFormat = true` as part of the request to both replace and download APIs. This should help export any chitchat content in your KB in the .qna format.

**Comment by vishwacsena** [comment]
@clearab - FYI

**Comment by SSanjeevi** [comment]
@vishwacsena - can you please elaborate on it, any sample request or api reference.

**Comment by alexisquintana** [comment]
@vishwacsena How can i download qna knowledge base in qna format? https://docs.microsoft.com/en-us/rest/api/cognitiveservices/qnamaker/knowledgebase/download. I didn't find the qnaFormat parameter in the documentation. Thanks.

**Comment by vishwacsena** [comment]
@alexisquintana I just made a PR to get all qna chit chat dataset added to docs. For now, if you are looking for these, you can find them [here][1]. This PR will get them off this branch into master. 

Also to just export any KB content in .qna format, you can simply use the [export CLI command][3]. When using the download API, you can also include `qnaFormat=true` e.g. 

```
https://westus.api.cognitive.microsoft.com/qnamaker/v4.0/knowledgebases/<yourKBID>/prod/qna?qnaformat=true
```
[1]:https://github.com/microsoft/botframework-cli/blob/vishwac/qna-chitchat-docs/packages/qnamaker/docs/chit-chat-dataset.md
[2]:https://github.com/microsoft/botframework-cli/pull/869
[3]:https://github.com/microsoft/botframework-cli/tree/master/packages/qnamaker#bf-qnamakerkbexport
