### ISSUE TITLE
bf qnamaker:convert does not add word alterations to json output

### ISSUE THREAD

**Issue by fattdon** [microsoft/botframework-cli#510]
Word alterations are not added to the json output when using the convert command.

The following .qna file
```
$test:qna-alterations=
- testing
- testcase
```

evaluates to the following json

`{
  "urls": [],
  "qnaList": [],
  "files": [],
  "name": ""
}
{
  "wordAlterations": []
}`

and is missing the alterations all together. Usage should be correct, also according to test files. Looking at the test case for qna alterations, it is only checked for `.contain('"wordAlterations": [')` which is always true.

**Comment by tonyanziano** [comment]
@munozemilio can you please take a look at this?  Thanks

**Comment by jspruance** [comment]
the fix for this is merged to master

**Comment by jspruance** [comment]
fix targeted for R8 on March 8th

**Comment by munozemilio** [comment]
Hi @fattdon, we have addressed this issue and will be available in the next release. In the meantime you can consume the preview version from [myget](https://botbuilder.myget.org/feed/botframework-cli/package/npm/@microsoft/botframework-cli) if you want. thanks for reporting the issue
