### ISSUE TITLE
bf-lu: Separate export modules for client and node environment?

### ISSUE THREAD

**Issue by lei9444** [microsoft/botframework-cli#518]
In Composer, some parser APIs are used in the client(browsers), and some are used in the server (node.js). The modules are exported by one file. Sometimes some node's own modules can't be found in client.

Maybe we need to split them up into separate modules that can be imported when needed.

**Comment by vishwacsena** [comment]
@lei9444 can you list what LU capabilities are used where? 

@munozemilio let's use this to track the API cleanup for bf-lu.

**Comment by lei9444** [comment]
In client we use 
![image](https://user-images.githubusercontent.com/39758135/73804103-b0661700-47fd-11ea-8783-b563d1a92a43.png)
![image](https://user-images.githubusercontent.com/39758135/73804112-b4923480-47fd-11ea-82f6-55ddcc4296cc.png)

and in server @feich-ms has helped to add 
![image](https://user-images.githubusercontent.com/39758135/73804258-1a7ebc00-47fe-11ea-91c2-5e2c3ef0c4ce.png)

**Comment by feich-ms** [comment]
I moved lubuild related module into lubuild.js so that server can consume lubuild.js and client can consume index.js. Hope this works

**Comment by cleemullins** [comment]
Fixed in PR #597, which is review now and anticipated to close today.
