### ISSUE TITLE
bf-lu: Can we import { export1 } from "module-name" instead of "module-name/path/to/specific/un-exported/file"

### ISSUE THREAD

**Issue by lei9444** [microsoft/botframework-cli#519]
Now use
`import { parser } from '@bfcomposer/bf-lu/lib/parser';`
I think if we use 
`import { parser } from '@bfcomposer/bf-lu';`
will be more clear for user.

**Comment by vishwacsena** [comment]
Part of BF-LU clean up. 

@munozemilio

**Comment by cleemullins** [comment]
PR #597 is issued, currently in review, intention is to close and merge the PR today.

**Comment by munozemilio** [comment]
We just pushed the new V2 API with a delimited surface area.
