### ISSUE TITLE
Add bf dialog:integrate command to merge assets

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botframework-cli#523]
The goal is to be able to merge together new and old versions of assets and to have the process driven by differences between the schema files.  This could be used either to merge together different people's changes or when regenerated assets need to be integrated with possibly modified assets.  Syntax "bf dialog:integrate <newDirectory> <oldDirectory>" would integrate all changes in <newDirectory> into <oldDirectory>.  The goal is to preserve any changes made while also incorporating changes from the generated assets.

This builds on the file naming pattern changes in #526 i.e. `<schema>-<property>[-additional][.locale]<extension>`  Property is 'library' for internal assets.

To update <schema>.main.dialog, you would compare the old and new trigger array.  The cases:
* Does not match the pattern or is inline -> keep it in place.
* Property exists in old and new schema.
  * Old contains filename -> keep old reference in place.
  * Old does not contain filename -> do not add reference or file
* Property was deleted in new schema -> remove reference and file.
* Property was added in new schema -> insert it into old list after its predecessor in new that is still present and copy the new file.  The goal here is to preserve the old trigger order since it can be used for priorities.  For example if old is [a, b, c] and new is [a, b, d, c] then the d would be inserted after the b and would be the same as new.  If old had changed the order to [c, b, a] then the result of merging would be [c, b, d, a].  If new was [a, d, c] then the result would be [c, a, d].  (Because the b was deleted and the next prior to d in new was a.
* For removed properties, remove `<schema>-<property>[Entity]` references and files.

If old and new contains a trigger handler file, we will leave the old one in place.  If new is different, then we should leave old in place and spit out a message that we are not copying the file but they are different.  We don't have the information needed to know whether differences are because of changes to the original modified file or because of template changes.  If someone wants the merge process to override with the new file, then they should delete the file.  (Although leave the reference in the main dialog.)

To update <schema>.<locale>.lg we want to maintain the same structure as much as possible.  Purely generated files have a collection of references to other files.  For each entry in the .lg file:
* If an lg template definition preserve it in place.
* If an lg reference that does not match the pattern keep it in place.
* Property exists in old and new schema
  * If an lg reference and property exists in both old and new, keep it 
  * If the reference is not in old, then don't copy the file.
* Property was deleted in new schema -> remove reference and file
* Property was added in new schema -> add reference to end and file

For the individual .lg files, we need to update parts that were generated from enums.  By naming convention we would update files that match <schema>-<PropertyEntity>.<locale>.lg and within that we need to update the template <Property>Entity which is a switch with a case for each unique enum value.  To modify this:
* If enum value exists in both, leave it alone.
* If new includes a new enum value, then add a new case for that value to the end.
* If new removes an enum value, then remove the case for that value.

To update <schema>.<locale>.lu we want to maintain the same structure as much as possible.  Purely generated files have a collection of references to other .lu files.  For each entry in the top-level .lu file:
* Inline definition, leave it in place.
* Reference to file that does not match the pattern, leave it in place.
* Property exists in both old and new
  * If there is a reference in old leave it
  * If there is not a reference in old, do not add it
* Property was deleted in new schema -> remove the reference and the file
* Property was added in new schema -> add reference and the file

Files that match <schema>-<Property>Entity.<locale>.lu need to be updated for what is generated from the schema enum values.  To do this you go through the definitions in the file:
* If enum value exists in both and $<propertyEntity>:<value>= clause exists leave it.  If not, then don't add it.
* If enum value is added in new, then add it to the .lu file.
* If enum value is removed in new, then remove it from the .lu file

**Comment by coldplaying42** [comment]
Except the main.dialog file, do we need to compare and update other .dialog files? For example, the old version and new version both have property Meat for the sandwich schema, therefore, both version assets have the sandwich-Meat-missing.dialog file. If the sandwich-Meat-missing.dialog file in the new version is edited by Composer (e.g., add a new action), how to deal with this case?

For lg files, both versions might also have the sandwich-Meat.en-us.lg file, if the sandwich-Meat.en-us.lg in new version is edited by Composer (e.g, add new templates, change the content of existing templates), do we need to update sandwich-Meat.en-us.lg in the old version?

**Comment by coldplaying42** [comment]
I hope to confirm what are the main differences between the bot generated by new version assets and the bot generated by the merged version assets. Based on my understanding, the differences are as follows: 1) The trigger order might be different. 2) if both old and new versions have the same property, the merged version assets always keep the corresponding old .dialog .lu and .lg files.
