### ISSUE TITLE
Generate JSON schema & templates from Swagger file

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-cli#528]
## Overview
As a developer, I can generate JSON schema and templates from a Swagger file, which can then be used to generate dialogs.

## Related Issues

- [ ] [Card templates](https://github.com/microsoft/botframework-cli/issues/535)

**Comment by chrimc62** [comment]
@coldplaying42 I moved this to R10--this is an experimental feature and we can add when needed, but should not be tracked as part of R9.

**Comment by cleemullins** [comment]
Removing R11 milestone, pushing to backlog.
