### ISSUE TITLE
Card templates for binding data from a Swagger file to a card response

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-cli#535]
**Overview**
As a developer, I'd like to be able to create templates for card responses that could be passed to the generation tool and be bound to data.

**Example**
I create an Adaptive Card template with placeholders for values returned from a particular API response. When the generation tool is run, the template is instantiated as part of the dialog response.

**Comment by cleemullins** [comment]
Can we punt this to R10?

**Comment by clearab** [comment]
This is part of generated dialogs, so not part of the release train
