### ISSUE TITLE
Creating KB with more than 1,000 questions leads to an Error "Field 'Qn A List' cannot have more than 1000 items"

### ISSUE THREAD

**Issue by marawanshalaby** [microsoft/botframework-cli#538]
I am using the bf cli to create a knowledge base from a qna json file, using:

```
bf qnamaker:kb:create --name myKB--subscriptionKey <my_key> --in abbreviations.qna
```
This call however fails if my abbreviations.qna file contains more than 1,000 questions in the `qnaList` element with the error:
```
{
    "code": "BadArgument",
    "message": "Invalid input. See details.",
    "details": [
        {
            "code": "ValidationFailure",
            "message": "Field 'Qn A List' cannot have more than 1000 items",
            "target": "QnAList"
        }
    ]
}
```

Strangely though, doing a `bf qnamaker:kb:replace --kbId <my_kb_id> --in abbreviations.qna` on an already existing KB works fine and doesn't complain about the 1,000 question limit. For qnamaker itself, there is no such [limitation](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/limits) , and I even checked my azure search instance and there is no quota for the number of documents in an index.

Is there a client-side limit imposed on the length of the json list and is there a reason for this discrepancy between the `create` and `replace` commands?

My qna maker is located in westus and my pricing tier is Standard. I am using bf-cli v4.7.0

**Comment by munozemilio** [comment]
Hi @marawanshalaby, thanks for reporting this. That response comes directly from the API but I will reach out to the QnAMaker team to clarify this and get back to you.

**Comment by simer99** [comment]
Create Api does have a limit of 1000 QnA pairs per request. Replace api does not have any limit. If you have more than 1000 QnA pairs, you will either have to make a second call or create an empty Kb and do a replace call.

**Comment by marawanshalaby** [comment]
@simer99 thank you for the response. Is there a reason for this discrepancy on the API side? Do you know if this limit will be lifted in an upcoming version?

**Comment by daveta** [comment]
@marawanshalaby : Here's a message from @simer99..

> It is by design that we have a validation on create API. We do not have plans in the near future to remove/increase this limit. 

Thanks, -Dave

**Comment by marawanshalaby** [comment]
@simer99 ok, so I guess my only option is to create an empty KB and then immediately replace. Would it be possible to update the documentation for the API to reflect this limitation? It took us a day to figure out the source of this error we were getting

**Comment by daveta** [comment]
@marawanshalaby : Another message from @simer99:

  > We will update the create API documentation. 

Thanks, -Dave

**Comment by marawanshalaby** [comment]
Thank you
