### ISSUE TITLE
luis:build refinements

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botframework-cli#548]
There are few improvements/ refinements to make to luis:build

1. Today, by default the write all generated files to the cwd() or the --out folder (if specified). We should change this behavior such that, **in cases where no --out folder is specified**,
    - any .dialog file generated should go to the respective folder where the .lu file was found. As an example, if the user ran `bf luis:build --in /myBot` and we found these two .lu files - `./dialog1/dialog1.lu` and `./dialog2/dialog2.lu` then all *.lu.dialog for dialog1.lu should go under `./dialog` and those for dialog2.lu should go under `./dialog2`.
   - **NOTE:** this is the default behavior when no --out folder is specified
2. luis:build write out a lot to console. we should move all these messages to be rendered only when `--log` is specified. By default, 
    - in cases where --dialog is not specified, write out the appIds list at the end of the operation
    - in cases where --dialog is specified, write `Successfully wrote .dialog files to <out-folder>`
    - write to console.error when there are any errors that prevent successful completion of the command
3. Replace `--culture` with `--defaultculture`
4. Add a `--config <path-to-config>`. This is the exact same [luconfig.json][1] that lubuild supported.
```jsonc
{
// CLI argument for --botName can be skipped if this is specified
    "name":"MyProject",
// CLI argument for --defaultCulture (--culture) can be skipped if this is specified. This is the application culture if a single .lu file is passed via --in. This is also the default culture for any .lu file without a lang-code in file name if a folder is passed in to --in. (e,.g. foo.lu will be foo.fr-fr.lu assuming --defaultCulture is set to fr-fr. This will continue to default to en-us
    "defaultLanguage":"en-us",
   // defaults to false when not specified. When set to true, old model version (when we create a new version) is automatically deleted for all applications
   "deleteOldVersion": true, 
   // absolute or relative path to set the output folder.
   "out": ".",
    // defaults to false when absent
    "writeDialogFiles": true,
    // each model is an application
    "models": [
        // each line is to an lu file and each line corresponds to a luis application. 
        "test/test.lu",
        "test/sample/x/Contoso.Foo.lu",
        "test/test.fr-fr.lu"
    ]
}
```

 
[1]:https://github.com/microsoft/botbuilder-tools/tree/V.Future/packages/lubuild#config-file

**Comment by feich-ms** [comment]
try to fix in PR #477

**Comment by vishwacsena** [comment]
@feich-ms ok. Let me know when you have it ready and I can test it.

**Comment by munozemilio** [comment]
PR merged
