### ISSUE TITLE
Add tokenizerVersion parameter to bf luis:convert

### ISSUE THREAD

**Issue by marawanshalaby** [microsoft/botframework-cli#550]
We are training german models and would like to specify the [tokenizerVersion](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-language-support)  to be injected into the json file created by `bf luis:convert`. Currently it's only possible to specify this parameter manually in the json file because neither the `ludown` nor the `bf-cli` tools support adding it automatically to the json file they generate from the raw `.lu` file. 

Related ticket about the documentation for this feauture in the luis json file: https://github.com/MicrosoftDocs/azure-docs/issues/47575

**Comment by daveta** [comment]
@scheyal : Can you please triage this?

**Comment by clearab** [comment]
@vishwacsena Can you take a look at this please?
