### ISSUE TITLE
Document usage of Telemetry CI bypass flag

### ISSUE THREAD

**Issue by scheyal** [microsoft/botframework-cli#562]
we need to document the usage of telemetry ci bypass flag for privacy compliance & use guidelines.
do before release.

**Comment by scheyal** [comment]
PR for doc is pending, @munozemilio may adjust text & location.

**Comment by cleemullins** [comment]
This is done, via the PR #563

**Comment by munozemilio** [comment]
We have to close this after R8 release otherwise the documentation wont be accurate

**Comment by cleemullins** [comment]
@munozemilio - Ah. thanks. I thought I was helping. :)

**Comment by cleemullins** [comment]
This is done, pending release of R8 at which point we can merge.

**Comment by cleemullins** [comment]
Pushed to R9, as we'll actualy do this release in R9 as it depends on R8.
