### ISSUE TITLE
Exceptions are not returned properly in luis:build

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botframework-cli#582]
## Describe the bug
Specific exceptions are ending up with a generic string describing them.  This looks to be caused by this missing in some files like luis.js:
const retCode = require('./../utils/enums/CLI-errors')

## To Reproduce
1. Create two .lu files that both define the same composite, but with different definitions.
2. Do bf luis:build on the files

## Expected behavior
Specific exception descriptions.

[bug]

**Comment by vishwacsena** [comment]
@feich-ms let me know if you need to load balance this. I can take a look next week.

**Comment by feich-ms** [comment]
@vishwacsena, I have bandwidth and will take a fix.

**Comment by feich-ms** [comment]
fix by PR #576

**Comment by munozemilio** [comment]
PR merged
