### ISSUE TITLE
luis:generate:cs - Typo in the tool link in generated CS file

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/botframework-cli#589]
luis:generate:cs generates a file with typo in the link:

// <auto-generated>
// Code generated by luis:generate:cs
// Tool github: https://github.com/microsoft/botframwork-cli
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

**Comment by carlosscastro** [comment]
Thanks for reporting, we'll fix promptly. @axelsrz you are up :)

**Comment by carlosscastro** [comment]
@axelsrz any updates?

**Comment by axelsrz** [comment]
Hello @turbozapekanka thanks for submitting this issue, we will triage it for current cycle and provide a fix in the next release
