### ISSUE TITLE
Updating local models corrupts LU and QNA files

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/botframework-cli#591]
#### What project is affected?
Virtual Assistant

#### What language is this in?
C#

#### What happens?
1. LU and QNA files gets corrupted (see screenshot)
2. If QNA models were updated and URL has been used to upload QNA pairs, this URL gets lost and the Source is instead reset to "> Source: custom editorial"

#### What are the steps to reproduce this issue?
1. Deploy VA with English and Spanish languages
./Deployment/Scripts/deploy.ps1 -languages "en-us,es-es"
2. Change remote QnA maker and Luis models using portals. Upload new QnA pairs from some URL, e.g. https://www.linkedin.com/help/linkedin/answer/76305/linkedin-homepage-faqs
3. Follow these instructions to update the local files with changes made to the remote models:
https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/customize-assistant/csharp/4-edit-your-cognitive-models/
./Deployment/Scripts/update_cognitive_models.ps1 -RemoteToLocal

#### What were you expecting to happen?
1. Local files are updated with changes (and only changes) I made to remote models. 
2. > Source: https://www.linkedin.com/help/linkedin/answer/76305/linkedin-homepage-faqs is preserved in the updated QNA files

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/20775323/74873777-6fa1ee00-5325-11ea-8f0c-e7ec0d3be7e7.png)

**Comment by carlosscastro** [comment]
@CoHealer could you please assign this for repro please? Thanks!

**Comment by mdrichardson** [comment]
@carlosscastro I'll attempt repro and report back

**Comment by mdrichardson** [comment]
@carlosscastro 

I wasn't able to repro *any* of the original issue.

1. None of my files were corrupted
2. Only the files under `/Dispatch` changed and none of them were `.qna` files

@turbozapekanka 
 What version of luisgen are you running? `luisgen -v`
Where there any other repro steps that would've caused the `.qna` files to change?

**Comment by turbozapekanka** [comment]
LUISGen version 2.0.2.0
both QNA and LU files got corrupted in a similar way and at the same time. The screenshot only shows QNA as an example.
I'm available to demonstrate or record any other details to help repro this.

**Comment by mdrichardson** [comment]
@turbozapekanka Odd. None of my .lu files even changed; only things under the `/Dispatch` folder. I tried with both v2.0.2 and v2.2.0. Are you sure those are the full steps? If so, a recording may help just to make sure I'm doing exactly the same thing--I know that's a big ask.

**Comment by mdrichardson** [comment]
@turbozapekanka Are you still experiencing this? Can you confirm that your repro steps are complete and accurate?

**Comment by turbozapekanka** [comment]
I haven't had a chance to record the steps yet. Please give me more time.

**Comment by turbozapekanka** [comment]
I pinpointed the issue to be in **bf qnamaker:kb:export** - it exports the JSON file wrong:
QNA portal:

![image](https://user-images.githubusercontent.com/20775323/75485561-8624f680-5970-11ea-8af6-2fbb9cf3094c.png)

result of  bf qnamaker:kb:export --environment=Prod --kbId=xxx --subscriptionKey=xxx > Chitchat.json
![image](https://user-images.githubusercontent.com/20775323/75485628-a5bc1f00-5970-11ea-9e33-7447a2bba857.png)

**Comment by turbozapekanka** [comment]
Same issue with **luis export version** command - exported json is corrupted:

![image](https://user-images.githubusercontent.com/20775323/75486376-09931780-5972-11ea-9fe8-5f93de03960b.png)

**Comment by turbozapekanka** [comment]
I use pwsh.exe command prompt, Not sure if it makes any difference.

**Comment by turbozapekanka** [comment]
It looks like it does. just tried to run the same command in cmd.exe and it worked just fine.
So it must be something wrong with PowerShell 6.2.3

**Comment by mdrichardson** [comment]
@turbozapekanka Thanks for all of the troubleshooting! I'll attempt to repro and fix this tomorrow. I believe I ran the original `./Deployment/Scripts/update_cognitive_models.ps1 -RemoteToLocal` command in pwsh v6.2.2, so I find this a little odd. What OS are you using?

**Comment by turbozapekanka** [comment]
Windows 10 x64, should be up to date

**Comment by mdrichardson** [comment]
@turbozapekanka I was able to repro using just the `bf qnamaker:kb:export --environment=Prod --kbId=xxx --subscriptionKey=xxx > Chitchat.json` but not when using the `.ps1` file. Happened in both PS v5.1 and v6.2 and not Command Prompt. 

I'll see if I can figure out how to make it compatible with PowerShell. Thanks for all the repros!

**Comment by mdrichardson** [comment]
@turbozapekanka 

Can you confirm that you get this error when you call `./Deployment/Scripts/update_cognitive_models.ps1 -RemoteToLocal`? I can't seem to repro with that.

However, I did find a fix for the other. Use:

```bash
bf qnamaker:kb:export --environment=Prod --kbId=xxx --subscriptionKey=xxx | Out-File -encoding oem ./ChitChat.json
```

I ask about confirming this occurs with the `ps1` file because I see that it uses `>` and will submit a PR if it occurs for you--it just doesn't for me for some reason.

**Comment by turbozapekanka** [comment]
Yes I initially ran into this issue when I wanted to update my local files from remote models and I used this `./Deployment/Scripts/update_cognitive_models.ps1 -RemoteToLocal ` script. You can see the result of this on my very first screenshot here.

If you look inside the script file you will see that it uses `>` to create JSON files. See lines 143 and 199:
[update_cognitive_models.ps1.txt](https://github.com/microsoft/botframework-cli/files/4269081/update_cognitive_models.ps1.txt)

**Comment by turbozapekanka** [comment]
Why would something work differently when run directly from pwsh prompt and from .ps1 file?

**Comment by mdrichardson** [comment]
@turbozapekanka Thanks for confirming. I'm not sure why it would work any differently, just that it did for me. I'll submit PRs for the change in Virtual Assistant. Was there any documentation for the CLI or VA that recommended you use `> <filename>.json`?

**Comment by turbozapekanka** [comment]
I didnt use `>`. I used provided `ps1` scripts and instructions says use `pwsh`: https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/csharp/4-provision-your-azure-resources/

Now sure what bf-cli documentation says.

**Comment by turbozapekanka** [comment]
BTW, PR that replaces `>` with `| Out-File -encoding oem` looks more like a workaround rather that the fix. I'd ask PowerShell team to take a look on this.

**Comment by mdrichardson** [comment]
@turbozapekanka I'll submit the PR for Virtual Assistant. I don't believe it's a powershell bug. `>` defaults to using `-encoding Unicode`, which also "breaks". I'm not sure if it should or not, but I would guess that's a breaking change for PowerShell.
