### ISSUE TITLE
packages/qnamaker tests keep failing

### ISSUE THREAD

**Issue by feich-ms** [microsoft/botframework-cli#598]
## Versions
master branch

## Describe the bug
'rush test -t @microsoft/bf-qnamaker' is always failing

## To Reproduce
1. checkout master branch
2. run 'rush update'
3. run 'rush build'
4. run 'rush test -t @microsoft/bf-qnamaker'

You will see below error
![image](https://user-images.githubusercontent.com/43032123/75127644-3a1d4c00-56fb-11ea-89a2-6d80e4fd598c.png)

## Expected behavior
Tests should pass

## Additional context

[bug]

**Comment by feich-ms** [comment]
@vishwacsena, can you reassign to the right onwer of qnamake CLI

**Comment by cleemullins** [comment]
This only happens for @feich-ms. This build passes for @munozemilio and on the automated build. More investigation is needed on our end, but as it's isolated to a single person this is low priority.

**Comment by mdrichardson** [comment]
@feich-ms I'm able to pass all tests in Node versions:

* 10.19.0
* 11.15.0
* 12.0.0

Can you please provide the following information:

1. Operating System
2. Node version `node -v`
3. npm version `npm -v`
4. Terminal (Command Prompt, PowerShell, etc)

Perhaps you need to run `npm install -g @microsoft/rush@latest`?

**Comment by feich-ms** [comment]
@mdrichardson, the tests still keep failing even I install the latest rush. Below are my tests env:
1. Operating System: windows 10
Node version node -v: v12.13.1
npm version npm -v: 6.13.0
Terminal (Command Prompt, PowerShell, etc): Command Prompt

**Comment by mdrichardson** [comment]
@feich-ms Alright, thanks for the info! I'll see what I can do to repro this so I can start fixing it. If you think of any steps I can take to repro consistently, let me know.

**Comment by munozemilio** [comment]
Hi @feich-ms , I just increased the timeout for qnamaker. Build is not failing due to this and we dont have a repro yet in our machines. I will relabel this since it is not impacting our release

**Comment by feich-ms** [comment]
Thanks to @mdrichardson and @munozemilio. I tried the qna maker tests again and they all passed now. I didn't take any actions. Anyway, I think we can close this issue first.
