### ISSUE TITLE
Azure CLI Bot extension not available

### ISSUE THREAD

**Issue by sschutten** [microsoft/botframework-cli#608]
## Versions
CLI: 2.1.0
Windows Terminal: 0.9.433.0
Windows 10 1909

## Describe the bug
When I try to install the Azure CLI Bot extension as per [the docs](https://github.com/microsoft/botframework-cli/blob/master/AzureCli.md) I receive the following error:

> No matching extensions for 'botservice'. Use --debug for more information.

## To Reproduce
Follow the steps in [the docs](https://github.com/microsoft/botframework-cli/blob/master/AzureCli.md) to install the extension

and

run the following command and notice that `botservice` isn't listed.
```
az extension list-available --output table
```

## Expected behavior
I expected the extension to be installed.

Is the Azure CLI extension also replaced by the BF CLI?

**Comment by munozemilio** [comment]
Hello @sschutten, the Azure CLI is not replaced by BF CLI. Azure CLI addresses the resource management in Azure, BF CLI produces input for those resources. Maybe you are looking for az bot? This a [link](https://docs.microsoft.com/en-us/cli/azure/bot?view=azure-cli-latest) to the description. Let me know if this helps

**Comment by sschutten** [comment]
Hi @munozemilio I was indeed looking for `az bot`. [The docs](https://github.com/microsoft/botframework-cli/blob/master/AzureCli.md) speak of installing it as an extension, but it appears `az bot` is now included in the Azure CLI by default. The docs seem to be a little outdated.

**Comment by munozemilio** [comment]
@scheyal could you please update the docs pointed by @sschutten to reflect the latest from az cli?

**Comment by scheyal** [comment]
pending PR #634

**Comment by scheyal** [comment]
Fixed (PR approved today)
