### ISSUE TITLE
bf luis:translate improvements

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botframework-cli#613]
Today the translate command does not automatically set the culture in the LUIS app to be the target lang. We should do this via `> !# @app.culture = <tgtculture>`

Adaptive dialogs, LG use file naming convention to detect language x locale. We should support this as the default,
- When --out is specified, all localized files are written out to --out folder with srcLuFileName.tgtLocale.lu as the file name.
- When --folderPerLang is specified, create one tgtLocale folder under the --out path and write out the localized files as srcLuFileName.lu.

**Comment by cleemullins** [comment]
@vishwacsena, I don't have enough context to prioritize or triage this. Is this an R9 issue, R10 issue, or something we should consider not doing?

**Comment by vishwacsena** [comment]
@cleemullins I'd like to do this for R9 since we are planning to get adaptive to stable release. It is not a must have for R9 which is why I tagged it as P1.

**Comment by cleemullins** [comment]
Thanks @vishwacsena. Who would you have do the work? Emilio is booked. Can @chrismc62 do this, or one of the STCA or LUIS Devs?

**Comment by vishwacsena** [comment]
@cleemullins I can work on this as part of #686 and have @munozemilio review.

**Comment by vishwacsena** [comment]
Not going to get to this in R9. Moving to backlog.

**Comment by vishwacsena** [comment]
@clearab FYI
