### ISSUE TITLE
cross-train auto-detect config based on .dialog files

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botframework-cli#614]
Today we expect the user to manually provide a config for cross-training but instead when the user points us to the rootDialog, we should walk the dialog files to figure out the hierarchy. To do that, we should 
1. recursively walk each dialog file starting with the root dialog. 
2. For each OnIntent trigger that has a BeginDialog action, capture the trigger's intent name as the trigger and the child dialog's LU file as the target. Use the recognizer property to get the lu file name for this dialog, find the file by name under the root folder scope to find the path to the .lu file. 

Cross train should ask for a manual configuration if a dialog with #2 does not have a valid .lu file set as its recognizer (e.g. recognizer is manually configured)

With this, if I have declarative bot, the user can just point to the root folder and the root dialog name and we can figure the rest.

**Comment by feich-ms** [comment]
@vishwacsena, can you point to any samples of such dialog folder hierarchy so that I can better understand them.

**Comment by vishwacsena** [comment]
I do not have one but we should create few with composer and managed LU.

**Comment by feich-ms** [comment]
I got some samples from composer guys. Will try to parse them.

**Comment by feich-ms** [comment]
For above _**Use the recognizer property to get the lu file name for this dialog**_, what do you mean recognizer property, you mean child dialog name? More specifically, for the example below, what will be picked as the child lu file name

{
    "$kind": "Microsoft.AdaptiveDialog",
    "id": "rootDialog",
    "recognizer": {
        "$kind": "Microsoft.RegexRecognizer",
        "intents": [
            {
                "intent": "JokeIntent",
                "pattern": "joke"
            }
        ]
    },
    "triggers": [
        {
            "$kind": "Microsoft.OnIntent",
            "intent": "JokeIntent",
            "actions": [
                {
                    "$kind": "Microsoft.BeginDialog",
                    "options": {},
                    "dialog": "TellJokeDialog"
                }
            ]
        }
    ],
}

**Comment by vishwacsena** [comment]
@feich-ms does not apply in your example but the whole idea with using something like luis:build is to the recognizer property can simply be set to the .lu file that contains the triggers/ LU definition for that dialog. So looking for `"recognizer" : "foo.lu"` indicates that `foo.lu` is the backing .lu file for this dialog. As noted in the original ask, we should just throw an error and stop auto-detection if we cannot find the right .lu resources for a dialog.

**Comment by feich-ms** [comment]
Synced with @lei9444 who is working on the cross-train in composer side, he has already done the config construction work in composer side. In our side, we can only add the construction work in the CLI part instead of the cross-train library part. In this way, no matter how files hierarchy changes or .dialog file format changes, the cross-train core library doesn't need to update. All the updates can be operated in composer side or CLI side. Does this make sense?

**Comment by feich-ms** [comment]
@vishwacsena, add the support of automatically detecting config based on rootDialog and file system in [cross-train ](https://github.com/microsoft/botframework-cli/tree/cross-train)branch, the commit is here https://github.com/microsoft/botframework-cli/commit/cf53d2a9f936b2ef571ac78eaf332544b9bb27f2. We can use the --rootDialog to specify root dialog file and then it can construct the config in memory and do cross training. For the dialog file format, I refer to files provided by leilei, you can find them in packages/cross-train/test/fixtures/testcases/interruption4.

**Comment by vishwacsena** [comment]
Cool. Is this the same logic used in composer if not, what and why are they not the same?

**Comment by feich-ms** [comment]
The core paring logic is same, the only difference is that composer is paring dialog file to DialogInfo class which is defined in composer, but I'm paring it to json object in CLI.

**Comment by vishwacsena** [comment]
Closing this.
