### ISSUE TITLE
chatdown not working in windows powershell

### ISSUE THREAD

**Issue by rkm050288** [microsoft/botframework-cli#616]
I am trying to run chatdown command using bf cli, but it throws error saying there is no file or directory. Please could you check.

PS C:\Users\Administrator\Downloads\teams-bot\chat> bf chatdown:convert --in sample.chat
Unknown error during execution. Please file an issue on https://github.com/microsoft/botframework-cli/issues
ENOENT: no such file or directory, open 'C:\Users\Administrator\Downloads\teams-bot\chat\bot-framework.png'
PS C:\Users\Administrator\Downloads\teams-bot\chat> bf --version
@microsoft/botframework-cli/4.7.0 win32-x64 node-v12.16.1
PS C:\Users\Administrator\Downloads\teams-bot\chat> node --version
v12.16.1
PS C:\Users\Administrator\Downloads\teams-bot\chat> ls

    Directory: C:\Users\Administrator\Downloads\teams-bot\chat

Mode                LastWriteTime         Length Name                                                                                                                                                      
----                -------------         ------ ----                                                                                                                                                      
-a----        2/28/2020   4:15 PM            465 sample.chat

**Comment by vishwacsena** [comment]
Unable to repro this. @rkm050288 can you clarify what version of bf cli you see this on? 

```
> bf --version
@microsoft/botframework-cli/4.8.0-preview.100982 darwin-x64 node-v12.13.1

> bf chatdown:convert --in packages/chatdown/docs/examples/Greeting.chat 
[
  {
    "conversation": {
      "id": "CasSix4xs3yIFPMVEZCpi/gqU2E="
    },
    "id": "1",
    "recipient": {
      "id": "jopVZjYqyE3A5EnA8dYrlA+Mubw=",
      "name": "cafebot",
      "role": "bot"
    },
    "from": {
      "id": "aqMkJoc/DqiL+cgiJhoUJCxSZ+U=",
      "name": "vishwac",
      "role": "user"
    },
    "timestamp": "2020-02-28T18:54:41.100Z",
    "type": "conversationUpdate",
    "channelId": "chatdown",
    "membersAdded": [
      {
        "id": "jopVZjYqyE3A5EnA8dYrlA+Mubw=",
        "name": "cafebot",
        "role": "bot"
      }
    ],
    "membersRemoved": []
  },
  {
    "conversation": {
      "id": "CasSix4xs3yIFPMVEZCpi/gqU2E="
    },
    "id": "2",
    "recipient": {
      "id": "jopVZjYqyE3A5EnA8dYrlA+Mubw=",
      "name": "cafebot",
      "role": "bot"
    },
    "from": {
      "id": "aqMkJoc/DqiL+cgiJhoUJCxSZ+U=",
      "name": "vishwac",
      "role": "user"
    },
    "text": "hi",
    "timestamp": "2020-02-28T18:54:43.100Z",
    "type": "message",
    "channelId": "chatdown"
  },
  {
    "conversation": {
      "id": "CasSix4xs3yIFPMVEZCpi/gqU2E="
    },
    "id": "3",
    "recipient": {
      "id": "aqMkJoc/DqiL+cgiJhoUJCxSZ+U=",
      "name": "vishwac",
      "role": "user"
    },
    "from": {
      "id": "jopVZjYqyE3A5EnA8dYrlA+Mubw=",
      "name": "cafebot",
      "role": "bot"
    },
    "text": "Hello, I'm the contoso cafe bot. How can I help you?",
    "timestamp": "2020-02-28T18:54:45.100Z",
    "type": "message",
    "channelId": "chatdown"
  }
]
```

**Comment by rkm050288** [comment]
@microsoft/botframework-cli/4.7.0 linux-x64 node-v8.16.2
This is version in my WSL 

@microsoft/botframework-cli/4.7.0 win32-x64 node-v12.16.1
This is my version in Windows server.

**Comment by rkm050288** [comment]
I updated node version in my WSL to 12.16.1 and the issue still persists
`@microsoft/botframework-cli/4.7.0 linux-x64 node-v12.16.1`

**Comment by scheyal** [comment]
I think this is specific to the user environment / data. 
Can you tell us more about your data/directory? Is it canned sample or specific to your solution?
I propose to deprioritize - not R9.

**Comment by cleemullins** [comment]
@mdrichardson, do you a moment to get a repro put together?

**Comment by mdrichardson** [comment]
@rkm050288 Are you still experiencing this issue? If so, is it for both WSL and Windows that this happens? Can you tell us more about your data/directory? Is it canned sample or specific to your solution? If you can zip it up and send it, that may be helpful.

**Comment by mdrichardson** [comment]
@rkm050288 Are you still experiencing this issue? If so, is it for both WSL and Windows that this happens? Can you tell us more about your data/directory? Is it canned sample or specific to your solution? If you can zip it up and send it, that may be helpful.

**Comment by mdrichardson** [comment]
@rkm050288 Are you still experiencing this issue? If so, is it for both WSL and Windows that this happens? Can you tell us more about your data/directory? Is it canned sample or specific to your solution? If you can zip it up and send it, that may be helpful.

**Comment by rkm050288** [comment]
This is now resolved in my test windows server box after reinstalling with right node version
