### ISSUE TITLE
Luis generate src links in the CLI docs are broken

### ISSUE THREAD

**Issue by jbgh2** [microsoft/botframework-cli#633]
## Versions
Documentation bug on Github

## Describe the bug

The Luis generate source links on https://github.com/microsoft/botframework-cli/tree/master/packages/cli lead to 404

## To Reproduce
1. Click on Luis generate source code link on https://github.com/microsoft/botframework-cli/tree/master/packages/cli (ie https://github.com/microsoft/botframework-cli/tree/master/packages/lu/src/commands/luis/generate/cs.ts)
2. Note 404 page

## Expected behavior
Goes to source code for function

[bug]

**Comment by munozemilio** [comment]
Thanks for reporting this @jbgh2. We will fix in the next PR

**Comment by munozemilio** [comment]
Fixed by #646
