### ISSUE TITLE
dialog:merge always generate oneOf

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botframework-cli#635]
**Is your feature request related to a problem? Please describe.**
In order to make the composer easier, it would be good if the generated schema was a little more consistent.  @a-b-r-o-w-n  should chime in on priority.

**Describe the solution you'd like**
Switch to always generate oneOf if there is more than one type.  This means ["number", "string"] would become oneOf: [{type:"string"}, {"type": "number"}}.

[enhancement]

**Comment by a-b-r-o-w-n** [comment]
@tomlm and I had a discussion yesterday that alleviates this somewhat. The motivation here is that the `oneOf` form can be expanded easier, like adding a title, description, examples, etc for each type. It doesn't make much difference for editors like vs code, but Composer could leverage the additional information to provide a better experience to users.

**Comment by chrimc62** [comment]
@a-b-r-o-w-n do you still need this?

**Comment by chrimc62** [comment]
Not needed.
