### ISSUE TITLE
bf luis build command

### ISSUE THREAD

**Issue by csnarain** [microsoft/botframework-cli#645]
luis build not working in bf. Getting the following error:

Error: command luis:build not found

running bf version @microsoft/botframework-cli/4.7.0 win32-x64 node-v12.16.1

**Comment by munozemilio** [comment]
Hello @csnarain, sorry for the confusion, this is only available in the Nightly build

**Comment by chrimc62** [comment]
@munozemilio can you reply with more details and close this if appropriate?

**Comment by munozemilio** [comment]
@csnarain you can download the nightly build from [here](https://github.com/microsoft/botframework-cli#nightly-builds). Since we are preparing for the release the doc is showing the available commands one week in advance.
