### ISSUE TITLE
luis:build error messages do not work with imported files

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botframework-cli#647]
## Describe the bug
If you import an .lu file, error messages are with respect to the merged file--not specific to the imported files.  This makes it very difficult to debug issues.

## To Reproduce
1.Create an .lu file which imports another .lu file that has an error.
2. Run luis:build on the root .lu file

## Expected behavior
Error messages refer to source file and line number.

[bug]

**Comment by feich-ms** [comment]
Will take a fix soon.

**Comment by vishwacsena** [comment]
We should probably include additional information on the file being parsed in the exception itself. I suspect this needs to be done in the core parser and not in luis:build. @feich-ms can you send me info on the fix you intended to make?

**Comment by feich-ms** [comment]
Just did some investigations. The errors in imported files can be caught with line number correctly, however for import cases, the error message in lubuild is constructed as 'Invalid LU file ${root lu file path}:  ${error message with line number from imported lg file}'. I will try to put lu object id in thrown err in parseLuFile function of luMerger.js file. Here is the PR https://github.com/microsoft/botframework-cli/pull/659
