### ISSUE TITLE
Add integrate into dialog:generate

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botframework-cli#665]
Rather than a separate command make integration part of the dialog:generate command.  I think all we need to add is a --integrate switch.  Integration would then:
1) Generate a temp directory to do generation in.
2) Integrate that into the --out directory with feedback on verbose indicating:
* Kept old file X
* Replaced old file X
* modified old file X
* Old file X changed and new file X changed (only in the case where new file X checksum != old file X checksum)

[enhancement]

**Comment by coldplaying42** [comment]
If the integration is part of the dialog:generate, is the command like dialog:generate schema_name -o outputPath -d oldAssetPath --integrate ? The generated asset could be considered as the new asset, and it will be merged with the old asset to the output path?

I have a question on lg files merging:

if old lg file is :
#template1
- abc
#template2
- def

and new lg file is :
#template1
- hij
#template3
- opq

what is the merged lg file?
should it be:
#template1
- abc
#template2
- def
or
#template1
- abc
#template2
- def
#template3
- opq

**Comment by chrimc62** [comment]
This has been done in the experimental version.
