### ISSUE TITLE
luis:build expects authoringKey not subscriptionKey and config doesn't

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botframework-cli#666]
## Describe the bug
luis:build expects --authoringKey, but config:set:luis only defines --subscriptionKey.  Config should support --authoringKey and luis:build should use it.  

[bug]

**Comment by vishwacsena** [comment]
@scheyal - what is the final name for keys for LUIS? are we calling this authoringKey and endpointKey? It would be good to have everything align.

**Comment by chrimc62** [comment]
@clearab This is kind of a bad inconsistency that luis build uses a different name which is not available in config.  There is a distinction between subscription key and authoring key, but authoring key should be added to config and plumbed through where it is needed.

**Comment by feich-ms** [comment]
Will take a fix this week.

**Comment by feich-ms** [comment]
fix by this PR https://github.com/microsoft/botframework-cli/pull/731

**Comment by feich-ms** [comment]
fixed by PR #731
