### ISSUE TITLE
Enable a --version command for plugins

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-cli#667]
It would be nice if there was a --version command for plugins, so something like `bf dialog -v` would display the currently installed version of that plugin.

[enhancement]

**Comment by munozemilio** [comment]
Core plugins are part of the cli therefore the version is the same as the cli. For the installed plugins you can run bf plugins:list and the version will be displayed
```
>bf plugins:list
@microsoft/bf-dialog 4.9.0-preview.113245
```
