### ISSUE TITLE
qnamaker:kb:export command not exporting multi turn prompts

### ISSUE THREAD

**Issue by jiruss** [microsoft/botframework-cli#670]
## Versions
What CLI version are you using.
 @microsoft/botframework-cli/4.8.0-preview.100922 win32-x64 node-v12.14.1

What Nodejs version are you using
v12.14.1

What OS are you using
Windows 10.1909 Build 18363.657

## Describe the bug
bf  qnamaker:kb:export command does not export multi-turn prompts.

## To Reproduce
1. Run command on any QnAMaker KB that includes multi-turn prompts
2. Check output json file and you will notice that prompts are missing for Q&A pairs that include them.

## Expected behavior
Expect that prompts will be exported

[bug]

**Comment by vishwacsena** [comment]
@munozemilio  this is fixed in R8. Can you resolve this ticket once the packages are published to npm?
