### ISSUE TITLE
Align Luis json schema between BF-LU and LUIS API

### ISSUE THREAD

**Issue by feich-ms** [microsoft/botframework-cli#675]
**Is your feature request related to a problem? Please describe.**
The luis schema converted from lu content in bf-lu does not align with the one returned from Luis API which makes the comparison of local luis model and remote luis model very difficult. Lu build CLI depends on the comparison result to decide whether to repunlish the luis applicationto a new version or not. 

**Describe the solution you'd like**
Align the json schema between BF-LU and LUIS API

**Describe alternatives you've considered**
1. Change the Luis schema in bf-lu to align with the schema from API
2. Make some changes in luConverter.js to make sure luisToLuContent function can convert to the same lu content for local and remote luis json that from same original lu content

**Additional context**
I have found several disalignments such as

1. Schema disalignments: BF-LU <-> LUIS API
    - model_features <-> phraselists
    - regex_entities <-> regexEntities
    - regex_features <-> regexFeatures
    - the luis_schema_version returned from LUIS API is always 6.0.0 even though I set it to 3.2.0 when importing
2. Unexpected behaviors
    - The json returned from luis API always automatically add features defintion to each intent if there is a phraseList definition in lu file but not enabled for each intent
    - The json returned from luis API sometimes automatically set settings with NormalizeDiacritics: true even though nothing is set for this when importing
    - The json returned from luis API automatically set enabledForAllModels to be true even though it is not set when importing

To repro this issue, you can publish a lu file with bf luis:build and get the json from API with bf:version:export. You will find above disalignments.

[enhancement]

**Comment by vishwacsena** [comment]
PatternAny entities if in the source should be persisted to LU.
