### ISSUE TITLE
cross-train -> master

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botframework-cli#687]
Filing this ticket to get cross-train into master branch. 

Need detailed docs.

**Comment by feich-ms** [comment]
@vishwacsea. I have created a PR #690 here to bring cross-train cli into master. The README file is already in PR, but the spec is not ready.

**Comment by cleemullins** [comment]
from @vishwacsena:
> I have been working on this with Fei. We chatted even an hour ago about next steps on closing this.  We are in the last mile. Given where we are, I would hold off on the punt decision unless we are unable to land this by Friday. Data point for you and Emilio: it's not going to be done in 24 hours, but likely to land well before R9 code complete.

> I had chatted with Emilio about code review here. I signed up to do functional review. We will try to land it in the next day or two but if not, let's punt it out on Friday. Thanks!
