### ISSUE TITLE
bf luis:convert error

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botframework-cli#692]
## Versions
@microsoft/botframework-cli/4.9.0-preview.113642 win32-x64 node-v12.14.1

## Describe the bug
1. When I convert a .lu file(converted from a json file) back to .json file, I got an error. 
![image](https://user-images.githubusercontent.com/44257569/77907166-bc30ff80-72bb-11ea-9a13-03f37db0e458.png)

2. in following piece of lu file:
> ## Manager
> - who's {@Keyword={@Person's Name=clement}}'s manager?
> - who's {@Keyword={@Person's Name=peter}}'s manager?
> - you know who was the manager teacher for {@Keyword={@Person's Name=john}}
>
> @ intent Manager usesFeature Manager Helper
>
> > # Entity definitions
> @ ml Keyword
>    - @ ml Person's Name
>    - @ ml Topic
>    - @ ml Email Address
>
> > # Phrase list definitions
> @ phraselist Manager Helper(interchangeable) = 
>    - manages,report to,manager,reports to

BF luis:covnert reports following errors:
1. entity name "Person's Name" cannot be recognized. Change to PersonName then it passed. same as the entity name "Email Address".
2. phraselist name "Manager Helper" cannot be recognized
3. @ intent Manager report error if there is no usesFeature followed (#696)

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by vishwacsena** [comment]
@xhr0804 the issue is with defining entities and lists with spaces in them. In general you need to wrap these with quotes.

```
## Manager
- who's {@Keyword={@PersonsName=clement}}'s manager?
- who's {@Keyword={@PersonsName=peter}}'s manager?
- you know who was the manager teacher for {@Keyword={@PersonsName=john}}

@ intent Manager usesFeature ManagerHelper

> # Entity definitions
@ ml Keyword
   - @ ml PersonsName
   - @ ml Topic
   - @ ml EmailAddress
> > # Phrase list definitions
@ phraselist ManagerHelper(interchangeable) = 
   - manages,report to,manager,reports to

```
