### ISSUE TITLE
BF CLI luis:application:publish --direct flag does not work

### ISSUE THREAD

**Issue by AndyCW** [microsoft/botframework-cli#693]
## Versions
What CLI version are you using:  **@microsoft/botframework-cli/4.9.0-preview.114058 win32-x64 node-v12.16.1** (from daily builds)
What Nodejs version are you using: **v12.16.1**
What command-line interpreters are you using: **Powershell** and **bash**
What OS are you using: **Windcows 10** and **Ubuntu**

## Describe the bug
The **bf luis:application:publish** command includes a flag **--direct** which, when defined, is meant to publish the specified version directly, rather than to the Staging or Production slots. This flag is ignored - if you issue this command, the response indicates that the version has *not* been direct published, and instaed ahas been published to **Production**. This is confirmed by viewing the version on the portal.

## To Reproduce
1. Create an app and a version.
2. Train the version.
3. At the command line, issue this command:
```
bf luis:application:publish --direct  --appId=c959c317-4885-486d-a5ac-9678xxxxxxxx --endpoint https://luisdevopsresource-authoringtest.cognitiveservices.azure.com/ --subscriptionKey 16f6ee4329ca4e19a4f9a213xxxxxxxx --versionId 0.2
```
4. The response comes back:
```
{
  "versionId": "0.2",
  "isStaging": false,
  "endpointUrl": "https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/c959c317-4885-486d-a5ac-9678xxxxxxxx",
  "region": "westus",
  "assignedEndpointKey": null,
  "endpointRegion": "westus",
  "failedRegions": "",
  "publishedDateTime": "2020-03-30T17:27:30Z",
  "directVersionPublish": false
}
```

## Expected behavior
If you call the REST API directly with Curl, it works and the version is direct version published. This is the behavior I expect.

## Additional context

[bug]

**Comment by munozemilio** [comment]
Hi @AndyCW, could you please share the http post you are running with curl?
