### ISSUE TITLE
bf luis:generate:cs generate entity type in C# code not match with the luis predicted result

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botframework-cli#699]
## Versions
@microsoft/botframework-cli/4.9.0-preview.113642 win32-x64 node-v12.14.1

## Describe the bug
I have a luis model in schema 6.0.0, I use bf luis:convert to convert it to .json, and then use bf 
luis:generate:cs to generate a C# source code.
But when I use a luis recognizer to recognize a query from luis service, I get an error.
Seems it is because the "genre" field in C# source code is string[]
![image](https://user-images.githubusercontent.com/44257569/78327683-12e65400-75b0-11ea-8ea8-21df43b1fb94.png)
but the luis predicted result is "genre":[["genre_list"]]
![image](https://user-images.githubusercontent.com/44257569/78327619-e3cfe280-75af-11ea-8273-d9f53dbf6678.png)

After I change the string[] to string[][] manually, it is resolved.

## To Reproduce
1. Use this .lu file

```
> LUIS application information
> !# @app.name = MusicSkill
> !# @app.versionId = 0.1
> !# @app.culture = en-us
> !# @app.luis_schema_version = 6.0.0


> # Intent definitions

## PlayMusic
- {@MusicParent={@beforeMusic=play} {@music=adeles} {@afterMusic=latest album}}
- {@MusicParent={@beforeMusic=play} {@music=prince}}
- {@MusicParent={@beforeMusic=play} {@genre=schlager}}
- {@MusicParent={@beforeMusic=can you play} {@inBetweenMusic=rihanna} {@afterMusic=please?}}
- {@MusicParent={@beforeMusic=can you play} {@genre=boi}
- {@MusicParent={@beforeMusic=can you play} {@music=crazy beautiful}}

> # Entity definitions

@ ml MusicParent 
    - @ ml beforeMusic
    - @ ml afterMusic
    - @ ml music
    - @ ml inBetweenMusic
    - @ GenreList genre


> # PREBUILT Entity definitions

> # Phrase list definitions

> # List entities

@ list GenreList = 
	- genre_list :
		- schlager
		- deathrash metal
		- boi
		- drill music



> # RegEx entities


```

2. use bf luis:convert to convert it to .json
3. use bf luis:generate:cs to get a C# resource code, named as "MusicSkillLuis"
4. use a luis recognizer to recognize the luis result from the luis service.
`luisrecognizer.RecognizeAsync<MusicSkillLuis>`

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by axelsrz** [comment]
Thanks @xhr0804 for submitting this issue, we will triage a potential fix for next release
