### ISSUE TITLE
luis:application:assignazureaccount does not invoke LUIS API as expected

### ISSUE THREAD

**Issue by peterinnesmsft** [microsoft/botframework-cli#712]
## Versions
What CLI version are you using: @microsoft/botframework-cli@4.9.0-preview.119971
What Nodejs version are you using: v12.16.1
What command-line interpreters are you using: luis:application:assignazureaccount
What OS are you using: Windows 10 Enterprise, Version 1909, OS build 18363.778

## Describe the bug
As part of running the deploy.ps1 script for Virtual Assistant, a LUIS account is expected to be assigned to corresponding Dispatch and General LUIS applications using luis:application:assignazureaccount. Running the command indicates that the account is successfully assigned, but when attempting to talk to my VA using the Emulator, LUIS returns an HTTP 403.

It was discovered that manually assigning the account via the LUIS portal to the application addresses this issue. Having looked at Fiddler while running the deploy.ps1 script, it appears that no outgoing call was being made to the LUIS API to do the account assignment.

## To Reproduce
1. Install AZ CLI version 2.3.1, BF CLI version 4.9.0-preview.119971, and Virtual Assistant VSIX version 4.8.0.0.
2. Create a new Virtual Assistant in Visual Studio using the VA VSIX template.
3. Deploy the VA using the deploy.ps1 script to Azure subscription of your choosing.
4. Upon completion of the deployment, run the VA locally and connect using the BF Emulator.
5. Send a message to the bot in response to the greeting prompt.

## Expected behavior
The bot should invoke a successful call to the Dispatch LUIS application to derive intent and entities from the user input and respond accordingly.

## Screenshots
<img width="1040" alt="Emulator" src="https://user-images.githubusercontent.com/53846082/79394397-37d1b400-7f2c-11ea-89e4-0578c60eeafe.png">

## Additional context
None.

[bug]

**Comment by peterinnesmsft** [comment]
Please see additional investigation details, including deploy.ps1 log output, console output, Fiddler trace, and Application Insights logs from VA showing the HTTP 403 to LUIS: [AdditionalDetails.zip](https://github.com/microsoft/botframework-cli/files/4483990/AdditionalDetails.zip)

**Comment by munozemilio** [comment]
Hello @peterinnesmsft, it works for me using the cli. Does the command work for you in the terminal? Can you point me to the script? Im more than happy to set a meeting with you and go over those details.

**Comment by peterinnesmsft** [comment]
Hi @munozemilio. I'm running currently from a PowerShell 7 terminal. I was unable to observe an outgoing HTTP call over Fiddler either when running the command manually, or when being invoked as part of our deployment script.

Were you able to attempt a repro using the steps I listed above? The entry script is our [deploy.ps1](https://github.com/microsoft/botframework-solutions/blob/next/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/deploy.ps1) that comes out of the box with the Virtual Assistant template. The specific lines which are invoking the CLI command in question are in deploy_cognitive_models.ps1, lines [203 -210](https://github.com/microsoft/botframework-solutions/blob/edf0c1a8950980d2ba8e7605bbae71bbd0a7a000/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/deploy_cognitive_models.ps1#L203-L210) and [341 - 348](https://github.com/microsoft/botframework-solutions/blob/edf0c1a8950980d2ba8e7605bbae71bbd0a7a000/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/deploy_cognitive_models.ps1#L341-L348).

If you can spot anything obvious with the way that we are invoking the command, do let me know. I have double-checked the --help for the command and believe we are passing in all of the correct values. Happy to set up some time to dig in deeper.

**Comment by sgellock** [comment]
@peterinnesmsft my Win10 box runs PS v5.  does this work on downlevel version of PS?

**Comment by peterinnesmsft** [comment]
@sgellock the deploy.ps1 script has a '#Requires -Version 6' annotation, which will prevent it running in PS5 or older. However, having looked over the actual code in the scripts themselves, I think it should work with older versions.

If you remove that tag from the .ps1 files in the Scripts directory, you may be able to try running it successfully from PS5.

**Comment by munozemilio** [comment]
@peterinnesmsft and I spent some time and we discovered the wrong keys were used to create the resources. Closing this issue
