### ISSUE TITLE
cross-train: The cross-train config doesn't support multiple intent triggers -> 1 dialog

### ISSUE THREAD

**Issue by lei9444** [microsoft/botframework-cli#713]
## Describe the bug
Give a clear and concise description of what the bug is.

Example
Main.dialog has 2 triggers
OnIntent(Name=IntentA) in this trigger, started a dialog called DialogA
OnIntent(Name=IntentB) in this trigger, started a dialog called DialogA

so the config should be like: 
`
        'main.lu': {
          'dialogA.lu': ['IntentA', 'IntentB']
        },
`

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by feich-ms** [comment]
close this issue since the fix is merged and verified.
