### ISSUE TITLE
[DCR] bf dialog:merge should replace --branch with --url

### ISSUE THREAD

**Issue by tomlm** [microsoft/botframework-cli#715]
bf dialog:merge has -branch to define the component.schema to use 

We should change this to be a url, which gives us flexibility to decide where the component.schema lives including versioning.  

This is to enable us to move component schema to Microsoft/botframework hub repo as releases.

[enhancement]

**Comment by clearab** [comment]
@chrimc62 Is this something you've planned to do in the R9 release?

**Comment by chrimc62** [comment]
Actually we decided to drop branch.
