### ISSUE TITLE
bf dialog:merge colors are bad

### ISSUE THREAD

**Issue by tomlm** [microsoft/botframework-cli#717]
When using bf dialog:merge
* error color is DARK red which is very hard to see with dark background of a shell.
* warning color is SAME dark red which is very hard to see AND doesn't communicate that it's a warning.

Expected:
* high contrast red for errors
* high contrast yellow for warnings

![image](https://user-images.githubusercontent.com/17789481/79523219-7b9ee900-8012-11ea-9542-cf7dd9499df2.png)

**Comment by chrimc62** [comment]
This is set for bf as a whole and they are red/yellow and look OK to me.
![image](https://user-images.githubusercontent.com/17637681/80846548-779dca00-8bc1-11ea-9c63-8abbe49e7cf7.png)
