### ISSUE TITLE
bf dialog:merge glob patterns don't work on ubuntu.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botframework-cli#721]
## Versions
```
bf --version
@microsoft/botframework-cli/4.9.0-preview.121045 linux-x64 node-v12.16.1
```

## Describe the bug
in dotnet repo I run bf dialog:merge to create tests.schema file in tests folder.
The command I run is
```
bf dialog:merge ../libraries/**/*.schema ./**/*.schema -b "" -o tests.schema -b  ""
```
On windows this merges all of the sdk libraries schema files and test schemas from testbotjson.
On linux the tests.schema has the schema from libraries but NOT the test schemas from testbotjson.

Specifically, TestBotJson/CustomSteps/TestBot.Multiply.schema is not included in the output.
on windows it is. 

other things I have tried (from the tests folder)
```
../**/*.schema --> Works (merges Multply.schema)
../libraries/**/*.schema ../tests/**/*.schema  -> does not work
../tests/**/*.schema ../libraries/**/*.schema  -> does not work
../libraries/**/*.schema ./**/*.schema  -> does not work
**/*.schema -> does not work
```

[bug]

**Comment by chrimc62** [comment]
Should be fixed by #737
