### ISSUE TITLE
bf dialog:merge doesn't have way to get version

### ISSUE THREAD

**Issue by tomlm** [microsoft/botframework-cli#724]
## Versions
can't say.

## Describe the bug
Bug report asks for version, but I can't give it to you.

## To Reproduce
bf dialog:merge

## Expected behavior
To have plugin version information displayed.

## Screenshots
![image](https://user-images.githubusercontent.com/17789481/79896281-08ec8f80-83bd-11ea-8e18-124a25e3fbfc.png)

## Additional context

[bug]

**Comment by chrimc62** [comment]
If part of bf, then bf --version does it.  Otherwise the standard way to do it is bf plugins:list which will show the version like this: 
```
C:\Users\chrim\source\repos\botbuilder-dotnet\tests\Microsoft.Bot.Builder.TestBot.Json>bf plugins:list
@microsoft/bf-dialog 4.9.0-preview.127410
```
