### ISSUE TITLE
bf dialog:merge doesn't display help when there are no arguments

### ISSUE THREAD

**Issue by tomlm** [microsoft/botframework-cli#725]
## Versions
can't say

## Describe the bug
bf dialog:merge gives error instead of displaying help as default

## To Reproduce
bf dialog:merge

## Expected behavior
To display help

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/79896428-35a0a700-83bd-11ea-8a46-897c32d4c010.png)

## Additional context

[bug]

**Comment by chrimc62** [comment]
Should be fixed by #737
