### ISSUE TITLE
Error publishing BOT using Bot framework SDK

### ISSUE THREAD

**Issue by manvendrautralia** [microsoft/botframework-cli#727]
The error I get is as below:

The MSBuild project 'C:\Users\Mutralia\Documents\Composer\CAMPUSsearch\BotProject.csproj' has already been initialized with a UserSecretsId.
0
1
Unknown error during execution. Please file an issue on https://github.com/microsoft/botframework-cli/issues
Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.
lubuild succeeded
Getting Luis accounts...
Return invalid status code while gettings luis accounts: 401, error message: StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  apim-request-id: 8e394e88-2fb3-4df3-b36d-959cfbea23d5
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  Date: Wed, 22 Apr 2020 16:15:00 GMT
  Content-Length: 161
  Content-Type: application/json
}

**Comment by tonyanziano** [comment]
@Kaiqb can you please delegate this to support?

**Comment by mdrichardson** [comment]
@manvendrautralia What command are you running to generate that? The error states:

> Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.

Are you using the correct subscription key and enpoint?

**Comment by manvendrautralia** [comment]
The deployment worked for me. Looks like there is a @bug in "Bot Framework Composer". The configuration settings at UI does not get reflected in app settings. I modified manually and it worked. 
Now I am facing another issue. While I get welcome message on testing, on sending input to bot receiving the following error:- "Response status code does not indicate success: 401 (PermissionDenied)."

Could you please help.

**Comment by mdrichardson** [comment]
@manvendrautralia I'm still not clear on what steps you're taking to generate this error. Please describe steps to reproduce it so that I can troubleshoot on my end.

**Comment by manvendrautralia** [comment]
@mdrichardson Followed the steps as mentioned in the documentation here "https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp".

**Comment by mdrichardson** [comment]
@manvendrautralia I am unable to reproduce this error. Which steps are you getting each error on? Please give me as much context as possible so that I can troubleshoot this.

**Comment by mdrichardson** [comment]
@manvendrautralia Are you still receiving this error?

**Comment by manvendrautralia** [comment]
> @manvendrautralia Are you still receiving this error?

I was able to resolve the issue my manually modifying the app settings.json file. You may please close the ticket. Thanks.

**Comment by manvendrautralia** [comment]
> @manvendrautralia Are you still receiving this error?

I was able to resolve the issue my manually modifying the app settings.json file. Closing the ticket. You may please mark as resolved. Thanks.
