### ISSUE TITLE
Feature gaps with cross-train

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botframework-cli#736]
Filing this as raw gaps with the current cross-train solution as a backlog item.

- .qna needs to be in the same location as .lu
- Do not include patterns in cross-train
- Cross-train does not copy over import references. May be the output should be fully resolved references. 
- Need to test cross-train with import references in utterances. Cross-train after imports are resolved.
- Need —force argument for cross-train
- Need a —log flag for cross-train

luis:build - verify imports are resolved before change detection.

**Comment by vishwacsena** [comment]
@feich-ms can you comment which of these if any have already been addressed?

**Comment by feich-ms** [comment]
@vishwacsena 

- .qna needs to be in the same location as .lu
**Not touched, if we want them to be in different location, we need to adjust the cross-train config to add the qna files mapping rules, it that ok?**
- Do not include patterns in cross-train
**Addressed. Currently only patterns with prebuilt entity are removed in cross-trained _interruption intent. Do we need to remove all patterns in _Interruption intent?**
- Cross-train does not copy over import references. May be the output should be fully resolved references. 
**Resolved**
- Need to test cross-train with import references in utterances. Cross-train after imports are resolved. 
**Not tested. Will try today.**
- Need —force argument for cross-train 
**What is --force used for? We already force overwrite existing files now I think. Do you mean clear the folder and rewrite?**
- Need a —log flag for cross-train 
**print more log messages to console like what we do in luis:build?**

luis:build - verify imports are resolved before change detection.
**Resolved**

**Comment by vishwacsena** [comment]
- By default do not overwrite. Consistent with luis:convert etc. If foo.lu exists then without `--force` we will write foo(1).lu. When `--force` is specified, we will overwrite.
- `--log` is to find parsing errors with a specific file.
