### ISSUE TITLE
qnamaker:build update non-empty kb with replace api failed for multi turn qna content

### ISSUE THREAD

**Issue by feich-ms** [microsoft/botframework-cli#766]
## Versions
What CLI version are you using.
What Nodejs version are you using
What command-line interpreters are you using
What OS are you using

## Describe the bug
The multi turn contents in qna file failed to update when replacing an existing non-empty kb with qnamaker:build command

## To Reproduce
1. Publish a valid qna file with qnamker:build
2. Add multi turn QA pairs to above qna file
3. Use qnamaker:build to update the kb
4. Go to https://www.qnamaker.ai/ to see you published kb. You will see multi turn prompts are not there.

## Expected behavior
Multi turn prompts should be published successfully.

## Additional context
This may be caused by some unexpected bug in QnA replace API https://docs.microsoft.com/en-us/rest/api/cognitiveservices/qnamaker/knowledgebase/replace.

[bug]

**Comment by feich-ms** [comment]
I tried many workaround solutions, such as replacing the kb with empty QA pairs first and then replacing with multi turn content or deleting kb pairs with update API first and then replacing with multi turn content. Unluckily no one works. I would prefer assigning this bug to QnA maker team to triage @vishwacsena

**Comment by feich-ms** [comment]
I think I found the root case. Replace API is doing something like delete and add. It is deleting existing KB pairs and add new ones. When it's adding, the ids of the newly added kb pairs will start from last deleted id + 1 instead of 1. For example, the orginal ids are 1, 2, 3, when doing replacing, the newly added kb pairs will start from 4, 5, 6 ....  In such case, the multi turn prompt ids will not work because it's still working from 1. The optional fix either from QnA maker API which means replacing api will make ids of repalced kb pairs count from 1 to n or we do some hacky changes here to get the last id of exising kb pairs and add them to the prompt ids of our multi turn content. I would prefer option 1. Please help to include QnA team if possible to see if we have other alternatives.

**Comment by vishwacsena** [comment]
@pchoudhari @vipeketi can you please comment? is it a bug that we are auto-incrementing IDs of QnA pairs on replace? For .qna content, we construct IDs to make sure multi-turn content is preserved but that is being over-written which results in lossy replace operation where multi-turn content associations are lost.

**Comment by vipeketi** [comment]
@vishwacsena It is not a bug at QnAMaker.

**Comment by vishwacsena** [comment]
I took a closer look at this..
@feich-ms, it looks like replace API does the right thing when you post JSON and not .qna directly (due to issue below). I just tested the replace API by posting JSON w/ multi-turn content and it worked. Can you try updating qnamaker:build to call BF-LU and do QnA JSON conversion and post the JSON instead of .qna file? That is until the QnA team have been able to investigate why .qna with multi-turn fails. I suspect it is because of missing ID. If this still is not an issue on QnA side, then we can continue to just post JSON.

@vipeketi it looks like we do not support auto-ID generation when importing .qna documents. This is supported today by the BF-LU library. To validate that, can you help provide an update on why this .qna does not work with replace API? Specifically multi-turn prompts are lost when I post this w/ `qnaFormat=true` to replace API.

```markdown
# ?leaf question 1
```
    leaf-answer
```

# ?leaf question 2
```
    leaf-answer
```

# ?root question 1
```
    root-answer
```
**Prompts:**
- [child1](#leaf-question-1)
- [child2](#leaf-question-2)
```

**Comment by vipeketi** [comment]
@vishwacsena  we support following format of .qna . The text provided above looks like old version of .qna format.
> # QnA pairs

<a id =  "1"></a>

> !# @qna.pair.source = Editorial source

## ? ques1
- question 2 data
- question 3 data

**Filters:**
- fk1_name = fk1 value is here
- fk2name = fk2 value is here
- fk3_name = fkk3 vaue is very big

```markdown
ans1 line\nans line 2
ans line 3
```

**Prompts:**
- [p1](#2) `context-only`
<a id = " 2">  </a>

> !# @qna.pair.source = Editorial

## ? p1

```markdown
ap1
```

**Comment by vishwacsena** [comment]
Thanks @vipeketi. @feich-ms can you prep a fix that does this - for qnamaker:build do QnA -> JSON on the client and then post up JSON directly for replace operations. 

for qnamaker:kb:replace, if --qnaFormat is set, then do QnA -> JSON on the client and post up JSON directly to service for replace operation. Let's not post .qna format directly to the service and just use JSON.

**Comment by feich-ms** [comment]
sure, will take a fix.

**Comment by feich-ms** [comment]
Fixed in this PR https://github.com/microsoft/botframework-cli/pull/786
