### ISSUE TITLE
bf luis:generate produces both Pattern.Any and List type Entity in csharp output which fails to compile 

### ISSUE THREAD

**Issue by dawwa** [microsoft/botframework-cli#788]
## Versions
* @microsoft/botframework-cli/4.8.0 win32-x64 node-v12.16.3
* bf luis:generate
* Windows 10

## Describe the bug
bf luis:generate produces both Pattern.Any and List type Entity in csharp output which fails to compile.

## To Reproduce
1. Create a sub lu file and name it as listEntities.lumodule and declare a List type Entity in it, e.g,
```
$StockSymbol:MSFT=
- Microsoft
$StockSymbol:APPL=
- Apple
```
2. Create a root lu file and name it as test.lu and starting with a line of "[List Entity Definitions](./listEntities.lumodule)” to reference the sub lumodule file and create an utterance with pattern, e.g.,
```
[List Entity Definitions](./listEntities.lumodule)
## Test.Symbol
- Test {StockSymbol}
```
4. run bf luis:generate to generate csharp model for the test.lu 

## Actual behavior
StockSymbol is generated as both List and Pattern.Any, which does not compile, e.g.,
```csharp
// Lists
public string[][] StockSymbol;

// Pattern.Any
public string[] StockSymbol;
```

## Expected behavior
StockSymbol is generated as List, e.g.,
```csharp
public string[][] StockSymbol
```

**Comment by dawwa** [comment]
@axelsrz ,  looks like handling sub-files has problems on multiple scenarios, as including phase list in a separate file also encounters this error below.

[ERROR] line 5:0 - line 5:60: Features must be defined before assigned to an intent. No definition found for feature "testPhraseList_pl" in usesFeature definition for intent "Test.Symbol"

**Comment by axelsrz** [comment]
Hello @dawwa thank you for filing this issue. From the description of your problem we would have to investigate if the bug is in the step to convert the .lu model to a json representation (luisgen works directly over .json) or luisgen itself.

We'll look into this issue in our next releasing cycle.

**Comment by dawwa** [comment]
@axelsrz , agreed, this could be due to that user is trying to include a List Entity in a wrong way, as the doc below mentioned how to appropriately use a List Entity in the utterance, which made me think I was using a wrong syntax for my intention. : )

> When using list entity, you should include a value from the list directly in the utterance, not an entity label or any other value. Here's an example definition of a list entity

https://github.com/microsoft/botbuilder-tools/blob/master/packages/Ludown/docs/lu-file-format.md#list-entity

**Comment by axelsrz** [comment]
Hello @dawwa, could you confirm this was due to a misuse of the tool and not an actual bug?


Thanks.

**Comment by dawwa** [comment]
yep, consider this is a syntax violation and address this by erroring out rather than rendering code that could not compile.
