### ISSUE TITLE
luis:build error messages missing context

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botframework-cli#794]
## Versions
@microsoft/botframework-cli/4.10.0-preview.130904 win32-x64 node-v12.16.1

## Describe the bug
An lu file with something like:
- {@AddTo$Pproperty=foo} 

Will generate an error message like: 
```
Intent and entity name cannot contain any of the following characters: [<, >, *, %, &, :, \, $]
```
There is no name or line/character number so you cannot tell the issue from the error message.  I've seen other error messages that are also missing any context.

[bug]

**Comment by feich-ms** [comment]
Close this specific issue first by this PR. We can continue optimizations if more come.
