### ISSUE TITLE
Re-do luis prediction options after SDK bug fixed

### ISSUE THREAD

**Issue by feich-ms** [microsoft/botframework-cli#805]
**Is your feature request related to a problem? Please describe.**
https://github.com/microsoft/BotFramework-Composer/issues/2545

**Describe the solution you'd like**
Re-do luis:prediction options after SDK bug for supporting expressions in prediction options is fixed

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by feich-ms** [comment]
@luhan2017 is the SDK bug fixed for luis prediction options?

**Comment by feich-ms** [comment]
Depending on SDK bug fixes, if that is fixed, we will pick this one.

**Comment by feich-ms** [comment]
This ticket is to resolve issue here https://github.com/microsoft/BotFramework-Composer/issues/2545 and it was ever resolved by this PR https://github.com/microsoft/botframework-cli/pull/709. But there are some bugs in SDK that makes the predictOptions cannot be loaded by SDK runtime, so we reverted the changes in bf-cli to unblock the release of SDK. Now we are planning to bring them back if needed, but it depends on the bug fix in SDK side. @vishwacsena, could you include Tom and Chris to clarify when and how the SDK issue should be fixed since @luhan2017 may not get full background about the discussions between Tom and Chris.

**Comment by feich-ms** [comment]
@tomlm, could you please clarify when and how the SDK issue should be fixed to resolve the predictionOptions loading bug in SDK side? Luis build is depending on the bug fix to bring back the predictionOptions in generated dialog files.

**Comment by feich-ms** [comment]
@vishwacsena any feedback for this issue?

**Comment by vishwacsena** [comment]
@feich-ms microsoft/botbuilder-dotnet#4149 is assigned to @tomlm. we discussed it in triage and he took point to fix it for R10. Hope that helps.

**Comment by feich-ms** [comment]
Blocking by microsoft/botbuilder-dotnet#4149. Once it's fixed, I will take changes in bf-cli side.

**Comment by feich-ms** [comment]
Since microsoft/botbuilder-dotnet#4149 removed R10 tag, I will remove R10 tag for this one first. Please add back R10 tag if it is.

**Comment by feich-ms** [comment]
We moved the dialog generation code pieces to composer, so the luis prediction options are supposed to be added from composer side instead of cli side. Based on this, this item is not necessary now, so close it.
