### ISSUE TITLE
bf luis:version:list Unknown error during execution - Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by dawwa** [microsoft/botframework-cli#815]
## Versions
- @microsoft/botframework-cli@4.10.0-preview.132916 (repros to both nightly and official build)
- Node 10.20.1
- PowerShellCore 6.2.2
- Azure CLI 2.2.0
- Linux 18.04 ubuntu

## Describe the bug
bf luis:version:list command throws unknown error, but not repro locally so the input is fine, considering the environment is a deployment VM,  it might be easier to print out some debug log to help uncover what could be null/undefined behind the message, please ping me for peer debugging.

`Unknown error during execution. Please file an issue on https://github.com/microsoft/botframework-cli/issues`

**Comment by munozemilio** [comment]
Hi @dawwa, as per conversation over teams...please try with this build to log the error:
npm i -g @microsoft/botframework-cli@4.10.0-preview.133034

**Comment by dawwa** [comment]
@munozemilio, here is the new error
2020-05-22 00:26:43.998735: Cannot convert undefined or null to object
2020-05-22 00:26:43.998900: **TypeError**: Cannot convert undefined or null to object

**Comment by gabog** [comment]
Added the ExemptFromDailyDRIReport because @dawwa is MS internal but doesn't have his ID linked to the MS org. Emilio is talking to him offline.

**Comment by munozemilio** [comment]
The issue was an invalid config file was manually added to bypass telemetry. This got fixed by setting the proper environment variables
