### ISSUE TITLE
bf luis:convert from json to lu prebuilt intent inheritance invalid

### ISSUE THREAD

**Issue by joe-tossell-mando** [microsoft/botframework-cli#818]
## Versions
@microsoft/botframework-cli/4.9.0 win32-x64 node-v12.13.1
Powershell

## Describe the bug
Converting json version export to LUDown with prebuilt intent incorrectly formats the @intent.inherits information.
Compare:
> !# @intent.inherits = name : Utilities.Cancel
with 
> !# @intent.inherits = name : Utilities.Cancel; domain_name : Utilities; model_name : Cancel
which comes from the "Export as LU" option in the LUIS portal.

## To Reproduce
1. Create LUIS application containing prebuilt intent
2. Run bf luis:version:export and output to file... i.e. test.json
3. Run bf luis:convert --in .\test.json --out test.lu
4. Inspect intent.inherits information
5. Run bf luis:convert --out .\test2.json --in test.lu
6. Observer error:
[WARN]: Invalid intent inherits information found. Skipping "> !# @intent.inherits = name : Utilities.Cancel"
7. Attempt to import resulting JSON using bf luis:version:import
8. Failed to import app version: Error: The model name { Utilities.Cancel } are reserved.
9. Compare LU from portal to converted LU

## Expected behavior
Correct inheritance information stored in LU down file

[bug]

**Comment by vishwacsena** [comment]
Investigating.

**Comment by joe-tossell-mando** [comment]
Thanks for the update, what's the best way of accessing the fix for an in-flight project?

**Comment by vishwacsena** [comment]
@munozemilio did we end up taking a fix for this in 4.9.1? If not, can you share an ETA?

**Comment by munozemilio** [comment]
Hi @joe-tossell-mando this will be available in production for our next release(Aug 17) or in our preview feed once the PR is merged (Ill work on that tomorrow).

You can find the instructions to download the preview feed [here](https://github.com/microsoft/botframework-cli#nightly-builds).

Let me know if that works for you
