### ISSUE TITLE
bf luis:application:query does not honor --verbose flag

### ISSUE THREAD

**Issue by EvilJohn** [microsoft/botframework-cli#834]
## Versions
What CLI version are you using.
@microsoft/botframework-cli/4.9.1 linux-x64 node-v12.16.2

What Nodejs version are you using
v12.16.2

What command-line interpreters are you using
bf luis under zsh

What OS are you using
Windows 10 WSL2 - Ubuntu 18.04

## Describe the bug
Give a clear and concise description of what the bug is.
When using the bf cli command luis:application:query the --verbose flag does not return all intents

## To Reproduce
1. Create an app with multiple intents
2. query application with "bf luis:application:query"

## Expected behavior
Return all intents, like the legacy luis command.

[bug]

**Comment by munozemilio** [comment]
Thanks for reporting this @EvilJohn, this will be addressed in the current release cycle and will be available in the nightly build as soon as the issue gets closed.
