### ISSUE TITLE
luis:build does not combine ml children

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botframework-cli#835]
For list entities, the definitions across files are combined.  For ML definitions, the last definition wins.

file1:
@ml foo
- @number number

file2:
@ml foo
- @personName personName

Produces:
@ml foo
- @personName personName

My preference would be to do the same combination as we do for lists, i.e.
@ml foo
- @number number
- @personName personName

Alternatively, this should generate an error.

[enhancement]

**Comment by vishwacsena** [comment]
This was added in 4.9.1.
