### ISSUE TITLE
luis:build does not correctly handle child labels with prebuilt name

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botframework-cli#842]
## Versions
4.10.0-preview.136002

## Describe the bug
A model like:
@ prebuilt number
@ ml foo
- @number number
Does not allow a label like:
- {@foo={@number=3}}

This worked in version 4.10.0-preview.135338

[bug]

**Comment by vishwacsena** [comment]
Fixed in the latest bf-cli package. This actually did not require a product fix but invalid packages were being pushed up to nightly. Try `4.10.0-preview.136099`

https://botbuilder.myget.org/feed/botframework-cli/package/npm/@microsoft/botframework-cli
