### ISSUE TITLE
bf luis:version:export output error, which causes bf luis:generate:cs to fail

### ISSUE THREAD

**Issue by manish-95** [microsoft/botframework-cli#848]
## Versions
@microsoft/botframework-cli/4.9.1 win32-x64 node-v12.13.1

## Describe the bug
The output json file generated by **bf luis:version:export** differs slightly from the json file downloaded from the LUIS Portal. This causes the **bf luis:generate:cs** command to fail with the error "Invalid LUIS JSON file content" while used with the output generated by the export command, but succeed with the .json file from LUIS portal. Screenshots attached below, showing these differences.

## To Reproduce
1. Export .json file using bf luis:version:export
2. Export same .json file from luis.ai portal
3. Run the bf luis:generate:cs command using both files as input
4. Note the error in the case of the file generated with bf tool.

## Expected behavior
The .cs Helper file must be produced irrespective of the source of the input json file.

## Screenshots
![image](https://user-images.githubusercontent.com/29098159/84141441-d1bb6600-aa70-11ea-90fa-4608f8dac79c.png)
The file on the left is generated from bf, the file on the right is downloaded from the LUIS portal. Note the differences for regex features and regex entities, which is causing the failure of the bf generate command.

**Comment by vishwacsena** [comment]
@axelsrz can you take a look and comment?

**Comment by manish-95** [comment]
Hi @axelsrz . Any updates or timeline regarding this issue? Would be great to get a quick update, if any on this. Thank you.

**Comment by axelsrz** [comment]
@vishwacsena is this really a luisgen issue or a luis:version:export? I was not aware that the names of those properties where camelcase/snakecase interchangegable

**Comment by vishwacsena** [comment]
@axelsrz yes. bf-lu accomodates for casing because the exported json is different via the LUIS SDK .vs. portal. I chatted with @munozemilio about this prior to 4.9 patch release and he said he is going to make a change to remove dependency on the LUIS SDK..

**Comment by axelsrz** [comment]
> @axelsrz yes. bf-lu accomodates for casing because the exported json is different via the LUIS SDK .vs. portal. I chatted with @munozemilio about this prior to 4.9 patch release and he said he is going to make a change to remove dependency on the LUIS SDK..

Got it, will start working on this.
