### ISSUE TITLE
[MCS-DE-GO] -- allow configuring the LUIS slot on lubuild.Builder publish application

### ISSUE THREAD

**Issue by joaollq** [microsoft/botframework-cli#855]
When using the luBuilder it would be important to be able to set the slot where the LUIS model is published. Currently it is hardcoded to the production slot. 
Source file: lubuild/core.js  method: publishApplication

 `this.client.apps.publish(appId, {
            versionId,
            isStaging: false
        });`

In our MCS project with Gothaer the customer wants to share a LUIS instance for the DEV and TEST environments by setting the staging slot for DEV and production slot for TEST, hence it is paramount that we are able to publish the .lu files for both slots.

As a workaround we can make a copy of the repo and implement that change in the .ts files, however that is far from an ideal solution as we would lose the ability to easily retrieve the newest updates.

This parameter should be set in the lubuild.Builder build method as this is the one being used by the BF Composer process

@benbrown @goergenj @sgellock

**Comment by feich-ms** [comment]
fixed in this PR https://github.com/microsoft/botframework-cli/pull/898
