### ISSUE TITLE
bf luis:version:export result not compatible for bf luis:version:import

### ISSUE THREAD

**Issue by felixvanleeuwen** [microsoft/botframework-cli#863]
## Versions
What CLI version are you using.
4.9.1
What Nodejs version are you using
10.16.1
What command-line interpreters are you using
Powershell 6
What OS are you using
Windows 10

## Describe the bug
When using the CLI to export a version I get a result with a "regexEntities" field. When I go to the luis portal and export the version this property does not exist. What exists instead is a "regex_entities" property.

## To Reproduce
0. Make sure you have a Regex Entity on the model you try this on.
1. Run 
```
bf luis:version:export --force `
                --out $tempJsonPath `
                --appId $luisApp.appId `
                --versionId $versionToExport `
                --endpoint $config.cognitiveModels.endpoint `
                --subscriptionKey $luisApp.subscriptionKey
```
(with appropriately filled variables).
2. Run 
```
bf luis:version:import `
                    --in $tempJsonPath `
                    --appId $luisApp.appId `
                    --versionId $portalExportObject.versionId `
                    --endpoint $config.cognitiveModels.endpoint `
                    --subscriptionKey $luisApp.subscriptionKey
```
(with appropriately filled variables).
3. Error in screenshot now shows up in the CLI.

Alternatively you can import the result from step 1 to the LUIS portal and get this error: 
![image](https://user-images.githubusercontent.com/64589372/85104644-37de8080-b209-11ea-8b71-57e9921dee57.png)

## Expected behavior
When I call bf luis:version:export I expect a json result that can be used as a parameter for bf luis:version:import

## Screenshots
![image](https://user-images.githubusercontent.com/64589372/85104195-6dcf3500-b208-11ea-9d9c-d0a7ace4abd7.png)

## Additional context
I feel like this is likely an issue with LUIS' API. Nonetheless, I wanted to post it here first before heading over to stackoverflow to post the same report with a LUIS tag.

[bug]

**Comment by munozemilio** [comment]
@felixvanleeuwen  I will provide a nightly soon to address this. I will keep you posted once this is out

**Comment by felixvanleeuwen** [comment]
Any movement on this?

**Comment by munozemilio** [comment]
@felixvanleeuwen  Can you please try the nightly build?

**Comment by felixvanleeuwen** [comment]
Nightly fixed the issue, importing JSONs from the export now works without a hitch. 
Thank you for your effort! 😁
