### ISSUE TITLE
bf luis:convert doesn't support lu file format fully

### ISSUE THREAD

**Issue by jbinko** [microsoft/botframework-cli#865]
bf --version
@microsoft/botframework-cli/4.9.1 linux-x64 node-v8.17.0

bf luis:convert
Is not able to work with officially documented elements for the *.lu file format.

E.g.
Syntax from here:
https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lu-file-format?view=azure-bot-service-4.0#tie-features-to-a-specific-model

(Sorry Formatting of this editor is not showing the original format)
`
@ ml address
@ address =
    - @ ml streetName
`

Gives error:
Unknown error during execution. Please file an issue on https://github.com/microsoft/botframework-cli/issues
Invalid regular expression: /^((?<leadingSpaces>[ ]*)|(?<leadingTabs>[\t]*))-\s*@\s*(?<instanceOf>[^\s]+) (?<entityName>(?:'[^']+')|(?:"[^"]+")|(?:[^ '"=]+))(?: uses?[fF]eatures? (?<features>[^=]+))?\s*=?\s*$/: Invalid group

But in portal
https://www.luis.ai/
you can import such file/syntax successfully.

Similar issue is with qna syntax:
https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-qna-file-format?view=azure-bot-service-4.0#question-and-answer-pairs

(Sorry Formatting of this editor is not showing the original format)
`
### ? who is the ceo?
```
blabla
```
`

[ERROR] Error happened when parsing qna section: Invalid regular expression: /^```(markdown)?\r*\n(?<answer>(.|\n|\r\n|\t| )*)\r?\n.*?```$/: Invalid group

I expect bf luis:convert
will accept the syntax as portal and will generate valid/expected json file

**Comment by amistry79** [comment]
I am facing the same issue. I exported the latest .lu file from LUIS portal and which has the latest syntax with @{} and I am getting parsing error. Do let us know if there is any work around for the same.

**Comment by vishwacsena** [comment]
@jbinko @amistry79 `bf-cli` requires [node version >= 10.17](https://github.com/microsoft/botframework-cli#installation). 

I see you are on `8.xx`. Can you please upgrade your node version to [LTS](https://nodejs.org/en/download/) and try the `luis:convert` and `qnamaker:convert` commands? 

I just verified that your example .lu and .qna content parse successfully. 

```bash
>bf --version
@microsoft/botframework-cli/4.10.0-preview.139191 win32-x64 node-v12.16.1
```

@munozemilio could we look at adding a min node version check in the core BF CLI?
