### ISSUE TITLE
Chatdown- converting .transcript to .chat file

### ISSUE THREAD

**Issue by saikumaru** [microsoft/botframework-cli#867]
## Tool
Name: [Chatdown]

## Describe the problem
we need a clean method of converting of transcript logs to a human readable format, and chtdown is one possible way, however it currently just does the reverse, i.e. converting .chat to .transcript. This is necessary when we want to analyse the transcripts visually.

## Describe the solution you'd like
Can we have a tool like "Chatup" which can convert .transcript to .chat, that will help to convert transcript json files to a more readable format.

## Describe alternatives you've considered
There is no clear alternative yet. But one way would be to parse the JSON and build some custom libraries to convert transcripts back to markdown.

Appreciate if you can instead suggest a way to convert the JSONs to markdown, also handling the adaptive cards and multi-line messages.

[enhancement]

**Comment by saikumaru** [comment]
Thank you for your response, I will begin looking at possibilities.

**Comment by carlosscastro** [comment]
Closing because we are not planning this work in the immediate future.
