### ISSUE TITLE
bf crosstrain, if qna file is empty, we should not crosstrained for qna and generated an non-empty qna file

### ISSUE THREAD

**Issue by luhan2017** [microsoft/botframework-cli#878]
## Versions
What CLI version are you using.
What Nodejs version are you using
What command-line interpreters are you using
What OS are you using

## Describe the bug
@vishwacsena , in composer, the expected behavior is if qna file is empty, user don't need to input a qna authoring key, and the qnabuild should not be called. but we found that the crosstrain did generate a non-empty qna file.

The expected logic should be:
only of lu and qna file both exist, it trains cross the qna and lu.
if lu is empty, just keep qna, and don't do the crosstrain.
if qna is empty, just crosstrain luis, don't write anything into qna file.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by feich-ms** [comment]
Fixed in PR #889
