### ISSUE TITLE
qnabuild write dialog assets for each dialog instead of writing a shared set

### ISSUE THREAD

**Issue by feich-ms** [microsoft/botframework-cli#879]
## Versions
What CLI version are you using.
What Nodejs version are you using
What command-line interpreters are you using
What OS are you using

## Describe the bug
In crosstrain CLI, when cross training qna with luis, the `DeferToRecognizer_QnA_{dialogName}` should change to `DeferToRecognizer_QnA_{botName}` as runtime is trying to find the recognizer by the suffix. Since we are generating dialog with botName as the file name prefix instead of dialogName in qnamaker:build, so for composer, it requires `DeferToRecognizer_QnA_{botName}`. To resolve this, we need to add one more `botName` parameter for luis/qnamaker: crosstrain cmd. What do you think? @vishwacsena 

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by boydc2014** [comment]
triaged, this is not the direction, we should follow up with dialog name

**Comment by feich-ms** [comment]
yes, we should not touch dialog name in filter. Instead I made changes in qnamaker build to write out dialog files for each dialog but the recognier pointing to merged KBs based on locales. PR is here https://github.com/microsoft/botframework-cli/pull/889
