### ISSUE TITLE
Move CrossTrainRecognizer generation logic from lubuild/qnabuild to crosstrain 

### ISSUE THREAD

**Issue by luhan2017** [microsoft/botframework-cli#880]
we hit some issue when enable qna and crosstrain recognizer in composer. So I propose to have a more clear design of the functionality of each lib. We should not put the crosstrain recognizer logic in qnabuild or lubuild, what if non-composer users and they don't care about crosstrain? I think crosstrain recognizer genration logic should be in crosstrain library. 

The whole crosstrain + lubuild + qnabuild process should look like this.
1. composer will call crosstrain api.
Here is the crosstrain logic.
if .lu and .qna are both empty. do nothing, and just generate a CrossTrainedRecognizer with no recognizers inside.
if only .lu not empty. crosstrain on lu only, and generate a crosstrainedrecognizer with lu recognizer only. 
if only .qna not empty. no need crosstrain, and generate a crosstrainedrecognzier with qna recognizer only.
if both not empty, crosstrain them, and generate a crosstrained recognizer with both lu and qna.

lubuild don't care qna, qnabuild don't care lu.
they just take the .lu files or .qna files if files are not empty, prompt for keys and generate the multilanuage luis/qna recognizer. 
 
@vishwacsena, @boydc2014 thoughts?

**Comment by feich-ms** [comment]
I don't think it's necessary to move CrossTrainRecognizer generation logic to crosstrain library. It will confuse users if we have CrosstTrainedRecognizer and other recogizers generated in different library. I prefer to optimize the lu/qnamaker build apis to provide a function for users to generate empty crosstrained recognizer when both .lu and .qna are empty files. Currently I have three functions exposed in builder.ts. The flow to use them are: 

loadContents() => load lu files and generate empty recognizers including single recognizer, multi language recognizer and crosstrained recognizer

build() => load lu contens and all empty recognizers from loadContents() and fill the recognizers with appid/kbid and other information after luis/qnamaker published, and then generate all contents that need to write out ot print

writeDialogAssets() => write recognizers and settings contents generated from build() function

I think for `.lu and .qna are both empty` scenario, we can make changes in loadContents() to return a flag to indicate whether all lu and qna files are empty, if so, directly call writeDialogAssets() to write empty crosstrained recognizer only.

**Comment by feich-ms** [comment]
Fixed in PR #889
