### ISSUE TITLE
Security issue since QnA Maker image URLs needs to be public.

### ISSUE THREAD

**Issue by Vigneshramkumar** [microsoft/botframework-cli#881]
## Versions
Name: QnA Maker and MS Teams
Version: latest
OS: all

## Describe the bug
QnA Maker images needs to be public and this will cause security issue since that is accessible from outside. Also images are not getting rendered in MS Teams

## To Reproduce

1. Create a QnA Maker and add public image URL

## Expected behavior

QnA Maker image URLs should not be public or else there should be a way where the private URLs can be trained and it should render in MS Teams channel when bot replies with QnA Maker reply with that private URL

## Additional context
Kindly let us know where it is possible to train with private URL and render the private URL in Teams bot after getting the response from QnA Maker API. Please let us know is there any way we can provide authorization to Teams or bot to render that URL in Teams.

[bug]

**Comment by munozemilio** [comment]
Hello @Vigneshramkumar can you provide details on how you are using the CLI for this?

**Comment by vishwacsena** [comment]
@pchoudhari can you comment?

**Comment by Vigneshramkumar** [comment]
@munozemilio - I am using QnA Maker portal for training the KB. There have to provide images for response and that images need not to be publically available since that are internal to company and cannot be exposed. Is there any other way for saving the images that is not exposed to internet.
QnA Maker Portal
![image](https://user-images.githubusercontent.com/17233137/87182953-c626bd80-c302-11ea-95f9-948b69c9d55a.png)

**Comment by vishwacsena** [comment]
@pchoudhari can you comment? Also this seems to be a general QnA Maker question and not related to BF CLI.

**Comment by DishaAgarwal** [comment]
@Vigneshramkumar Hello, Currently there is no way to render private image links in Teams right now.

**Comment by Vigneshramkumar** [comment]
@DishaAgarwal - Thanks for the response. Is there any chance of including that feature in near future? Because private image repo is very critical for many business.

**Comment by DishaAgarwal** [comment]
@Vigneshramkumar Thanks for the feedback. We are making a note of your request. While we don't have it as a priority item currently, we will keep our documents updated if we build in the functionality to include private images.
