### ISSUE TITLE
update_cognitive_models.ps1 misbehave when Machine learning features are added

### ISSUE THREAD

**Issue by GitDruid** [microsoft/botframework-cli#900]
#### What project is affected?
Skill template

#### What language is this in?
C#

#### What happens?
When a Machine learning feature is added to an intent on the LUIS authoring page, the execution of update_cognitive_models.ps1 (RemoteToLocal=true) does not generate the xxxLuis.cs file.
The cli tool ends with a successfull "> Update complete." message, no warning is presented. 
Just the log file (update_cognitive_models_log.txt) reports the error:

```
AZ CLI passes minimum version. Current version is 2.8.0
[ERROR] line 19:0 - line 19:57: Features must be defined before assigned to an intent. No definition found for feature ""Application synonyms"" in usesFeature definition for intent "Application"
Invalid LUIS JSON file content.
```

#### What are the steps to reproduce this issue?

1. Create an empty Skill from the template.
2. Add a new intent on LUIS authoring for that skill.
3. Add a "Machine learning feature" to that intent.
4. Train and publish.
5. Execute update_cognitive_models.ps1 (RemoteToLocal=true) 

#### What were you expecting to happen?
See in my project the xxxLuis.cs file updated with the new intent.

#### Can you share any logs, error output, etc.?
The json file is as follows (it seems a matter of order of the intent and feature definition in the json):

```
MySkill.json

{
  "name": "myskillen-us_MySkill",
  "versionId": "0.1",
  "desc": "",
  "culture": "en-us",
  "intents": [
    {
      "name": "Application",
      "features": [
        {
          "featureName": "Application synonyms",
          "isRequired": false
        }
      ]
    },
    {
      "name": "None",
      "features": []
    },
    {
      "name": "Sample",
      "features": []
    }
  ],
  "entities": [],
  "closedLists": [],
  "composites": [],
  "hierarchicals": [],
  "patternAnyEntities": [],
  "regexEntities": [],
  "prebuiltEntities": [],
  "regexFeatures": [],
  "phraselists": [
    {
      "activated": true,
      "name": "Application synonyms",
      "words": "Application,Web pages,Sites",
      "mode": true,
      "enabledForAllModels": false
    }
  ],
  "patterns": [],
  "utterances": [
    {
      "text": "demo dialog",
      "intent": "Sample",
      "entities": []
    },
    {
      "text": "goodbye",
      "intent": "None",
      "entities": []
    },
    {
      "text": "hello",
      "intent": "None",
      "entities": []
    },
    {
      "text": "hi",
      "intent": "None",
      "entities": []
    },
    {
      "text": "list the applications i'm allowed to",
      "intent": "Application",
      "entities": []
    },
    {
      "text": "logout",
      "intent": "None",
      "entities": []
    },
    {
      "text": "may you list me my applications?",
      "intent": "Application",
      "entities": []
    },
    {
      "text": "run dialog",
      "intent": "Sample",
      "entities": []
    },
    {
      "text": "run sample dialog",
      "intent": "Sample",
      "entities": []
    },
    {
      "text": "sample dialog",
      "intent": "Sample",
      "entities": []
    },
    {
      "text": "test dialog",
      "intent": "Sample",
      "entities": []
    },
    {
      "text": "to what application i've access?",
      "intent": "Application",
      "entities": []
    },
    {
      "text": "what are my applications?",
      "intent": "Application",
      "entities": []
    }
  ],
  "luis_schema_version": "7.0.0",
  "tokenizerVersion": "1.0.0",
  "settings": []
}
```

#### Any screenshots or additional context?
No.

**Comment by compulim** [comment]
@munozemilio Please funnel to the right person. 😉

**Comment by munozemilio** [comment]
Hi @vishwacsena is it possible for you to check on this one please?

**Comment by vishwacsena** [comment]
@lauren-mills @GitDruid can one of you please attach an export of the LUIS application as JSON instead of LU?

**Comment by vishwacsena** [comment]
Nevermind. I spotted the issue. @GitDruid I believe the space in phrase list name is causing the issue. For now, could you try a phrase list without space in its name and see if that addresses your issue? `ApplicationSynonym` instead of  `Application synonyms`

**Comment by vishwacsena** [comment]
@feich-ms can you help address this issue in the core parser? The following does not parse correctly

```markdown
> LUIS application information
> !# @app.name = myskillen-us_MySkill
> !# @app.versionId = 0.1
> !# @app.culture = en-us
> !# @app.luis_schema_version = 7.0.0
> !# @app.tokenizerVersion = 1.0.0

# Application

@ intent Application usesFeature ApplicationSynonyms

@ phraselist "Application Synonyms"(interchangeable) disabledForAllModels = 
	- Application,Web pages,Sites
```

But this (without spaces in phrase list name) parses correctly. Looks like we need a grammar fix? 

```markdown
> LUIS application information
> !# @app.name = myskillen-us_MySkill
> !# @app.versionId = 0.1
> !# @app.culture = en-us
> !# @app.luis_schema_version = 7.0.0
> !# @app.tokenizerVersion = 1.0.0

# Application

@ intent Application usesFeature ApplicationSynonyms

@ phraselist ApplicationSynonyms(interchangeable) disabledForAllModels = 
	- Application,Web pages,Sites
```

Tagging R10, LU

**Comment by GitDruid** [comment]
> Nevermind. I spotted the issue. @GitDruid I believe the space in phrase list name is causing the issue. For now, could you try a phrase list without space in its name and see if that addresses your issue? `ApplicationSynonym` instead of `Application synonyms`

Yes, you are right @vishwacsena : removing the space in the feature name solved the issue.

**Comment by feich-ms** [comment]
@vishwacsena, sorry, I missed the github email yesterday. Will send a PR today.

**Comment by feich-ms** [comment]
Fixed in this PR https://github.com/microsoft/botframework-cli/pull/915. Test case from above is also added.
