### ISSUE TITLE
bf luis:generate:cs not taking the className flag correctly

### ISSUE THREAD

**Issue by manish-95** [microsoft/botframework-cli#914]
## Versions
 
**BF CLI**: @microsoft/botframework-cli/4.10.0-dev.20200721.8bb21ac 
**Node version**: node-v14.6.0
**CLI**: PowerShell 6.2.2
What OS are you using : Windows 10 win32-x64

## Describe the bug
For the className arg, I am passing a name which contains an underscore "EmceeSkill_DevBotLuis". However the generated output ignores the special character and gives me the class name as "EmceeSkillDevBotLuis". This causes numerous errors in code, and manually requires me to add the underscore into the generated output file.

## To Reproduce
1. Run the bf luis:version:export command to generate the required output .json
2. Run the bf luis:generate:cs command giving className with an underscore
3. Check the generated output file, it does not match the name given as an option

## Expected behavior
The command must make no changes to the className provided by the user, and generate an output that will not cause code issues.

## Screenshots
Note the command, containing the name desired by the user, and the actual output class name
![image](https://user-images.githubusercontent.com/29098159/88634603-38a1e680-d0d4-11ea-9fc9-b4e94a3a48d4.png)
![image](https://user-images.githubusercontent.com/29098159/88634788-77d03780-d0d4-11ea-997d-aba2a020582c.png)

## Additional context
Switched over to nightly feeds since the fix incorporated as part of #848 is not yet released as a GA version.

[bug]

**Comment by EricDahlvang** [comment]
Hi @manish-95 

Thank you for raising this issue, and noticing the fix is in the nightly.  This will be released in August as part of our 4.10 release cycle.

**Comment by manish-95** [comment]
@EricDahlvang The fix for this was not part of the nightly build I am using. The fix available is for another issue , ie #848 . This issue still exists even in the nightly build.

**Comment by EricDahlvang** [comment]
Apologies, maybe i closed this too early.  Does this PR fix the issue?

https://github.com/microsoft/botframework-cli/pull/857

**Comment by manish-95** [comment]
@EricDahlvang #857 fixes #848 . The bug I have still exists. If I provide the className flag as part of the arguments to the bf luis:generate:cs command, and the name provided contains an underscore, eg Name_Luis, the output cs file generated has the class name as NameLuis.

**Comment by EricDahlvang** [comment]
@munozemilio  Would you please look at this one?

**Comment by EricDahlvang** [comment]
@manish-95  Have you tried working around this by using names without underscores?

**Comment by manish-95** [comment]
Hi @EricDahlvang 
  I'm sure this would work, however, the bot and all its resources were deployed using the deploy.ps1 script provided, which converts hyphens in the resource group name, to underscores in the namespaces across the code. Changing the class name of the LUIS helper would require a lot of changes in the code itself.

**Comment by axelsrz** [comment]
Hello @manish-95 thanks for your feedback. The behavior your describing from luis:generate command is expected. By [C# convetion](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces), classes and interfaces should be PascalCase and that's why the tool converts from other casing styles to the standard.

Regarding what you mention from the deploy.ps1 script, I contacted the VA team and they said that it shouldn't modify any code base, so we would appreciate if you can point us to the exact part that could be changing your class names.


The recommendation here would be (ideally) to change your code base to use PascalCasing for class names.

**Comment by manish-95** [comment]
@axelsrz Our DevOps team had provided a hyphen in the resource name while providing it, which changed the class name of the LUIS helper class to one with an underscore in place of the hyphen, so I guess the change is indeed on our end. Thanks.
