### ISSUE TITLE
LU format link reference additions

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botframework-cli#917]
LU format today only supports `[description](link)` notation for imports as well as resolving references. We should expand this to support the following markdown notation

```markdown
[import][1]

# intent 1
- [reference][2]

[1]:foo.lu
[2]:bar.lu#intent2
```

**Comment by vishwacsena** [comment]
@feich-ms can you help?

**Comment by feich-ms** [comment]
sure, will take a look.
