### ISSUE TITLE
Review Endpoint Utterances with dispatch

### ISSUE THREAD

**Issue by shikshik** [microsoft/botframework-cli#930]
Hey, great work on moving all tools under 1 CLI, makes life much more easier.

I couldn't find any option to return the endpoint utterances for dispatch app for active learning.
Is there a tool to add endpoint utterances for dispatch app in the new CLI?
What will be the right flow for adding those to a dispatcher and to a second level luis app connected to the dispatch app?

There isn't even export option in luis.ai site for manual entering those in the dispach CLI tool.

Thanks!

**Comment by tsuwandy** [comment]
@shikshik , do you normally review endpoint utterances for dispatch app on luis.ai portal?  

To add utterances directly to Dispatch and make sure those are persisted with dispatch refreshes, add those utterances to a text file and add them to dispatch with the same intent name as the LUIS sub app.  

More information here:
https://github.com/microsoft/botbuilder-tools/blob/master/packages/Dispatch/readme.md#updating-dispatch

Please let me know if you need more info.  Thanks!

**Comment by carlosscastro** [comment]
Closing since @tsuwandy seems to have answered the question. Please reactivate if needed, thanks!

**Comment by shikshik** [comment]
Issue was not solved.

I'm using dispatch CLI to update dispatch, as the docs suggest.
There is no way to export "Review Endpoint Utterances" list from luis.ai which is the main problem.

Either allow exporting so we can add manually to the dispatch CLI or allow the dispatch CLI tool to do it (much better solution).

**Comment by tsuwandy** [comment]
@shikshik, luis.ai has a way to export the endpoint logs:

![64083BC1-37D3-459E-B22F-624B269D7D26](https://user-images.githubusercontent.com/10739108/90036738-36b15900-dc78-11ea-919e-f449f624621f.png)

Have you tried this?

**Comment by shikshik** [comment]
@tsuwandy , Thanks you!
I guess my intuitive action was to look for export in that specific page instead of the "My Apps" page.

I will give it a try. Thanks again!
