### ISSUE TITLE
Enable customized import resolver in LUParser

### ISSUE THREAD

**Issue by zhixzhan** [microsoft/botframework-cli#933]
**Is your feature request related to a problem? Please describe.**

Composer are bring in Lu reference feature, it requires two place support customized resolver
1. `parse` method in `luParser`
2. CRUD methods  in `sectionOperator`
3. parse result add `allSections` include imported file's section (for editor intelligence)
4. parse result's `diagnostics` need include imported file's diagnostics

**Comment by feich-ms** [comment]
This can be done by the existing functions. You can use such [function flow](https://github.com/microsoft/botframework-cli/blob/98731ad1c06a0e98027bd427474ba52b7ace7fb0/packages/lu/src/parser/lubuild/builder.ts#L86-L88) to resolve imports and get the resolved lu content. Then use current luparser.parse to parse the resolved lu content and get all sections that contains imported ones.

**Comment by zhixzhan** [comment]
I see, the result of 
```LuisBuilderVerbose.build(luFiles, true, fileCulture, fileResolver);```
 contains all `entities, patterns, intents`

<img width="442" alt="image" src="https://user-images.githubusercontent.com/49866537/90749655-50047600-e306-11ea-88c5-22d612e2e534.png">

It will resolve item no.3

**Comment by feich-ms** [comment]
close this issue since there is already a solution there.
