### ISSUE TITLE
"Update available" reminder invalidate the output json schema

### ISSUE THREAD

**Issue by dawwa** [microsoft/botframework-cli#937]
## Versions
4.9

## Describe the bug
The extra reminder content injected into the output and invalidates the json.
Consumer scripts might rely on the output and has been parsing into json object, injecting additional output in free form caused regression in deployment automation. 

- Provide a flag to turn off the reminder would work as an option to fix this.
- The -o option to a json file is not impacted by this, but for our deployment automation, the unnecessary file I/O is not preferred comparing to parsing STDOUT; hope to have the option to ensure consistency between STDOUT and -o file, OR provide an additional option to -o to a variable.
- Also wondering why it still prompts update available even every time we're running `npm install -g @microsoft/botframework-cli` already at the beginning, without specifying the version, which implies the latest version I guess?

## Screenshots
![image](https://user-images.githubusercontent.com/44714043/90336089-5a351600-df8e-11ea-9bc7-68fb32ff3021.png)

![image](https://user-images.githubusercontent.com/44714043/90335960-5ce33b80-df8d-11ea-96a5-f0b9d6e25b73.png)

## Additional context
@munozemilio @vishwacsena , shall we have another environment variable to control this and provide user an option to opt out the reminder? similar to the BF_CLI_TELEMETRY flag?

## Workaround
Meanwhile, I'm doing bf version at the initialization to work around this.
[bug]

**Comment by clancy** [comment]
Please fix this.

**Comment by FrancoCorleone** [comment]
I can report it broke my scripting as well. Interestingly enough, if I execute that command directly in the console - no message. @dawwa can you tell me more about your workaround?
