### ISSUE TITLE
bf qnamaker:kb:update do not create follow-up prompt

### ISSUE THREAD

**Issue by GitDruid** [microsoft/botframework-cli#946]
## Versions
What CLI version are you using: 4.10.1
What Nodejs version are you using: node-v12.18.0
What command-line interpreters are you using: 7.0.2
What OS are you using: Windows 10 Enterprise

## Describe the bug
When using bf CLI to add QnA List, context field is not taken into account. Follow-up prompt feature is not created.

## To Reproduce
1. Create a knowledge base on QnA Maker with just one sample question-answer pair.
2. Create a file named "UpdateKbOperationDTO.json" with following content (element 101 is related to 100 with the Context):
```
{
  "Add": {
    "QnaList": [
      {
        "Id": "100",
        "Source": "Editorial (script)",
        "Context": {},
        "Questions": ["Question 1", "Question 2"],
        "Answer": "Answer 1",
        "Metadata": [
          {
            "Name": "SampleMetadata",
            "Value": "SampleValue"
          }
        ]
      },
      {
        "Id": "101",
        "Source": "Editorial (script)",
        "Context": {
          "IsContextOnly": false,
          "Prompts": [
            {
              "DisplayOrder": 1,
              "DisplayText": "Text",
              "Qna": null,
              "QnaId": 100
            }
          ]
        },
        "Questions": ["Question 3", "Question 4"],
        "Answer": "Answer 2",
        "Metadata": [
          {
            "Name": "SampleMetadata",
            "Value": "SampleValue"
          }
        ]
      }
    ]
  }
}

```
3. Execute the following command to upload additional question-and-answers from the file:
`bf qnamaker:kb:update --subscriptionKey=xxx --kbId=yyy --wait --in=UpdateKbOperationDTO.json`
4. Go on QnA Maker page to see the result

## Expected behavior
Have two QnA pair related through the follow-up prompt

## Screenshots
Attached the screenshot of the QnA MAker page.
![qna](https://user-images.githubusercontent.com/4527837/90774494-debdc680-e2f7-11ea-84f6-cb783946b9cf.png)

## Additional context

[bug]

**Comment by GitDruid** [comment]
Doing a KB export I just saw that the Id provided in the file is overwritten on the server.
Probably that's why the follow-up link is not created.
So, how can I link two QnA entries?

**Comment by lauren-mills** [comment]
@munozemilio - can you take a look at this?

**Comment by munozemilio** [comment]
Thanks for bringing this up @GitDruid, I will try to reproduce and get back to you.

**Comment by tsuwandy** [comment]
@munozemilio, any update?

**Comment by ninggao** [comment]
@munozemilio, revisit this issue, any update?

**Comment by munozemilio** [comment]
Hello @GitDruid I have tested your sample payload against the QnA Service and got the same result. This means the issue is either in the payload or in the QnA Service
![Screen Shot 2020-10-07 at 12 21 31 PM](https://user-images.githubusercontent.com/43281931/95378440-c8180280-0898-11eb-9c39-a8f69bc7dc54.png)

You can test your payloads easily [here](https://westus.dev.cognitive.microsoft.com/docs/services/5a93fcf85b4ccd136866eb37/operations/5ac266295b4ccd1554da7600/console)

Have you tried with the update [payload](https://westus.dev.cognitive.microsoft.com/docs/services/5a93fcf85b4ccd136866eb37/operations/5ac266295b4ccd1554da7600/console)?

**Comment by GitDruid** [comment]
Hi @munozemilio , thanks for the answer.
I've tested with the update payload, as you suggested, and it is working.
So, since it's not possible to set the qnapair id with the add payload, I think that follow-up prompt is not feasible in one single service call. Instead:
- PATCH call to add qna 
- GET knowledge base detail, to obtain IDs
- PATH call to update qna with follow-up prompts

Thanks,
Alessandro.
