### ISSUE TITLE
Not able to send files to QnA Maker using “bf qnamaker:kb:update” command

### ISSUE THREAD

**Issue by GitDruid** [microsoft/botframework-cli#947]
## Versions
What CLI version are you using: 4.10.1
What Nodejs version are you using: node-v12.18.0
What command-line interpreters are you using: 7.0.2
What OS are you using: Windows 10 Enterprise

## Describe the bug
None of the possible FileUri format listed [here](https://en.wikipedia.org/wiki/File_URI_scheme) for windows are accepted.

## To Reproduce
1. Create a file named "UpdateKbOperationDTO.json" with following content:
```
{
  "Add": {
    "Files": [
      {
        "FileName": "sample_file_1.txt",
        "FileUri": "file:///C:/myfolder/QnA/sample_file_1.txt"
      }
    ]
  },
  "DefaultAnswerUsedForExtraction": "",
  "Delete": "",
  "EnableHierarchicalExtraction": "",
  "Update": ""
}
```
2. Execute the following command:
bf qnamaker:kb:update --subscriptionKey=xxx --kbId=yyy --wait --in=UpdateKbOperationDTO.json

## Expected behavior
1. bf executed without error
2. sample_file_1.txt loaded and visible in the QnA settings page
3. QnA extracted from sample_file_1.txt

## Screenshots
```
{
    "code": "BadArgument",
    "message": "Invalid input. See details.",
    "details": [
        {
            "code": "ValidationFailure",
            "message": "File Uri has one or more invalid uri.",
            "target": "Add.Files[0].FileUri"
        }
    ]
}
```
## Additional context
Also tried: 
"file://localhost/c$/myfolder/QnA/sample_file_1.txt", 
"file:///c:/myfolder/QnA/sample_file_1.txt",
and the likes...

[bug]

**Comment by munozemilio** [comment]
Hi @GitDruid this is coming from the qnamaker service directly. Ill try to find out the correct api usage and provide an update

**Comment by munozemilio** [comment]
@GitDruid [this](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/qnamaker/knowledgebase/update#filedto) is the documentation for the qna service. The issue is the url should be public

**Comment by GitDruid** [comment]
Hi Emilio,
thank you for the answer.

However, I do not agree with your analysis. QnA service url IS actually public accessible.
Additionally the script works if I use it just to upload qna pairs or page urls. It just does not work when using local files Uri (like file:///...).
In the documentation page you send me they are using full URL to locate the files, like:

```
    "files": [
      {
        "fileName": "SurfaceManual.pdf",
        "fileUri": "https://download.microsoft.com/download/2/9/B/29B20383-302C-4517-A006-B0186F04BE28/surface-pro-4-user-guide-EN.pdf"
      }
```
And this actually works.
So, my idea is that local files are not supported by the script.

As a side note I'd like to ask you guys at Microsoft to be more supportive on Bot Framework. I'm trying to build up a system based on this framework but encountering a lot of frustrating issues. If you want your system to be adopted by developers you should focus on solve problems more than on just closing github issues.

Best regards,
Alessandro.

**Comment by munozemilio** [comment]
Hi @GitDruid, my apologies for the confusion. I was referring to the fileUri thats way I pointed the link directly to the FileDTO part.
Im very sorry to read you are facing difficulties using the Bot Framework. We are constantly working on improving users support and experience. Please feel free to open as many issues as needed or reopen the ones you believe were not addressed properly. I assure you we really pay attention to them and strive to provide the correct resolution.
We really appreciate you taking the time to report all of this and its very valuable to us getting to understand the user needs.
Thanks,
 Emilio
