### ISSUE TITLE
Make LU parser behavior configurable

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botframework-cli#974]
### Context
.lu file format is the format that we intended to use a standard to define intent classification and entity extraction and there could be different LU technologies (like LUIS, Orchestrator, PVA, etc) that are consuming .lu files. 

The issue is those different LU technologies probably will not support all features in .lu format. Some format in .lu can be considered as core, some can be extensions. We need a way to inform parser that certain features are supported and enabled.

### Proposed Solution
Let lu parser take a config which defines a list of feature flags then parser will treat certain input as normal\error based on those flags.

Sample flags:
- enableMLEntities   // Orchestrator don't support ML type entities

**Comment by vishwacsena** [comment]
@boydc2014 

Listing the capabilities captured in the LU format, it should be possible to both enable/ disable these as well as set validation constraints. May be the validation constraints can be expressed using `Adaptive Expressions`.

1. Intents
2. Utterances
3. Patterns
4. Entities
    a. ML
    b. List
    c. Composite
    d. Prebuilt
    e. Regex
5. Phrase lists
6. Features
7. Model description
8. External references
9. Comments.

AFAIK, Orchestrator and PVA supports 1, 2, 4.d, 7, 8, 9.

**Comment by cwhitten** [comment]
@boydc2014 can we expand on the design a bit? I'm interested in the following:

1. a quick design visual  to show the layering a bit better
2. @vishwacsena 's list and how it maps to core/configurable
3. an example config to share with PVA
4. explanation to how the design is resilient to new features not yet implemented into the file format

**Comment by feich-ms** [comment]
@vishwacsena, `Role` may be also included?

**Comment by vishwacsena** [comment]
No. Roles should not be recognized as a concept going forward. Roles are named instance of a type and you can already model them this way in LU.

@ ml name hasRoles firstName, lastName

Is the same as

@ ml name
@ name firstName
@ name lastName
