### ISSUE TITLE
[Orchestrator] bf orchestrator:build doesn't work with latest model

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botframework-cli#976]
## Versions
@microsoft/botframework-cli/4.10.1 win32-x64 node-v12.16.1

## Describe the bug
following https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/orchestrator/csharp_dotnetcore/03.declarative-bot

instead of downloading the 1.0.0 version, download the 1.1.0 version
1.1.0-pretrained.20200819-12l.microsoft.dte.en.onnx

then run bf orchestrator:build, it will complain 
![image](https://user-images.githubusercontent.com/3829387/93189994-6838ab00-f775-11ea-8188-4de8791285f5.png)

## To Reproduce
working as expected 
## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by tsuwandy** [comment]
Got a repro, taking a look...

**Comment by tsuwandy** [comment]
@boydc2014, latest model needs latest code (which hasn't been published to npmjs yet).  We'll update the core sometime next week.  Till then, could you use this model "1.0.0-pretrained.20200729.microsoft.dte.en.onnx".  Thanks!

**Comment by boydc2014** [comment]
> @boydc2014, latest model needs latest code (which hasn't been published to npmjs yet). We'll update the core sometime next week. Till then, could you use this model "1.0.0-pretrained.20200729.microsoft.dte.en.onnx". Thanks!

once you update the latest code, will it still be back-compatible with previous model?

**Comment by tsuwandy** [comment]
@boydc2014, not unfortunately.  New code will need new model.  We decided to make the breaking change since we are in still preview.  Thanks!

**Comment by boydc2014** [comment]
> @boydc2014, not unfortunately. New code will need new model. We decided to make the breaking change since we are in still preview. Thanks!

Thanks @tsuwandy, that make sense. Breaking changes is acceptable. 

Let me ask the question a little different question, should i expect, "If i updated to lastest tool, the model listed can all be downloaded and be usable"?

**Comment by tsuwandy** [comment]
@boydc2014, yes!  Runtime components need updating as well though.   @feich-ms filed an issue with the orchestrator sample code which requires a push of Microsoft.BotFramework.Orchestrator to NuGet and an update of Microsoft.BotBuilder.AI.Orchestrator package from SDK.  We’ll push to NuGet tomorrow am.  Thanks!

**Comment by boydc2014** [comment]
> @boydc2014, yes! Runtime components need updating as well though. @feich-ms filed an issue with the orchestrator sample code which requires a push of Microsoft.BotFramework.Orchestrator to NuGet and an update of Microsoft.BotBuilder.AI.Orchestrator package from SDK. We’ll push to NuGet tomorrow am. Thanks!

Thanks, get it.

**Comment by tsuwandy** [comment]
@boydc2014 , @feich-ms , let me know if you are still having issues with the cli or the samples (after updating Microsoft.BotBuilder.AI.Orchestrator package from azure artifacts, in nuget.config checked in to orchestrator samples folder.
