### ISSUE TITLE
bf orchestrator:create jsonObjectArray.forEach is not a function

### ISSUE THREAD

**Issue by ecuellar2** [microsoft/botframework-cli#983]
## Versions
What CLI version are you using. @microsoft/botframework-cli/4.10.1 win32-x64 node-v12.18.3
What Nodejs version are you using v12.18.3
bf orchestrator:create --force --model=C:\lib\commands\orchestrator\nlr

What OS are you using windows 10

## Describe the bug
bf orchestrator:create --force --model=C:\lib\commands\orchestrator\nlr

\AppData\\Local\\@microsoft\\botframework-cli\\node_modules\\@microsoft\\bf-orchestrator-cli\\lib\\commands\\orchestrator\\nlr\\vocab.json...\n"
jsonObjectArray.forEach is not a function

## To Reproduce
bf orchestrator:create --force --model=C:\lib\commands\orchestrator\nlr

## Expected behavior
Create orchestrator snapshot (.blu) file from .lu/.qna files

## Additional context

[bug]

**Comment by tdurnford** [comment]
@tsuwandy Can you take a look at this?

**Comment by tsuwandy** [comment]
@ecuellar2, did you provide the --input/-i parameter (path to .lu/.qna files)?

**Comment by ecuellar2** [comment]
Adding in parameter resolved issue. I was confused because the documentation says --in "Default to current working directory". Thank you.

**Comment by tsuwandy** [comment]
Thanks @ecuellar2, we’ll fix the docs.
