### ISSUE TITLE
Add cli for @microsoft/bf-dispatcher

### ISSUE THREAD

**Issue by lei9444** [microsoft/botframework-cli#991]
Now composer use @microsoft/bf-dispatcher as a library in server to do down sampling.

Now composer use bootstramp sampling to balance the utterances' number ratio, and use reservoir sampling to down size the utterances.

To take control of the dialog generation, we want to unify the cli tools. But the bf-dispatcher does not support cli now.
what we want maybe like: do down sample for lu file, then output a new lu file with the result.

**Comment by feich-ms** [comment]
Done in cli side
