### ISSUE TITLE
bf luis:cross-train detection logic for discovering child dialogs is wrong and incomplete.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botframework-cli#997]
## Versions
4.10.1 (and looking at the source code)

## Describe the bug
Looking at the source code I see that the detection of child dialogs is incomplete:
1.  actions can be arbitrarily nested (for example if there is a "If" condition, the action code which is attempting to enumerate begindialogs will not detect the dialog.
2.  it is assuming that there are no direct references to dialogs by resource id
3. it is assuming that all of the content of a dialog is in one file (and the declarative file system allows you to import portions of the dialog from an external .dialog into the context of the dialog.

## To Reproduce
look at confighelper.js line 77, it is simply assuming that the actions are shallow, and is only looking for BeginDialog.
```if (action.$type !== 'Microsoft.BeginDialog') continue```

## Expected behavior
1. actions can be nested arbitrarily deep.
2. BeginDialog is not the only way that dialogs can be invoked.  You can just refer to a dialog directly by name, and other actions may invoke dialogs as well. (RepeatDialog, GotoDialog, etc.)

Unless you are using the declarative type loader to follow all references this approach is completely flawed. 

## Additional context

[bug]

**Comment by boydc2014** [comment]
@feich-ms I assume Composer is not use this dialog structure discovery code, right? I expect Composer is doing it's own dialog discovery and output the result as a config file. 

How about we, at cli side, always requires a full config, and don't try to create some default config with some incomplete logic?

**Comment by feich-ms** [comment]
Yes, Composing is using its own dialog structure discovery logic. The discovery logic in cli side does not cover every scenarios so it is not completed. I already removed any auto-discovering dialog config capability in cli help docs, so now it requires users to provide a full config. I will optimize the code to remove any auto-discovering code and meanwhile make sure users to provide a config before doing cross-train.

**Comment by feich-ms** [comment]
Closed by #1024, there is no config discovery and --config is required in cli now.
